/**
 * The real NIST SP 800-53 Rev. 5 control catalog — index.
 *
 * Generated from the NIST OSCAL release of SP 800-53 Rev. 5 (catalog version
 * 5.2.0, 2026-05-11) and the SP 800-53B Low / Moderate / High baselines.
 * NIST publications are US Government works in the public domain.
 *
 * Do not hand-edit: regenerate from the OSCAL catalog instead.
 */

export type NistBaseline = "Low" | "Moderate" | "High";

export type NistControl = {
  /** Natural key as a human writes it: "AC-2", "AC-2(3)". */
  id: string;
  family: string;
  /** Rev. 5 title, verbatim. Enhancements carry only their own half. */
  title: string;
  /** Base control an enhancement extends, or null. */
  parent: string | null;
  parentTitle: string | null;
  /** SP 800-53B baselines that select this control. Empty = tailored in by an overlay. */
  baselines: NistBaseline[];
};

export type NistStatementItem = { label?: string; prose: string; items?: NistStatementItem[] };
export type NistParameter = { id: string; kind: "Assignment" | "Selection"; value: string; guideline?: string };
export type NistObjective = { label: string; prose: string; items?: NistObjective[] };
export type NistMethod = { method: "Examine" | "Interview" | "Test"; objects: string[] };
export type NistReference = { title: string; url?: string };

/** Everything SP 800-53 and 800-53A say about one control. */
export type NistControlText = {
  statement: NistStatementItem[];
  discussion: string[];
  params: NistParameter[];
  related: string[];
  objectives: NistObjective[];
  methods: NistMethod[];
  references: NistReference[];
};

export const catalogVersion = "NIST SP 800-53 Rev. 5 (5.2.0)";

export const nistFamilies: { id: string; name: string }[] = [{"id":"AC","name":"Access Control"},{"id":"AT","name":"Awareness and Training"},{"id":"AU","name":"Audit and Accountability"},{"id":"CA","name":"Assessment, Authorization, and Monitoring"},{"id":"CM","name":"Configuration Management"},{"id":"CP","name":"Contingency Planning"},{"id":"IA","name":"Identification and Authentication"},{"id":"IR","name":"Incident Response"},{"id":"MA","name":"Maintenance"},{"id":"MP","name":"Media Protection"},{"id":"PE","name":"Physical and Environmental Protection"},{"id":"PL","name":"Planning"},{"id":"PM","name":"Program Management"},{"id":"PS","name":"Personnel Security"},{"id":"PT","name":"Personally Identifiable Information Processing and Transparency"},{"id":"RA","name":"Risk Assessment"},{"id":"SA","name":"System and Services Acquisition"},{"id":"SC","name":"System and Communications Protection"},{"id":"SI","name":"System and Information Integrity"},{"id":"SR","name":"Supply Chain Risk Management"}];

export const nistFamilyName = new Map(nistFamilies.map((f) => [f.id, f.name]));

export const nistControls: NistControl[] = [
  { id: "AC-1", family: "AC", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-2", family: "AC", title: "Account Management", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-2(1)", family: "AC", title: "Automated System Account Management", parent: "AC-2", parentTitle: "Account Management", baselines: ["Moderate","High"] },
  { id: "AC-2(2)", family: "AC", title: "Automated Temporary and Emergency Account Management", parent: "AC-2", parentTitle: "Account Management", baselines: ["Moderate","High"] },
  { id: "AC-2(3)", family: "AC", title: "Disable Accounts", parent: "AC-2", parentTitle: "Account Management", baselines: ["Moderate","High"] },
  { id: "AC-2(4)", family: "AC", title: "Automated Audit Actions", parent: "AC-2", parentTitle: "Account Management", baselines: ["Moderate","High"] },
  { id: "AC-2(5)", family: "AC", title: "Inactivity Logout", parent: "AC-2", parentTitle: "Account Management", baselines: ["Moderate","High"] },
  { id: "AC-2(11)", family: "AC", title: "Usage Conditions", parent: "AC-2", parentTitle: "Account Management", baselines: ["High"] },
  { id: "AC-2(12)", family: "AC", title: "Account Monitoring for Atypical Usage", parent: "AC-2", parentTitle: "Account Management", baselines: ["High"] },
  { id: "AC-2(13)", family: "AC", title: "Disable Accounts for High-risk Individuals", parent: "AC-2", parentTitle: "Account Management", baselines: ["Moderate","High"] },
  { id: "AC-3", family: "AC", title: "Access Enforcement", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-4", family: "AC", title: "Information Flow Enforcement", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "AC-4(4)", family: "AC", title: "Flow Control of Encrypted Information", parent: "AC-4", parentTitle: "Information Flow Enforcement", baselines: ["High"] },
  { id: "AC-5", family: "AC", title: "Separation of Duties", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "AC-6", family: "AC", title: "Least Privilege", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "AC-6(1)", family: "AC", title: "Authorize Access to Security Functions", parent: "AC-6", parentTitle: "Least Privilege", baselines: ["Moderate","High"] },
  { id: "AC-6(2)", family: "AC", title: "Non-privileged Access for Nonsecurity Functions", parent: "AC-6", parentTitle: "Least Privilege", baselines: ["Moderate","High"] },
  { id: "AC-6(3)", family: "AC", title: "Network Access to Privileged Commands", parent: "AC-6", parentTitle: "Least Privilege", baselines: ["High"] },
  { id: "AC-6(5)", family: "AC", title: "Privileged Accounts", parent: "AC-6", parentTitle: "Least Privilege", baselines: ["Moderate","High"] },
  { id: "AC-6(7)", family: "AC", title: "Review of User Privileges", parent: "AC-6", parentTitle: "Least Privilege", baselines: ["Moderate","High"] },
  { id: "AC-6(9)", family: "AC", title: "Log Use of Privileged Functions", parent: "AC-6", parentTitle: "Least Privilege", baselines: ["Moderate","High"] },
  { id: "AC-6(10)", family: "AC", title: "Prohibit Non-privileged Users from Executing Privileged Functions", parent: "AC-6", parentTitle: "Least Privilege", baselines: ["Moderate","High"] },
  { id: "AC-7", family: "AC", title: "Unsuccessful Logon Attempts", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-8", family: "AC", title: "System Use Notification", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-10", family: "AC", title: "Concurrent Session Control", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "AC-11", family: "AC", title: "Device Lock", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "AC-11(1)", family: "AC", title: "Pattern-hiding Displays", parent: "AC-11", parentTitle: "Device Lock", baselines: ["Moderate","High"] },
  { id: "AC-12", family: "AC", title: "Session Termination", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "AC-14", family: "AC", title: "Permitted Actions Without Identification or Authentication", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-17", family: "AC", title: "Remote Access", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-17(1)", family: "AC", title: "Monitoring and Control", parent: "AC-17", parentTitle: "Remote Access", baselines: ["Moderate","High"] },
  { id: "AC-17(2)", family: "AC", title: "Protection of Confidentiality and Integrity Using Encryption", parent: "AC-17", parentTitle: "Remote Access", baselines: ["Moderate","High"] },
  { id: "AC-17(3)", family: "AC", title: "Managed Access Control Points", parent: "AC-17", parentTitle: "Remote Access", baselines: ["Moderate","High"] },
  { id: "AC-17(4)", family: "AC", title: "Privileged Commands and Access", parent: "AC-17", parentTitle: "Remote Access", baselines: ["Moderate","High"] },
  { id: "AC-18", family: "AC", title: "Wireless Access", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-18(1)", family: "AC", title: "Authentication and Encryption", parent: "AC-18", parentTitle: "Wireless Access", baselines: ["Moderate","High"] },
  { id: "AC-18(3)", family: "AC", title: "Disable Wireless Networking", parent: "AC-18", parentTitle: "Wireless Access", baselines: ["Moderate","High"] },
  { id: "AC-18(4)", family: "AC", title: "Restrict Configurations by Users", parent: "AC-18", parentTitle: "Wireless Access", baselines: ["High"] },
  { id: "AC-18(5)", family: "AC", title: "Antennas and Transmission Power Levels", parent: "AC-18", parentTitle: "Wireless Access", baselines: ["High"] },
  { id: "AC-19", family: "AC", title: "Access Control for Mobile Devices", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-19(5)", family: "AC", title: "Full Device or Container-based Encryption", parent: "AC-19", parentTitle: "Access Control for Mobile Devices", baselines: ["Moderate","High"] },
  { id: "AC-20", family: "AC", title: "Use of External Systems", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AC-20(1)", family: "AC", title: "Limits on Authorized Use", parent: "AC-20", parentTitle: "Use of External Systems", baselines: ["Moderate","High"] },
  { id: "AC-20(2)", family: "AC", title: "Portable Storage Devices — Restricted Use", parent: "AC-20", parentTitle: "Use of External Systems", baselines: ["Moderate","High"] },
  { id: "AC-21", family: "AC", title: "Information Sharing", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "AC-22", family: "AC", title: "Publicly Accessible Content", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AT-1", family: "AT", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AT-2", family: "AT", title: "Literacy Training and Awareness", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AT-2(2)", family: "AT", title: "Insider Threat", parent: "AT-2", parentTitle: "Literacy Training and Awareness", baselines: ["Low","Moderate","High"] },
  { id: "AT-2(3)", family: "AT", title: "Social Engineering and Mining", parent: "AT-2", parentTitle: "Literacy Training and Awareness", baselines: ["Moderate","High"] },
  { id: "AT-3", family: "AT", title: "Role-based Training", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AT-4", family: "AT", title: "Training Records", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-1", family: "AU", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-2", family: "AU", title: "Event Logging", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-3", family: "AU", title: "Content of Audit Records", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-3(1)", family: "AU", title: "Additional Audit Information", parent: "AU-3", parentTitle: "Content of Audit Records", baselines: ["Moderate","High"] },
  { id: "AU-4", family: "AU", title: "Audit Log Storage Capacity", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-5", family: "AU", title: "Response to Audit Logging Process Failures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-5(1)", family: "AU", title: "Storage Capacity Warning", parent: "AU-5", parentTitle: "Response to Audit Logging Process Failures", baselines: ["High"] },
  { id: "AU-5(2)", family: "AU", title: "Real-time Alerts", parent: "AU-5", parentTitle: "Response to Audit Logging Process Failures", baselines: ["High"] },
  { id: "AU-6", family: "AU", title: "Audit Record Review, Analysis, and Reporting", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-6(1)", family: "AU", title: "Automated Process Integration", parent: "AU-6", parentTitle: "Audit Record Review, Analysis, and Reporting", baselines: ["Moderate","High"] },
  { id: "AU-6(3)", family: "AU", title: "Correlate Audit Record Repositories", parent: "AU-6", parentTitle: "Audit Record Review, Analysis, and Reporting", baselines: ["Moderate","High"] },
  { id: "AU-6(5)", family: "AU", title: "Integrated Analysis of Audit Records", parent: "AU-6", parentTitle: "Audit Record Review, Analysis, and Reporting", baselines: ["High"] },
  { id: "AU-6(6)", family: "AU", title: "Correlation with Physical Monitoring", parent: "AU-6", parentTitle: "Audit Record Review, Analysis, and Reporting", baselines: ["High"] },
  { id: "AU-7", family: "AU", title: "Audit Record Reduction and Report Generation", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "AU-7(1)", family: "AU", title: "Automatic Processing", parent: "AU-7", parentTitle: "Audit Record Reduction and Report Generation", baselines: ["Moderate","High"] },
  { id: "AU-8", family: "AU", title: "Time Stamps", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-9", family: "AU", title: "Protection of Audit Information", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-9(2)", family: "AU", title: "Store on Separate Physical Systems or Components", parent: "AU-9", parentTitle: "Protection of Audit Information", baselines: ["High"] },
  { id: "AU-9(3)", family: "AU", title: "Cryptographic Protection", parent: "AU-9", parentTitle: "Protection of Audit Information", baselines: ["High"] },
  { id: "AU-9(4)", family: "AU", title: "Access by Subset of Privileged Users", parent: "AU-9", parentTitle: "Protection of Audit Information", baselines: ["Moderate","High"] },
  { id: "AU-10", family: "AU", title: "Non-repudiation", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "AU-11", family: "AU", title: "Audit Record Retention", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-12", family: "AU", title: "Audit Record Generation", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "AU-12(1)", family: "AU", title: "System-wide and Time-correlated Audit Trail", parent: "AU-12", parentTitle: "Audit Record Generation", baselines: ["High"] },
  { id: "AU-12(3)", family: "AU", title: "Changes by Authorized Individuals", parent: "AU-12", parentTitle: "Audit Record Generation", baselines: ["High"] },
  { id: "CA-1", family: "CA", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CA-2", family: "CA", title: "Control Assessments", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CA-2(1)", family: "CA", title: "Independent Assessors", parent: "CA-2", parentTitle: "Control Assessments", baselines: ["Moderate","High"] },
  { id: "CA-2(2)", family: "CA", title: "Specialized Assessments", parent: "CA-2", parentTitle: "Control Assessments", baselines: ["High"] },
  { id: "CA-3", family: "CA", title: "Information Exchange", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CA-3(6)", family: "CA", title: "Transfer Authorizations", parent: "CA-3", parentTitle: "Information Exchange", baselines: ["High"] },
  { id: "CA-5", family: "CA", title: "Plan of Action and Milestones", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CA-6", family: "CA", title: "Authorization", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CA-7", family: "CA", title: "Continuous Monitoring", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CA-7(1)", family: "CA", title: "Independent Assessment", parent: "CA-7", parentTitle: "Continuous Monitoring", baselines: ["Moderate","High"] },
  { id: "CA-7(4)", family: "CA", title: "Risk Monitoring", parent: "CA-7", parentTitle: "Continuous Monitoring", baselines: ["Low","Moderate","High"] },
  { id: "CA-8", family: "CA", title: "Penetration Testing", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "CA-8(1)", family: "CA", title: "Independent Penetration Testing Agent or Team", parent: "CA-8", parentTitle: "Penetration Testing", baselines: ["High"] },
  { id: "CA-9", family: "CA", title: "Internal System Connections", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-1", family: "CM", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-2", family: "CM", title: "Baseline Configuration", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-2(2)", family: "CM", title: "Automation Support for Accuracy and Currency", parent: "CM-2", parentTitle: "Baseline Configuration", baselines: ["Moderate","High"] },
  { id: "CM-2(3)", family: "CM", title: "Retention of Previous Configurations", parent: "CM-2", parentTitle: "Baseline Configuration", baselines: ["Moderate","High"] },
  { id: "CM-2(7)", family: "CM", title: "Configure Systems and Components for High-risk Areas", parent: "CM-2", parentTitle: "Baseline Configuration", baselines: ["Moderate","High"] },
  { id: "CM-3", family: "CM", title: "Configuration Change Control", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "CM-3(1)", family: "CM", title: "Automated Documentation, Notification, and Prohibition of Changes", parent: "CM-3", parentTitle: "Configuration Change Control", baselines: ["High"] },
  { id: "CM-3(2)", family: "CM", title: "Testing, Validation, and Documentation of Changes", parent: "CM-3", parentTitle: "Configuration Change Control", baselines: ["Moderate","High"] },
  { id: "CM-3(4)", family: "CM", title: "Security and Privacy Representatives", parent: "CM-3", parentTitle: "Configuration Change Control", baselines: ["Moderate","High"] },
  { id: "CM-3(6)", family: "CM", title: "Cryptography Management", parent: "CM-3", parentTitle: "Configuration Change Control", baselines: ["High"] },
  { id: "CM-4", family: "CM", title: "Impact Analyses", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-4(1)", family: "CM", title: "Separate Test Environments", parent: "CM-4", parentTitle: "Impact Analyses", baselines: ["High"] },
  { id: "CM-4(2)", family: "CM", title: "Verification of Controls", parent: "CM-4", parentTitle: "Impact Analyses", baselines: ["Moderate","High"] },
  { id: "CM-5", family: "CM", title: "Access Restrictions for Change", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-5(1)", family: "CM", title: "Automated Access Enforcement and Audit Records", parent: "CM-5", parentTitle: "Access Restrictions for Change", baselines: ["High"] },
  { id: "CM-6", family: "CM", title: "Configuration Settings", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-6(1)", family: "CM", title: "Automated Management, Application, and Verification", parent: "CM-6", parentTitle: "Configuration Settings", baselines: ["High"] },
  { id: "CM-6(2)", family: "CM", title: "Respond to Unauthorized Changes", parent: "CM-6", parentTitle: "Configuration Settings", baselines: ["High"] },
  { id: "CM-7", family: "CM", title: "Least Functionality", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-7(1)", family: "CM", title: "Periodic Review", parent: "CM-7", parentTitle: "Least Functionality", baselines: ["Moderate","High"] },
  { id: "CM-7(2)", family: "CM", title: "Prevent Program Execution", parent: "CM-7", parentTitle: "Least Functionality", baselines: ["Moderate","High"] },
  { id: "CM-7(5)", family: "CM", title: "Authorized Software — Allow-by-exception", parent: "CM-7", parentTitle: "Least Functionality", baselines: ["Moderate","High"] },
  { id: "CM-8", family: "CM", title: "System Component Inventory", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-8(1)", family: "CM", title: "Updates During Installation and Removal", parent: "CM-8", parentTitle: "System Component Inventory", baselines: ["Moderate","High"] },
  { id: "CM-8(2)", family: "CM", title: "Automated Maintenance", parent: "CM-8", parentTitle: "System Component Inventory", baselines: ["High"] },
  { id: "CM-8(3)", family: "CM", title: "Automated Unauthorized Component Detection", parent: "CM-8", parentTitle: "System Component Inventory", baselines: ["Moderate","High"] },
  { id: "CM-8(4)", family: "CM", title: "Accountability Information", parent: "CM-8", parentTitle: "System Component Inventory", baselines: ["High"] },
  { id: "CM-9", family: "CM", title: "Configuration Management Plan", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "CM-10", family: "CM", title: "Software Usage Restrictions", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-11", family: "CM", title: "User-installed Software", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CM-12", family: "CM", title: "Information Location", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "CM-12(1)", family: "CM", title: "Automated Tools to Support Information Location", parent: "CM-12", parentTitle: "Information Location", baselines: ["Moderate","High"] },
  { id: "CP-1", family: "CP", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CP-2", family: "CP", title: "Contingency Plan", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CP-2(1)", family: "CP", title: "Coordinate with Related Plans", parent: "CP-2", parentTitle: "Contingency Plan", baselines: ["Moderate","High"] },
  { id: "CP-2(2)", family: "CP", title: "Capacity Planning", parent: "CP-2", parentTitle: "Contingency Plan", baselines: ["High"] },
  { id: "CP-2(3)", family: "CP", title: "Resume Mission and Business Functions", parent: "CP-2", parentTitle: "Contingency Plan", baselines: ["Moderate","High"] },
  { id: "CP-2(5)", family: "CP", title: "Continue Mission and Business Functions", parent: "CP-2", parentTitle: "Contingency Plan", baselines: ["High"] },
  { id: "CP-2(8)", family: "CP", title: "Identify Critical Assets", parent: "CP-2", parentTitle: "Contingency Plan", baselines: ["Moderate","High"] },
  { id: "CP-3", family: "CP", title: "Contingency Training", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CP-3(1)", family: "CP", title: "Simulated Events", parent: "CP-3", parentTitle: "Contingency Training", baselines: ["High"] },
  { id: "CP-4", family: "CP", title: "Contingency Plan Testing", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CP-4(1)", family: "CP", title: "Coordinate with Related Plans", parent: "CP-4", parentTitle: "Contingency Plan Testing", baselines: ["Moderate","High"] },
  { id: "CP-4(2)", family: "CP", title: "Alternate Processing Site", parent: "CP-4", parentTitle: "Contingency Plan Testing", baselines: ["High"] },
  { id: "CP-6", family: "CP", title: "Alternate Storage Site", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "CP-6(1)", family: "CP", title: "Separation from Primary Site", parent: "CP-6", parentTitle: "Alternate Storage Site", baselines: ["Moderate","High"] },
  { id: "CP-6(2)", family: "CP", title: "Recovery Time and Recovery Point Objectives", parent: "CP-6", parentTitle: "Alternate Storage Site", baselines: ["High"] },
  { id: "CP-6(3)", family: "CP", title: "Accessibility", parent: "CP-6", parentTitle: "Alternate Storage Site", baselines: ["Moderate","High"] },
  { id: "CP-7", family: "CP", title: "Alternate Processing Site", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "CP-7(1)", family: "CP", title: "Separation from Primary Site", parent: "CP-7", parentTitle: "Alternate Processing Site", baselines: ["Moderate","High"] },
  { id: "CP-7(2)", family: "CP", title: "Accessibility", parent: "CP-7", parentTitle: "Alternate Processing Site", baselines: ["Moderate","High"] },
  { id: "CP-7(3)", family: "CP", title: "Priority of Service", parent: "CP-7", parentTitle: "Alternate Processing Site", baselines: ["Moderate","High"] },
  { id: "CP-7(4)", family: "CP", title: "Preparation for Use", parent: "CP-7", parentTitle: "Alternate Processing Site", baselines: ["High"] },
  { id: "CP-8", family: "CP", title: "Telecommunications Services", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "CP-8(1)", family: "CP", title: "Priority of Service Provisions", parent: "CP-8", parentTitle: "Telecommunications Services", baselines: ["Moderate","High"] },
  { id: "CP-8(2)", family: "CP", title: "Single Points of Failure", parent: "CP-8", parentTitle: "Telecommunications Services", baselines: ["Moderate","High"] },
  { id: "CP-8(3)", family: "CP", title: "Separation of Primary and Alternate Providers", parent: "CP-8", parentTitle: "Telecommunications Services", baselines: ["High"] },
  { id: "CP-8(4)", family: "CP", title: "Provider Contingency Plan", parent: "CP-8", parentTitle: "Telecommunications Services", baselines: ["High"] },
  { id: "CP-9", family: "CP", title: "System Backup", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CP-9(1)", family: "CP", title: "Testing for Reliability and Integrity", parent: "CP-9", parentTitle: "System Backup", baselines: ["Moderate","High"] },
  { id: "CP-9(2)", family: "CP", title: "Test Restoration Using Sampling", parent: "CP-9", parentTitle: "System Backup", baselines: ["High"] },
  { id: "CP-9(3)", family: "CP", title: "Separate Storage for Critical Information", parent: "CP-9", parentTitle: "System Backup", baselines: ["High"] },
  { id: "CP-9(5)", family: "CP", title: "Transfer to Alternate Storage Site", parent: "CP-9", parentTitle: "System Backup", baselines: ["High"] },
  { id: "CP-9(8)", family: "CP", title: "Cryptographic Protection", parent: "CP-9", parentTitle: "System Backup", baselines: ["Moderate","High"] },
  { id: "CP-10", family: "CP", title: "System Recovery and Reconstitution", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "CP-10(2)", family: "CP", title: "Transaction Recovery", parent: "CP-10", parentTitle: "System Recovery and Reconstitution", baselines: ["Moderate","High"] },
  { id: "CP-10(4)", family: "CP", title: "Restore Within Time Period", parent: "CP-10", parentTitle: "System Recovery and Reconstitution", baselines: ["High"] },
  { id: "IA-1", family: "IA", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IA-2", family: "IA", title: "Identification and Authentication (Organizational Users)", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IA-2(1)", family: "IA", title: "Multi-factor Authentication to Privileged Accounts", parent: "IA-2", parentTitle: "Identification and Authentication (Organizational Users)", baselines: ["Low","Moderate","High"] },
  { id: "IA-2(2)", family: "IA", title: "Multi-factor Authentication to Non-privileged Accounts", parent: "IA-2", parentTitle: "Identification and Authentication (Organizational Users)", baselines: ["Low","Moderate","High"] },
  { id: "IA-2(5)", family: "IA", title: "Individual Authentication with Group Authentication", parent: "IA-2", parentTitle: "Identification and Authentication (Organizational Users)", baselines: ["High"] },
  { id: "IA-2(8)", family: "IA", title: "Access to Accounts — Replay Resistant", parent: "IA-2", parentTitle: "Identification and Authentication (Organizational Users)", baselines: ["Low","Moderate","High"] },
  { id: "IA-2(12)", family: "IA", title: "Acceptance of PIV Credentials", parent: "IA-2", parentTitle: "Identification and Authentication (Organizational Users)", baselines: ["Low","Moderate","High"] },
  { id: "IA-3", family: "IA", title: "Device Identification and Authentication", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "IA-4", family: "IA", title: "Identifier Management", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IA-4(4)", family: "IA", title: "Identify User Status", parent: "IA-4", parentTitle: "Identifier Management", baselines: ["Moderate","High"] },
  { id: "IA-5", family: "IA", title: "Authenticator Management", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IA-5(1)", family: "IA", title: "Password-based Authentication", parent: "IA-5", parentTitle: "Authenticator Management", baselines: ["Low","Moderate","High"] },
  { id: "IA-5(2)", family: "IA", title: "Public Key-based Authentication", parent: "IA-5", parentTitle: "Authenticator Management", baselines: ["Moderate","High"] },
  { id: "IA-5(6)", family: "IA", title: "Protection of Authenticators", parent: "IA-5", parentTitle: "Authenticator Management", baselines: ["Moderate","High"] },
  { id: "IA-6", family: "IA", title: "Authentication Feedback", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IA-7", family: "IA", title: "Cryptographic Module Authentication", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IA-8", family: "IA", title: "Identification and Authentication (Non-organizational Users)", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IA-8(1)", family: "IA", title: "Acceptance of PIV Credentials from Other Agencies", parent: "IA-8", parentTitle: "Identification and Authentication (Non-organizational Users)", baselines: ["Low","Moderate","High"] },
  { id: "IA-8(2)", family: "IA", title: "Acceptance of External Authenticators", parent: "IA-8", parentTitle: "Identification and Authentication (Non-organizational Users)", baselines: ["Low","Moderate","High"] },
  { id: "IA-8(4)", family: "IA", title: "Use of Defined Profiles", parent: "IA-8", parentTitle: "Identification and Authentication (Non-organizational Users)", baselines: ["Low","Moderate","High"] },
  { id: "IA-11", family: "IA", title: "Re-authentication", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IA-12", family: "IA", title: "Identity Proofing", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "IA-12(2)", family: "IA", title: "Identity Evidence", parent: "IA-12", parentTitle: "Identity Proofing", baselines: ["Moderate","High"] },
  { id: "IA-12(3)", family: "IA", title: "Identity Evidence Validation and Verification", parent: "IA-12", parentTitle: "Identity Proofing", baselines: ["Moderate","High"] },
  { id: "IA-12(4)", family: "IA", title: "In-person Validation and Verification", parent: "IA-12", parentTitle: "Identity Proofing", baselines: ["High"] },
  { id: "IA-12(5)", family: "IA", title: "Address Confirmation", parent: "IA-12", parentTitle: "Identity Proofing", baselines: ["Moderate","High"] },
  { id: "IR-1", family: "IR", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IR-2", family: "IR", title: "Incident Response Training", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IR-2(1)", family: "IR", title: "Simulated Events", parent: "IR-2", parentTitle: "Incident Response Training", baselines: ["High"] },
  { id: "IR-2(2)", family: "IR", title: "Automated Training Environments", parent: "IR-2", parentTitle: "Incident Response Training", baselines: ["High"] },
  { id: "IR-3", family: "IR", title: "Incident Response Testing", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "IR-3(2)", family: "IR", title: "Coordination with Related Plans", parent: "IR-3", parentTitle: "Incident Response Testing", baselines: ["Moderate","High"] },
  { id: "IR-4", family: "IR", title: "Incident Handling", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IR-4(1)", family: "IR", title: "Automated Incident Handling Processes", parent: "IR-4", parentTitle: "Incident Handling", baselines: ["Moderate","High"] },
  { id: "IR-4(4)", family: "IR", title: "Information Correlation", parent: "IR-4", parentTitle: "Incident Handling", baselines: ["High"] },
  { id: "IR-4(11)", family: "IR", title: "Integrated Incident Response Team", parent: "IR-4", parentTitle: "Incident Handling", baselines: ["High"] },
  { id: "IR-5", family: "IR", title: "Incident Monitoring", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IR-5(1)", family: "IR", title: "Automated Tracking, Data Collection, and Analysis", parent: "IR-5", parentTitle: "Incident Monitoring", baselines: ["High"] },
  { id: "IR-6", family: "IR", title: "Incident Reporting", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IR-6(1)", family: "IR", title: "Automated Reporting", parent: "IR-6", parentTitle: "Incident Reporting", baselines: ["Moderate","High"] },
  { id: "IR-6(3)", family: "IR", title: "Supply Chain Coordination", parent: "IR-6", parentTitle: "Incident Reporting", baselines: ["Moderate","High"] },
  { id: "IR-7", family: "IR", title: "Incident Response Assistance", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "IR-7(1)", family: "IR", title: "Automation Support for Availability of Information and Support", parent: "IR-7", parentTitle: "Incident Response Assistance", baselines: ["Moderate","High"] },
  { id: "IR-8", family: "IR", title: "Incident Response Plan", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "MA-1", family: "MA", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "MA-2", family: "MA", title: "Controlled Maintenance", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "MA-2(2)", family: "MA", title: "Automated Maintenance Activities", parent: "MA-2", parentTitle: "Controlled Maintenance", baselines: ["High"] },
  { id: "MA-3", family: "MA", title: "Maintenance Tools", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "MA-3(1)", family: "MA", title: "Inspect Tools", parent: "MA-3", parentTitle: "Maintenance Tools", baselines: ["Moderate","High"] },
  { id: "MA-3(2)", family: "MA", title: "Inspect Media", parent: "MA-3", parentTitle: "Maintenance Tools", baselines: ["Moderate","High"] },
  { id: "MA-3(3)", family: "MA", title: "Prevent Unauthorized Removal", parent: "MA-3", parentTitle: "Maintenance Tools", baselines: ["Moderate","High"] },
  { id: "MA-4", family: "MA", title: "Nonlocal Maintenance", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "MA-4(3)", family: "MA", title: "Comparable Security and Sanitization", parent: "MA-4", parentTitle: "Nonlocal Maintenance", baselines: ["High"] },
  { id: "MA-5", family: "MA", title: "Maintenance Personnel", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "MA-5(1)", family: "MA", title: "Individuals Without Appropriate Access", parent: "MA-5", parentTitle: "Maintenance Personnel", baselines: ["High"] },
  { id: "MA-6", family: "MA", title: "Timely Maintenance", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "MP-1", family: "MP", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "MP-2", family: "MP", title: "Media Access", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "MP-3", family: "MP", title: "Media Marking", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "MP-4", family: "MP", title: "Media Storage", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "MP-5", family: "MP", title: "Media Transport", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "MP-6", family: "MP", title: "Media Sanitization", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "MP-6(1)", family: "MP", title: "Review, Approve, Track, Document, and Verify", parent: "MP-6", parentTitle: "Media Sanitization", baselines: ["High"] },
  { id: "MP-6(2)", family: "MP", title: "Equipment Testing", parent: "MP-6", parentTitle: "Media Sanitization", baselines: ["High"] },
  { id: "MP-6(3)", family: "MP", title: "Nondestructive Techniques", parent: "MP-6", parentTitle: "Media Sanitization", baselines: ["High"] },
  { id: "MP-7", family: "MP", title: "Media Use", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-1", family: "PE", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-2", family: "PE", title: "Physical Access Authorizations", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-3", family: "PE", title: "Physical Access Control", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-3(1)", family: "PE", title: "System Access", parent: "PE-3", parentTitle: "Physical Access Control", baselines: ["High"] },
  { id: "PE-4", family: "PE", title: "Access Control for Transmission", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "PE-5", family: "PE", title: "Access Control for Output Devices", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "PE-6", family: "PE", title: "Monitoring Physical Access", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-6(1)", family: "PE", title: "Intrusion Alarms and Surveillance Equipment", parent: "PE-6", parentTitle: "Monitoring Physical Access", baselines: ["Moderate","High"] },
  { id: "PE-6(4)", family: "PE", title: "Monitoring Physical Access to Systems", parent: "PE-6", parentTitle: "Monitoring Physical Access", baselines: ["High"] },
  { id: "PE-8", family: "PE", title: "Visitor Access Records", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-8(1)", family: "PE", title: "Automated Records Maintenance and Review", parent: "PE-8", parentTitle: "Visitor Access Records", baselines: ["High"] },
  { id: "PE-9", family: "PE", title: "Power Equipment and Cabling", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "PE-10", family: "PE", title: "Emergency Shutoff", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "PE-11", family: "PE", title: "Emergency Power", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "PE-11(1)", family: "PE", title: "Alternate Power Supply — Minimal Operational Capability", parent: "PE-11", parentTitle: "Emergency Power", baselines: ["High"] },
  { id: "PE-12", family: "PE", title: "Emergency Lighting", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-13", family: "PE", title: "Fire Protection", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-13(1)", family: "PE", title: "Detection Systems — Automatic Activation and Notification", parent: "PE-13", parentTitle: "Fire Protection", baselines: ["Moderate","High"] },
  { id: "PE-13(2)", family: "PE", title: "Suppression Systems — Automatic Activation and Notification", parent: "PE-13", parentTitle: "Fire Protection", baselines: ["High"] },
  { id: "PE-14", family: "PE", title: "Environmental Controls", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-15", family: "PE", title: "Water Damage Protection", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-15(1)", family: "PE", title: "Automation Support", parent: "PE-15", parentTitle: "Water Damage Protection", baselines: ["High"] },
  { id: "PE-16", family: "PE", title: "Delivery and Removal", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PE-17", family: "PE", title: "Alternate Work Site", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "PE-18", family: "PE", title: "Location of System Components", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "PE-19", family: "PE", title: "Information Leakage", parent: null, parentTitle: null, baselines: [] },
  { id: "PL-1", family: "PL", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PL-2", family: "PL", title: "System Security and Privacy Plans", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PL-4", family: "PL", title: "Rules of Behavior", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PL-4(1)", family: "PL", title: "Social Media and External Site/Application Usage Restrictions", parent: "PL-4", parentTitle: "Rules of Behavior", baselines: ["Low","Moderate","High"] },
  { id: "PL-8", family: "PL", title: "Security and Privacy Architectures", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "PL-10", family: "PL", title: "Baseline Selection", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PL-11", family: "PL", title: "Baseline Tailoring", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PM-2", family: "PM", title: "Information Security Program Leadership Role", parent: null, parentTitle: null, baselines: [] },
  { id: "PS-1", family: "PS", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PS-2", family: "PS", title: "Position Risk Designation", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PS-3", family: "PS", title: "Personnel Screening", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PS-4", family: "PS", title: "Personnel Termination", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PS-4(2)", family: "PS", title: "Automated Actions", parent: "PS-4", parentTitle: "Personnel Termination", baselines: ["High"] },
  { id: "PS-5", family: "PS", title: "Personnel Transfer", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PS-6", family: "PS", title: "Access Agreements", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PS-7", family: "PS", title: "External Personnel Security", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PS-8", family: "PS", title: "Personnel Sanctions", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PS-9", family: "PS", title: "Position Descriptions", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "PT-3", family: "PT", title: "Personally Identifiable Information Processing Purposes", parent: null, parentTitle: null, baselines: [] },
  { id: "PT-5", family: "PT", title: "Privacy Notice", parent: null, parentTitle: null, baselines: [] },
  { id: "RA-1", family: "RA", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "RA-2", family: "RA", title: "Security Categorization", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "RA-3", family: "RA", title: "Risk Assessment", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "RA-3(1)", family: "RA", title: "Supply Chain Risk Assessment", parent: "RA-3", parentTitle: "Risk Assessment", baselines: ["Low","Moderate","High"] },
  { id: "RA-5", family: "RA", title: "Vulnerability Monitoring and Scanning", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "RA-5(2)", family: "RA", title: "Update Vulnerabilities to Be Scanned", parent: "RA-5", parentTitle: "Vulnerability Monitoring and Scanning", baselines: ["Low","Moderate","High"] },
  { id: "RA-5(4)", family: "RA", title: "Discoverable Information", parent: "RA-5", parentTitle: "Vulnerability Monitoring and Scanning", baselines: ["High"] },
  { id: "RA-5(5)", family: "RA", title: "Privileged Access", parent: "RA-5", parentTitle: "Vulnerability Monitoring and Scanning", baselines: ["Moderate","High"] },
  { id: "RA-5(11)", family: "RA", title: "Public Disclosure Program", parent: "RA-5", parentTitle: "Vulnerability Monitoring and Scanning", baselines: ["Low","Moderate","High"] },
  { id: "RA-7", family: "RA", title: "Risk Response", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "RA-9", family: "RA", title: "Criticality Analysis", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SA-1", family: "SA", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SA-2", family: "SA", title: "Allocation of Resources", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SA-3", family: "SA", title: "System Development Life Cycle", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SA-4", family: "SA", title: "Acquisition Process", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SA-4(1)", family: "SA", title: "Functional Properties of Controls", parent: "SA-4", parentTitle: "Acquisition Process", baselines: ["Moderate","High"] },
  { id: "SA-4(2)", family: "SA", title: "Design and Implementation Information for Controls", parent: "SA-4", parentTitle: "Acquisition Process", baselines: ["Moderate","High"] },
  { id: "SA-4(5)", family: "SA", title: "System, Component, and Service Configurations", parent: "SA-4", parentTitle: "Acquisition Process", baselines: ["High"] },
  { id: "SA-4(9)", family: "SA", title: "Functions, Ports, Protocols, and Services in Use", parent: "SA-4", parentTitle: "Acquisition Process", baselines: ["Moderate","High"] },
  { id: "SA-4(10)", family: "SA", title: "Use of Approved PIV Products", parent: "SA-4", parentTitle: "Acquisition Process", baselines: ["Low","Moderate","High"] },
  { id: "SA-5", family: "SA", title: "System Documentation", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SA-8", family: "SA", title: "Security and Privacy Engineering Principles", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SA-9", family: "SA", title: "External System Services", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SA-9(2)", family: "SA", title: "Identification of Functions, Ports, Protocols, and Services", parent: "SA-9", parentTitle: "External System Services", baselines: ["Moderate","High"] },
  { id: "SA-10", family: "SA", title: "Developer Configuration Management", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SA-11", family: "SA", title: "Developer Testing and Evaluation", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SA-15", family: "SA", title: "Development Process, Standards, and Tools", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SA-15(3)", family: "SA", title: "Criticality Analysis", parent: "SA-15", parentTitle: "Development Process, Standards, and Tools", baselines: ["Moderate","High"] },
  { id: "SA-16", family: "SA", title: "Developer-provided Training", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "SA-17", family: "SA", title: "Developer Security and Privacy Architecture and Design", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "SA-21", family: "SA", title: "Developer Screening", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "SA-22", family: "SA", title: "Unsupported System Components", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-1", family: "SC", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-2", family: "SC", title: "Separation of System and User Functionality", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SC-3", family: "SC", title: "Security Function Isolation", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "SC-4", family: "SC", title: "Information in Shared System Resources", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SC-5", family: "SC", title: "Denial-of-service Protection", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-7", family: "SC", title: "Boundary Protection", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-7(3)", family: "SC", title: "Access Points", parent: "SC-7", parentTitle: "Boundary Protection", baselines: ["Moderate","High"] },
  { id: "SC-7(4)", family: "SC", title: "External Telecommunications Services", parent: "SC-7", parentTitle: "Boundary Protection", baselines: ["Moderate","High"] },
  { id: "SC-7(5)", family: "SC", title: "Deny by Default — Allow by Exception", parent: "SC-7", parentTitle: "Boundary Protection", baselines: ["Moderate","High"] },
  { id: "SC-7(7)", family: "SC", title: "Split Tunneling for Remote Devices", parent: "SC-7", parentTitle: "Boundary Protection", baselines: ["Moderate","High"] },
  { id: "SC-7(8)", family: "SC", title: "Route Traffic to Authenticated Proxy Servers", parent: "SC-7", parentTitle: "Boundary Protection", baselines: ["Moderate","High"] },
  { id: "SC-7(18)", family: "SC", title: "Fail Secure", parent: "SC-7", parentTitle: "Boundary Protection", baselines: ["High"] },
  { id: "SC-7(21)", family: "SC", title: "Isolation of System Components", parent: "SC-7", parentTitle: "Boundary Protection", baselines: ["High"] },
  { id: "SC-8", family: "SC", title: "Transmission Confidentiality and Integrity", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SC-8(1)", family: "SC", title: "Cryptographic Protection", parent: "SC-8", parentTitle: "Transmission Confidentiality and Integrity", baselines: ["Moderate","High"] },
  { id: "SC-10", family: "SC", title: "Network Disconnect", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SC-12", family: "SC", title: "Cryptographic Key Establishment and Management", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-12(1)", family: "SC", title: "Availability", parent: "SC-12", parentTitle: "Cryptographic Key Establishment and Management", baselines: ["High"] },
  { id: "SC-13", family: "SC", title: "Cryptographic Protection", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-15", family: "SC", title: "Collaborative Computing Devices and Applications", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-17", family: "SC", title: "Public Key Infrastructure Certificates", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SC-18", family: "SC", title: "Mobile Code", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SC-20", family: "SC", title: "Secure Name/Address Resolution Service (Authoritative Source)", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-21", family: "SC", title: "Secure Name/Address Resolution Service (Recursive or Caching Resolver)", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-22", family: "SC", title: "Architecture and Provisioning for Name/Address Resolution Service", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-23", family: "SC", title: "Session Authenticity", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SC-24", family: "SC", title: "Fail in Known State", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "SC-28", family: "SC", title: "Protection of Information at Rest", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SC-28(1)", family: "SC", title: "Cryptographic Protection", parent: "SC-28", parentTitle: "Protection of Information at Rest", baselines: ["Moderate","High"] },
  { id: "SC-39", family: "SC", title: "Process Isolation", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SC-40", family: "SC", title: "Wireless Link Protection", parent: null, parentTitle: null, baselines: [] },
  { id: "SI-1", family: "SI", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SI-2", family: "SI", title: "Flaw Remediation", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SI-2(2)", family: "SI", title: "Automated Flaw Remediation Status", parent: "SI-2", parentTitle: "Flaw Remediation", baselines: ["Moderate","High"] },
  { id: "SI-3", family: "SI", title: "Malicious Code Protection", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SI-4", family: "SI", title: "System Monitoring", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SI-4(2)", family: "SI", title: "Automated Tools and Mechanisms for Real-time Analysis", parent: "SI-4", parentTitle: "System Monitoring", baselines: ["Moderate","High"] },
  { id: "SI-4(4)", family: "SI", title: "Inbound and Outbound Communications Traffic", parent: "SI-4", parentTitle: "System Monitoring", baselines: ["Moderate","High"] },
  { id: "SI-4(5)", family: "SI", title: "System-generated Alerts", parent: "SI-4", parentTitle: "System Monitoring", baselines: ["Moderate","High"] },
  { id: "SI-4(10)", family: "SI", title: "Visibility of Encrypted Communications", parent: "SI-4", parentTitle: "System Monitoring", baselines: ["High"] },
  { id: "SI-4(12)", family: "SI", title: "Automated Organization-generated Alerts", parent: "SI-4", parentTitle: "System Monitoring", baselines: ["High"] },
  { id: "SI-4(14)", family: "SI", title: "Wireless Intrusion Detection", parent: "SI-4", parentTitle: "System Monitoring", baselines: ["High"] },
  { id: "SI-4(20)", family: "SI", title: "Privileged Users", parent: "SI-4", parentTitle: "System Monitoring", baselines: ["High"] },
  { id: "SI-4(22)", family: "SI", title: "Unauthorized Network Services", parent: "SI-4", parentTitle: "System Monitoring", baselines: ["High"] },
  { id: "SI-5", family: "SI", title: "Security Alerts, Advisories, and Directives", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SI-5(1)", family: "SI", title: "Automated Alerts and Advisories", parent: "SI-5", parentTitle: "Security Alerts, Advisories, and Directives", baselines: ["High"] },
  { id: "SI-6", family: "SI", title: "Security and Privacy Function Verification", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "SI-7", family: "SI", title: "Software, Firmware, and Information Integrity", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SI-7(1)", family: "SI", title: "Integrity Checks", parent: "SI-7", parentTitle: "Software, Firmware, and Information Integrity", baselines: ["Moderate","High"] },
  { id: "SI-7(2)", family: "SI", title: "Automated Notifications of Integrity Violations", parent: "SI-7", parentTitle: "Software, Firmware, and Information Integrity", baselines: ["High"] },
  { id: "SI-7(5)", family: "SI", title: "Automated Response to Integrity Violations", parent: "SI-7", parentTitle: "Software, Firmware, and Information Integrity", baselines: ["High"] },
  { id: "SI-7(7)", family: "SI", title: "Integration of Detection and Response", parent: "SI-7", parentTitle: "Software, Firmware, and Information Integrity", baselines: ["Moderate","High"] },
  { id: "SI-7(15)", family: "SI", title: "Code Authentication", parent: "SI-7", parentTitle: "Software, Firmware, and Information Integrity", baselines: ["High"] },
  { id: "SI-8", family: "SI", title: "Spam Protection", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SI-8(2)", family: "SI", title: "Automatic Updates", parent: "SI-8", parentTitle: "Spam Protection", baselines: ["Moderate","High"] },
  { id: "SI-10", family: "SI", title: "Information Input Validation", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SI-11", family: "SI", title: "Error Handling", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SI-12", family: "SI", title: "Information Management and Retention", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SI-16", family: "SI", title: "Memory Protection", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SI-18", family: "SI", title: "Personally Identifiable Information Quality Operations", parent: null, parentTitle: null, baselines: [] },
  { id: "SR-1", family: "SR", title: "Policy and Procedures", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SR-2", family: "SR", title: "Supply Chain Risk Management Plan", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SR-2(1)", family: "SR", title: "Establish SCRM Team", parent: "SR-2", parentTitle: "Supply Chain Risk Management Plan", baselines: ["Low","Moderate","High"] },
  { id: "SR-3", family: "SR", title: "Supply Chain Controls and Processes", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SR-4", family: "SR", title: "Provenance", parent: null, parentTitle: null, baselines: [] },
  { id: "SR-5", family: "SR", title: "Acquisition Strategies, Tools, and Methods", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SR-6", family: "SR", title: "Supplier Assessments and Reviews", parent: null, parentTitle: null, baselines: ["Moderate","High"] },
  { id: "SR-8", family: "SR", title: "Notification Agreements", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SR-9", family: "SR", title: "Tamper Resistance and Detection", parent: null, parentTitle: null, baselines: ["High"] },
  { id: "SR-9(1)", family: "SR", title: "Multiple Stages of System Development Life Cycle", parent: "SR-9", parentTitle: "Tamper Resistance and Detection", baselines: ["High"] },
  { id: "SR-10", family: "SR", title: "Inspection of Systems or Components", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SR-11", family: "SR", title: "Component Authenticity", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
  { id: "SR-11(1)", family: "SR", title: "Anti-counterfeit Training", parent: "SR-11", parentTitle: "Component Authenticity", baselines: ["Low","Moderate","High"] },
  { id: "SR-11(2)", family: "SR", title: "Configuration Control for Component Service and Repair", parent: "SR-11", parentTitle: "Component Authenticity", baselines: ["Low","Moderate","High"] },
  { id: "SR-12", family: "SR", title: "Component Disposal", parent: null, parentTitle: null, baselines: ["Low","Moderate","High"] },
];

export const nistControlById = new Map(nistControls.map((c) => [c.id, c]));

const baselineCache = new Map<NistBaseline, NistControl[]>();

/** The SP 800-53B baseline for an impact level, in catalog order. */
export function baselineControls(level: NistBaseline): NistControl[] {
  const hit = baselineCache.get(level);
  if (hit) return hit;
  const rows = nistControls.filter((c) => c.baselines.includes(level));
  baselineCache.set(level, rows);
  return rows;
}

/** "Account Management | Disable Accounts" — how a control reads in an RMF tool. */
export function controlTitle(c: NistControl): string {
  return c.parentTitle ? `${c.parentTitle} | ${c.title}` : c.title;
}

/** Title for a bare id, falling back to the id itself. */
export function titleOf(id: string): string {
  const c = nistControlById.get(id);
  return c ? controlTitle(c) : id;
}
