/**
 * The real NIST SP 800-53 Rev. 5 control catalog — index.
 *
 * Every control and enhancement in the catalog (1196 rows, 20 families), with no
 * prose: this module is imported statically all over the app, so the statements,
 * discussion and SP 800-53A objectives live in the per-family chunks under
 * `./nist-control-text/` and are fetched on demand.
 *
 * Generated from the NIST OSCAL release of SP 800-53 Rev. 5 (catalog version
 * 5.2.0, 2026-05-11, OSCAL 1.2.2) and the SP 800-53B Low /
 * Moderate / High / Privacy baseline profiles.
 * NIST publications are US Government works in the public domain.
 *
 * Do not hand-edit — regenerate with: node scripts/gen-nist-catalog.mjs
 */

import type { ReferenceProvenance } from "./reference-provenance";

export type NistBaseline = "Low" | "Moderate" | "High" | "Privacy";

export type NistControl = {
  /** Natural key as a human writes it: "AC-2", "AC-2(3)". */
  id: string;
  family: string;
  /** Rev. 5 title, verbatim. Enhancements carry only their own half. */
  title: string;
  /** Base control an enhancement extends, or null. */
  parent: string | null;
  parentTitle: string | null;
  /** SP 800-53B baselines that select this control. Empty = tailored in by an overlay. */
  baselines: NistBaseline[];
  /** Withdrawn in Rev. 5. Absent on the 1014 active controls. */
  withdrawn?: true;
  /**
   * For a withdrawn control, the controls its requirement was folded into.
   * Two upstream shapes are coarsened here: a statement-level target
   * ("#ac-2_smt.k" on AC-2(10)) becomes its control, and a family-level target
   * ("#sr" on SA-12) becomes the two-letter family id "SR".
   */
  incorporatedInto?: string[];
  /** For a withdrawn control, the control it was renumbered to. */
  movedTo?: string[];
};

export type NistStatementItem = { label?: string; prose: string; items?: NistStatementItem[] };
export type NistParameter = { id: string; kind: "Assignment" | "Selection"; value: string; guideline?: string };
/**
 * One SP 800-53A Rev. 5 assessment objective. `id` is the OSCAL part id
 * ("ac-2_obj.a-1"), which is what an assessment result cites.
 */
export type NistObjective = { id: string; label: string; prose: string; items?: NistObjective[] };
export type NistMethod = { method: "Examine" | "Interview" | "Test"; objects: string[] };
export type NistReference = { title: string; url?: string };

/** Everything SP 800-53 and 800-53A say about one control. */
export type NistControlText = {
  statement: NistStatementItem[];
  discussion: string[];
  params: NistParameter[];
  related: string[];
  objectives: NistObjective[];
  methods: NistMethod[];
  references: NistReference[];
};

export const catalogVersion = "NIST SP 800-53 Rev. 5 (5.2.0)";

/**
 * Where this module's content comes from, machine-readable.
 *
 * One OSCAL file carries both publications: the statement, discussion and
 * parameters on `NistControlText` are SP 800-53 Rev. 5, and its objectives and
 * assessment methods are SP 800-53A Rev. 5. Both are NIST's own release, so both
 * are authoritative; they are separate records because a screen that cites an
 * assessment objective must cite 800-53A, not 800-53.
 */
export const nistCatalogProvenance: ReferenceProvenance = {
  id: "NIST-800-53-R5",
  source: "NIST SP 800-53 Rev. 5 (OSCAL) 5.2.0",
  authority: "National Institute of Standards and Technology",
  citation: "NIST SP 800-53 Rev. 5, Security and Privacy Controls for Information Systems and Organizations",
  release: "5.2.0",
  sourceUrl:
    "https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json",
  authoritative: true,
  rights: "NIST publications are US Government works in the public domain.",
  sha256: "01f37cf90ea99d92242c936cbfbdebcc338eef1f71454e2acac36cc56e9bc062",
  lastModified: "2026-05-11",
  notes: [
    "OSCAL 1.2.2. The same file carries the SP 800-53A Rev. 5 assessment procedures.",
    "Control ids are stored in the human/DISA convention — AC-2(1) — never zero padded; see src/lib/control-id.ts.",
  ],
};

/** The SP 800-53A Rev. 5 half of the same OSCAL release: objectives and methods. */
export const nistAssessmentProvenance: ReferenceProvenance = {
  ...nistCatalogProvenance,
  id: "NIST-800-53A-R5",
  source: "NIST SP 800-53A Rev. 5 assessment procedures (OSCAL) 5.2.0",
  citation: "NIST SP 800-53A Rev. 5, Assessing Security and Privacy Controls in Information Systems and Organizations",
  notes: [
    "Published inside the SP 800-53 Rev. 5 OSCAL catalog as assessment-objective, assessment-method and assessment-objects parts.",
    "NistObjective.id is the OSCAL part id, which is what an assessment result cites.",
  ],
};

/**
 * Per-record provenance without 1196 copies of one object: every row in
 * this module comes from the OSCAL release above. Null for an id the catalog
 * does not have, so a caller cannot accidentally attribute a foreign id to NIST.
 */
export function controlProvenance(id: string): ReferenceProvenance | null {
  return nistControlById.has(id) ? nistCatalogProvenance : null;
}

/** Provenance for a control's SP 800-53A objectives and methods. */
export function objectiveProvenance(id: string): ReferenceProvenance | null {
  return nistControlById.has(id) ? nistAssessmentProvenance : null;
}

export const nistFamilies: { id: string; name: string }[] = [{"id":"AC","name":"Access Control"},{"id":"AT","name":"Awareness and Training"},{"id":"AU","name":"Audit and Accountability"},{"id":"CA","name":"Assessment, Authorization, and Monitoring"},{"id":"CM","name":"Configuration Management"},{"id":"CP","name":"Contingency Planning"},{"id":"IA","name":"Identification and Authentication"},{"id":"IR","name":"Incident Response"},{"id":"MA","name":"Maintenance"},{"id":"MP","name":"Media Protection"},{"id":"PE","name":"Physical and Environmental Protection"},{"id":"PL","name":"Planning"},{"id":"PM","name":"Program Management"},{"id":"PS","name":"Personnel Security"},{"id":"PT","name":"Personally Identifiable Information Processing and Transparency"},{"id":"RA","name":"Risk Assessment"},{"id":"SA","name":"System and Services Acquisition"},{"id":"SC","name":"System and Communications Protection"},{"id":"SI","name":"System and Information Integrity"},{"id":"SR","name":"Supply Chain Risk Management"}];

export const nistFamilyName = new Map(nistFamilies.map((f) => [f.id, f.name]));


/**
 * One row per control: [id, title, parent id or null, baseline bitmask].
 * The mask is Low 1 | Moderate 2 | High 4 | Privacy 8 — the array form is
 * rebuilt below so `nistControls` keeps the shape every consumer expects.
 */
type CatalogRow = [id: string, title: string, parent: string | null, baselines: number];

const catalogRows: CatalogRow[] = [
  ["AC-1","Policy and Procedures",null,15],
  ["AC-2","Account Management",null,7],
  ["AC-2(1)","Automated System Account Management","AC-2",6],
  ["AC-2(2)","Automated Temporary and Emergency Account Management","AC-2",6],
  ["AC-2(3)","Disable Accounts","AC-2",6],
  ["AC-2(4)","Automated Audit Actions","AC-2",6],
  ["AC-2(5)","Inactivity Logout","AC-2",6],
  ["AC-2(6)","Dynamic Privilege Management","AC-2",0],
  ["AC-2(7)","Privileged User Accounts","AC-2",0],
  ["AC-2(8)","Dynamic Account Management","AC-2",0],
  ["AC-2(9)","Restrictions on Use of Shared and Group Accounts","AC-2",0],
  ["AC-2(10)","Shared and Group Account Credential Change","AC-2",0],
  ["AC-2(11)","Usage Conditions","AC-2",4],
  ["AC-2(12)","Account Monitoring for Atypical Usage","AC-2",4],
  ["AC-2(13)","Disable Accounts for High-risk Individuals","AC-2",6],
  ["AC-3","Access Enforcement",null,7],
  ["AC-3(1)","Restricted Access to Privileged Functions","AC-3",0],
  ["AC-3(2)","Dual Authorization","AC-3",0],
  ["AC-3(3)","Mandatory Access Control","AC-3",0],
  ["AC-3(4)","Discretionary Access Control","AC-3",0],
  ["AC-3(5)","Security-relevant Information","AC-3",0],
  ["AC-3(6)","Protection of User and System Information","AC-3",0],
  ["AC-3(7)","Role-based Access Control","AC-3",0],
  ["AC-3(8)","Revocation of Access Authorizations","AC-3",0],
  ["AC-3(9)","Controlled Release","AC-3",0],
  ["AC-3(10)","Audited Override of Access Control Mechanisms","AC-3",0],
  ["AC-3(11)","Restrict Access to Specific Information Types","AC-3",0],
  ["AC-3(12)","Assert and Enforce Application Access","AC-3",0],
  ["AC-3(13)","Attribute-based Access Control","AC-3",0],
  ["AC-3(14)","Individual Access","AC-3",8],
  ["AC-3(15)","Discretionary and Mandatory Access Control","AC-3",0],
  ["AC-4","Information Flow Enforcement",null,6],
  ["AC-4(1)","Object Security and Privacy Attributes","AC-4",0],
  ["AC-4(2)","Processing Domains","AC-4",0],
  ["AC-4(3)","Dynamic Information Flow Control","AC-4",0],
  ["AC-4(4)","Flow Control of Encrypted Information","AC-4",4],
  ["AC-4(5)","Embedded Data Types","AC-4",0],
  ["AC-4(6)","Metadata","AC-4",0],
  ["AC-4(7)","One-way Flow Mechanisms","AC-4",0],
  ["AC-4(8)","Security and Privacy Policy Filters","AC-4",0],
  ["AC-4(9)","Human Reviews","AC-4",0],
  ["AC-4(10)","Enable and Disable Security or Privacy Policy Filters","AC-4",0],
  ["AC-4(11)","Configuration of Security or Privacy Policy Filters","AC-4",0],
  ["AC-4(12)","Data Type Identifiers","AC-4",0],
  ["AC-4(13)","Decomposition into Policy-relevant Subcomponents","AC-4",0],
  ["AC-4(14)","Security or Privacy Policy Filter Constraints","AC-4",0],
  ["AC-4(15)","Detection of Unsanctioned Information","AC-4",0],
  ["AC-4(16)","Information Transfers on Interconnected Systems","AC-4",0],
  ["AC-4(17)","Domain Authentication","AC-4",0],
  ["AC-4(18)","Security Attribute Binding","AC-4",0],
  ["AC-4(19)","Validation of Metadata","AC-4",0],
  ["AC-4(20)","Approved Solutions","AC-4",0],
  ["AC-4(21)","Physical or Logical Separation of Information Flows","AC-4",0],
  ["AC-4(22)","Access Only","AC-4",0],
  ["AC-4(23)","Modify Non-releasable Information","AC-4",0],
  ["AC-4(24)","Internal Normalized Format","AC-4",0],
  ["AC-4(25)","Data Sanitization","AC-4",0],
  ["AC-4(26)","Audit Filtering Actions","AC-4",0],
  ["AC-4(27)","Redundant/Independent Filtering Mechanisms","AC-4",0],
  ["AC-4(28)","Linear Filter Pipelines","AC-4",0],
  ["AC-4(29)","Filter Orchestration Engines","AC-4",0],
  ["AC-4(30)","Filter Mechanisms Using Multiple Processes","AC-4",0],
  ["AC-4(31)","Failed Content Transfer Prevention","AC-4",0],
  ["AC-4(32)","Process Requirements for Information Transfer","AC-4",0],
  ["AC-5","Separation of Duties",null,6],
  ["AC-6","Least Privilege",null,6],
  ["AC-6(1)","Authorize Access to Security Functions","AC-6",6],
  ["AC-6(2)","Non-privileged Access for Nonsecurity Functions","AC-6",6],
  ["AC-6(3)","Network Access to Privileged Commands","AC-6",4],
  ["AC-6(4)","Separate Processing Domains","AC-6",0],
  ["AC-6(5)","Privileged Accounts","AC-6",6],
  ["AC-6(6)","Privileged Access by Non-organizational Users","AC-6",0],
  ["AC-6(7)","Review of User Privileges","AC-6",6],
  ["AC-6(8)","Privilege Levels for Code Execution","AC-6",0],
  ["AC-6(9)","Log Use of Privileged Functions","AC-6",6],
  ["AC-6(10)","Prohibit Non-privileged Users from Executing Privileged Functions","AC-6",6],
  ["AC-7","Unsuccessful Logon Attempts",null,7],
  ["AC-7(1)","Automatic Account Lock","AC-7",0],
  ["AC-7(2)","Purge or Wipe Mobile Device","AC-7",0],
  ["AC-7(3)","Biometric Attempt Limiting","AC-7",0],
  ["AC-7(4)","Use of Alternate Authentication Factor","AC-7",0],
  ["AC-8","System Use Notification",null,7],
  ["AC-9","Previous Logon Notification",null,0],
  ["AC-9(1)","Unsuccessful Logons","AC-9",0],
  ["AC-9(2)","Successful and Unsuccessful Logons","AC-9",0],
  ["AC-9(3)","Notification of Account Changes","AC-9",0],
  ["AC-9(4)","Additional Logon Information","AC-9",0],
  ["AC-10","Concurrent Session Control",null,4],
  ["AC-11","Device Lock",null,6],
  ["AC-11(1)","Pattern-hiding Displays","AC-11",6],
  ["AC-12","Session Termination",null,6],
  ["AC-12(1)","User-initiated Logouts","AC-12",0],
  ["AC-12(2)","Termination Message","AC-12",0],
  ["AC-12(3)","Timeout Warning Message","AC-12",0],
  ["AC-13","Supervision and Review — Access Control",null,0],
  ["AC-14","Permitted Actions Without Identification or Authentication",null,7],
  ["AC-14(1)","Necessary Uses","AC-14",0],
  ["AC-15","Automated Marking",null,0],
  ["AC-16","Security and Privacy Attributes",null,0],
  ["AC-16(1)","Dynamic Attribute Association","AC-16",0],
  ["AC-16(2)","Attribute Value Changes by Authorized Individuals","AC-16",0],
  ["AC-16(3)","Maintenance of Attribute Associations by System","AC-16",0],
  ["AC-16(4)","Association of Attributes by Authorized Individuals","AC-16",0],
  ["AC-16(5)","Attribute Displays on Objects to Be Output","AC-16",0],
  ["AC-16(6)","Maintenance of Attribute Association","AC-16",0],
  ["AC-16(7)","Consistent Attribute Interpretation","AC-16",0],
  ["AC-16(8)","Association Techniques and Technologies","AC-16",0],
  ["AC-16(9)","Attribute Reassignment — Regrading Mechanisms","AC-16",0],
  ["AC-16(10)","Attribute Configuration by Authorized Individuals","AC-16",0],
  ["AC-17","Remote Access",null,7],
  ["AC-17(1)","Monitoring and Control","AC-17",6],
  ["AC-17(2)","Protection of Confidentiality and Integrity Using Encryption","AC-17",6],
  ["AC-17(3)","Managed Access Control Points","AC-17",6],
  ["AC-17(4)","Privileged Commands and Access","AC-17",6],
  ["AC-17(5)","Monitoring for Unauthorized Connections","AC-17",0],
  ["AC-17(6)","Protection of Mechanism Information","AC-17",0],
  ["AC-17(7)","Additional Protection for Security Function Access","AC-17",0],
  ["AC-17(8)","Disable Nonsecure Network Protocols","AC-17",0],
  ["AC-17(9)","Disconnect or Disable Access","AC-17",0],
  ["AC-17(10)","Authenticate Remote Commands","AC-17",0],
  ["AC-18","Wireless Access",null,7],
  ["AC-18(1)","Authentication and Encryption","AC-18",6],
  ["AC-18(2)","Monitoring Unauthorized Connections","AC-18",0],
  ["AC-18(3)","Disable Wireless Networking","AC-18",6],
  ["AC-18(4)","Restrict Configurations by Users","AC-18",4],
  ["AC-18(5)","Antennas and Transmission Power Levels","AC-18",4],
  ["AC-19","Access Control for Mobile Devices",null,7],
  ["AC-19(1)","Use of Writable and Portable Storage Devices","AC-19",0],
  ["AC-19(2)","Use of Personally Owned Portable Storage Devices","AC-19",0],
  ["AC-19(3)","Use of Portable Storage Devices with No Identifiable Owner","AC-19",0],
  ["AC-19(4)","Restrictions for Classified Information","AC-19",0],
  ["AC-19(5)","Full Device or Container-based Encryption","AC-19",6],
  ["AC-20","Use of External Systems",null,7],
  ["AC-20(1)","Limits on Authorized Use","AC-20",6],
  ["AC-20(2)","Portable Storage Devices — Restricted Use","AC-20",6],
  ["AC-20(3)","Non-organizationally Owned Systems — Restricted Use","AC-20",0],
  ["AC-20(4)","Network Accessible Storage Devices — Prohibited Use","AC-20",0],
  ["AC-20(5)","Portable Storage Devices — Prohibited Use","AC-20",0],
  ["AC-21","Information Sharing",null,6],
  ["AC-21(1)","Automated Decision Support","AC-21",0],
  ["AC-21(2)","Information Search and Retrieval","AC-21",0],
  ["AC-22","Publicly Accessible Content",null,7],
  ["AC-23","Data Mining Protection",null,0],
  ["AC-24","Access Control Decisions",null,0],
  ["AC-24(1)","Transmit Access Authorization Information","AC-24",0],
  ["AC-24(2)","No User or Process Identity","AC-24",0],
  ["AC-25","Reference Monitor",null,0],
  ["AT-1","Policy and Procedures",null,15],
  ["AT-2","Literacy Training and Awareness",null,15],
  ["AT-2(1)","Practical Exercises","AT-2",0],
  ["AT-2(2)","Insider Threat","AT-2",7],
  ["AT-2(3)","Social Engineering and Mining","AT-2",6],
  ["AT-2(4)","Suspicious Communications and Anomalous System Behavior","AT-2",0],
  ["AT-2(5)","Advanced Persistent Threat","AT-2",0],
  ["AT-2(6)","Cyber Threat Environment","AT-2",0],
  ["AT-3","Role-based Training",null,15],
  ["AT-3(1)","Environmental Controls","AT-3",0],
  ["AT-3(2)","Physical Security Controls","AT-3",0],
  ["AT-3(3)","Practical Exercises","AT-3",0],
  ["AT-3(4)","Suspicious Communications and Anomalous System Behavior","AT-3",0],
  ["AT-3(5)","Processing Personally Identifiable Information","AT-3",8],
  ["AT-4","Training Records",null,15],
  ["AT-5","Contacts with Security Groups and Associations",null,0],
  ["AT-6","Training Feedback",null,0],
  ["AU-1","Policy and Procedures",null,15],
  ["AU-2","Event Logging",null,15],
  ["AU-2(1)","Compilation of Audit Records from Multiple Sources","AU-2",0],
  ["AU-2(2)","Selection of Audit Events by Component","AU-2",0],
  ["AU-2(3)","Reviews and Updates","AU-2",0],
  ["AU-2(4)","Privileged Functions","AU-2",0],
  ["AU-3","Content of Audit Records",null,7],
  ["AU-3(1)","Additional Audit Information","AU-3",6],
  ["AU-3(2)","Centralized Management of Planned Audit Record Content","AU-3",0],
  ["AU-3(3)","Limit Personally Identifiable Information Elements","AU-3",8],
  ["AU-4","Audit Log Storage Capacity",null,7],
  ["AU-4(1)","Transfer to Alternate Storage","AU-4",0],
  ["AU-5","Response to Audit Logging Process Failures",null,7],
  ["AU-5(1)","Storage Capacity Warning","AU-5",4],
  ["AU-5(2)","Real-time Alerts","AU-5",4],
  ["AU-5(3)","Configurable Traffic Volume Thresholds","AU-5",0],
  ["AU-5(4)","Shutdown on Failure","AU-5",0],
  ["AU-5(5)","Alternate Audit Logging Capability","AU-5",0],
  ["AU-6","Audit Record Review, Analysis, and Reporting",null,7],
  ["AU-6(1)","Automated Process Integration","AU-6",6],
  ["AU-6(2)","Automated Security Alerts","AU-6",0],
  ["AU-6(3)","Correlate Audit Record Repositories","AU-6",6],
  ["AU-6(4)","Central Review and Analysis","AU-6",0],
  ["AU-6(5)","Integrated Analysis of Audit Records","AU-6",4],
  ["AU-6(6)","Correlation with Physical Monitoring","AU-6",4],
  ["AU-6(7)","Permitted Actions","AU-6",0],
  ["AU-6(8)","Full Text Analysis of Privileged Commands","AU-6",0],
  ["AU-6(9)","Correlation with Information from Nontechnical Sources","AU-6",0],
  ["AU-6(10)","Audit Level Adjustment","AU-6",0],
  ["AU-7","Audit Record Reduction and Report Generation",null,6],
  ["AU-7(1)","Automatic Processing","AU-7",6],
  ["AU-7(2)","Automatic Sort and Search","AU-7",0],
  ["AU-8","Time Stamps",null,7],
  ["AU-8(1)","Synchronization with Authoritative Time Source","AU-8",0],
  ["AU-8(2)","Secondary Authoritative Time Source","AU-8",0],
  ["AU-9","Protection of Audit Information",null,7],
  ["AU-9(1)","Hardware Write-once Media","AU-9",0],
  ["AU-9(2)","Store on Separate Physical Systems or Components","AU-9",4],
  ["AU-9(3)","Cryptographic Protection","AU-9",4],
  ["AU-9(4)","Access by Subset of Privileged Users","AU-9",6],
  ["AU-9(5)","Dual Authorization","AU-9",0],
  ["AU-9(6)","Read-only Access","AU-9",0],
  ["AU-9(7)","Store on Component with Different Operating System","AU-9",0],
  ["AU-10","Non-repudiation",null,4],
  ["AU-10(1)","Association of Identities","AU-10",0],
  ["AU-10(2)","Validate Binding of Information Producer Identity","AU-10",0],
  ["AU-10(3)","Chain of Custody","AU-10",0],
  ["AU-10(4)","Validate Binding of Information Reviewer Identity","AU-10",0],
  ["AU-10(5)","Digital Signatures","AU-10",0],
  ["AU-11","Audit Record Retention",null,15],
  ["AU-11(1)","Long-term Retrieval Capability","AU-11",0],
  ["AU-12","Audit Record Generation",null,7],
  ["AU-12(1)","System-wide and Time-correlated Audit Trail","AU-12",4],
  ["AU-12(2)","Standardized Formats","AU-12",0],
  ["AU-12(3)","Changes by Authorized Individuals","AU-12",4],
  ["AU-12(4)","Query Parameter Audits of Personally Identifiable Information","AU-12",0],
  ["AU-13","Monitoring for Information Disclosure",null,0],
  ["AU-13(1)","Use of Automated Tools","AU-13",0],
  ["AU-13(2)","Review of Monitored Sites","AU-13",0],
  ["AU-13(3)","Unauthorized Replication of Information","AU-13",0],
  ["AU-14","Session Audit",null,0],
  ["AU-14(1)","System Start-up","AU-14",0],
  ["AU-14(2)","Capture and Record Content","AU-14",0],
  ["AU-14(3)","Remote Viewing and Listening","AU-14",0],
  ["AU-15","Alternate Audit Logging Capability",null,0],
  ["AU-16","Cross-organizational Audit Logging",null,0],
  ["AU-16(1)","Identity Preservation","AU-16",0],
  ["AU-16(2)","Sharing of Audit Information","AU-16",0],
  ["AU-16(3)","Disassociability","AU-16",0],
  ["CA-1","Policy and Procedures",null,15],
  ["CA-2","Control Assessments",null,15],
  ["CA-2(1)","Independent Assessors","CA-2",6],
  ["CA-2(2)","Specialized Assessments","CA-2",4],
  ["CA-2(3)","Leveraging Results from External Organizations","CA-2",0],
  ["CA-3","Information Exchange",null,7],
  ["CA-3(1)","Unclassified National Security System Connections","CA-3",0],
  ["CA-3(2)","Classified National Security System Connections","CA-3",0],
  ["CA-3(3)","Unclassified Non-national Security System Connections","CA-3",0],
  ["CA-3(4)","Connections to Public Networks","CA-3",0],
  ["CA-3(5)","Restrictions on External System Connections","CA-3",0],
  ["CA-3(6)","Transfer Authorizations","CA-3",4],
  ["CA-3(7)","Transitive Information Exchanges","CA-3",0],
  ["CA-4","Security Certification",null,0],
  ["CA-5","Plan of Action and Milestones",null,15],
  ["CA-5(1)","Automation Support for Accuracy and Currency","CA-5",0],
  ["CA-6","Authorization",null,15],
  ["CA-6(1)","Joint Authorization — Intra-organization","CA-6",0],
  ["CA-6(2)","Joint Authorization — Inter-organization","CA-6",0],
  ["CA-7","Continuous Monitoring",null,15],
  ["CA-7(1)","Independent Assessment","CA-7",6],
  ["CA-7(2)","Types of Assessments","CA-7",0],
  ["CA-7(3)","Trend Analyses","CA-7",0],
  ["CA-7(4)","Risk Monitoring","CA-7",15],
  ["CA-7(5)","Consistency Analysis","CA-7",0],
  ["CA-7(6)","Automation Support for Monitoring","CA-7",0],
  ["CA-8","Penetration Testing",null,4],
  ["CA-8(1)","Independent Penetration Testing Agent or Team","CA-8",4],
  ["CA-8(2)","Red Team Exercises","CA-8",0],
  ["CA-8(3)","Facility Penetration Testing","CA-8",0],
  ["CA-9","Internal System Connections",null,7],
  ["CA-9(1)","Compliance Checks","CA-9",0],
  ["CM-1","Policy and Procedures",null,15],
  ["CM-2","Baseline Configuration",null,7],
  ["CM-2(1)","Reviews and Updates","CM-2",0],
  ["CM-2(2)","Automation Support for Accuracy and Currency","CM-2",6],
  ["CM-2(3)","Retention of Previous Configurations","CM-2",6],
  ["CM-2(4)","Unauthorized Software","CM-2",0],
  ["CM-2(5)","Authorized Software","CM-2",0],
  ["CM-2(6)","Development and Test Environments","CM-2",0],
  ["CM-2(7)","Configure Systems and Components for High-risk Areas","CM-2",6],
  ["CM-3","Configuration Change Control",null,6],
  ["CM-3(1)","Automated Documentation, Notification, and Prohibition of Changes","CM-3",4],
  ["CM-3(2)","Testing, Validation, and Documentation of Changes","CM-3",6],
  ["CM-3(3)","Automated Change Implementation","CM-3",0],
  ["CM-3(4)","Security and Privacy Representatives","CM-3",6],
  ["CM-3(5)","Automated Security Response","CM-3",0],
  ["CM-3(6)","Cryptography Management","CM-3",4],
  ["CM-3(7)","Review System Changes","CM-3",0],
  ["CM-3(8)","Prevent or Restrict Configuration Changes","CM-3",0],
  ["CM-4","Impact Analyses",null,15],
  ["CM-4(1)","Separate Test Environments","CM-4",4],
  ["CM-4(2)","Verification of Controls","CM-4",6],
  ["CM-5","Access Restrictions for Change",null,7],
  ["CM-5(1)","Automated Access Enforcement and Audit Records","CM-5",4],
  ["CM-5(2)","Review System Changes","CM-5",0],
  ["CM-5(3)","Signed Components","CM-5",0],
  ["CM-5(4)","Dual Authorization","CM-5",0],
  ["CM-5(5)","Privilege Limitation for Production and Operation","CM-5",0],
  ["CM-5(6)","Limit Library Privileges","CM-5",0],
  ["CM-5(7)","Automatic Implementation of Security Safeguards","CM-5",0],
  ["CM-6","Configuration Settings",null,7],
  ["CM-6(1)","Automated Management, Application, and Verification","CM-6",4],
  ["CM-6(2)","Respond to Unauthorized Changes","CM-6",4],
  ["CM-6(3)","Unauthorized Change Detection","CM-6",0],
  ["CM-6(4)","Conformance Demonstration","CM-6",0],
  ["CM-7","Least Functionality",null,7],
  ["CM-7(1)","Periodic Review","CM-7",6],
  ["CM-7(2)","Prevent Program Execution","CM-7",6],
  ["CM-7(3)","Registration Compliance","CM-7",0],
  ["CM-7(4)","Unauthorized Software — Deny-by-exception","CM-7",0],
  ["CM-7(5)","Authorized Software — Allow-by-exception","CM-7",6],
  ["CM-7(6)","Confined Environments with Limited Privileges","CM-7",0],
  ["CM-7(7)","Code Execution in Protected Environments","CM-7",0],
  ["CM-7(8)","Binary or Machine Executable Code","CM-7",0],
  ["CM-7(9)","Prohibiting The Use of Unauthorized Hardware","CM-7",0],
  ["CM-8","System Component Inventory",null,7],
  ["CM-8(1)","Updates During Installation and Removal","CM-8",6],
  ["CM-8(2)","Automated Maintenance","CM-8",4],
  ["CM-8(3)","Automated Unauthorized Component Detection","CM-8",6],
  ["CM-8(4)","Accountability Information","CM-8",4],
  ["CM-8(5)","No Duplicate Accounting of Components","CM-8",0],
  ["CM-8(6)","Assessed Configurations and Approved Deviations","CM-8",0],
  ["CM-8(7)","Centralized Repository","CM-8",0],
  ["CM-8(8)","Automated Location Tracking","CM-8",0],
  ["CM-8(9)","Assignment of Components to Systems","CM-8",0],
  ["CM-9","Configuration Management Plan",null,6],
  ["CM-9(1)","Assignment of Responsibility","CM-9",0],
  ["CM-10","Software Usage Restrictions",null,7],
  ["CM-10(1)","Open-source Software","CM-10",0],
  ["CM-11","User-installed Software",null,7],
  ["CM-11(1)","Alerts for Unauthorized Installations","CM-11",0],
  ["CM-11(2)","Software Installation with Privileged Status","CM-11",0],
  ["CM-11(3)","Automated Enforcement and Monitoring","CM-11",0],
  ["CM-12","Information Location",null,6],
  ["CM-12(1)","Automated Tools to Support Information Location","CM-12",6],
  ["CM-13","Data Action Mapping",null,0],
  ["CM-14","Signed Components",null,0],
  ["CP-1","Policy and Procedures",null,7],
  ["CP-2","Contingency Plan",null,7],
  ["CP-2(1)","Coordinate with Related Plans","CP-2",6],
  ["CP-2(2)","Capacity Planning","CP-2",4],
  ["CP-2(3)","Resume Mission and Business Functions","CP-2",6],
  ["CP-2(4)","Resume All Mission and Business Functions","CP-2",0],
  ["CP-2(5)","Continue Mission and Business Functions","CP-2",4],
  ["CP-2(6)","Alternate Processing and Storage Sites","CP-2",0],
  ["CP-2(7)","Coordinate with External Service Providers","CP-2",0],
  ["CP-2(8)","Identify Critical Assets","CP-2",6],
  ["CP-3","Contingency Training",null,7],
  ["CP-3(1)","Simulated Events","CP-3",4],
  ["CP-3(2)","Mechanisms Used in Training Environments","CP-3",0],
  ["CP-4","Contingency Plan Testing",null,7],
  ["CP-4(1)","Coordinate with Related Plans","CP-4",6],
  ["CP-4(2)","Alternate Processing Site","CP-4",4],
  ["CP-4(3)","Automated Testing","CP-4",0],
  ["CP-4(4)","Full Recovery and Reconstitution","CP-4",0],
  ["CP-4(5)","Self-challenge","CP-4",0],
  ["CP-5","Contingency Plan Update",null,0],
  ["CP-6","Alternate Storage Site",null,6],
  ["CP-6(1)","Separation from Primary Site","CP-6",6],
  ["CP-6(2)","Recovery Time and Recovery Point Objectives","CP-6",4],
  ["CP-6(3)","Accessibility","CP-6",6],
  ["CP-7","Alternate Processing Site",null,6],
  ["CP-7(1)","Separation from Primary Site","CP-7",6],
  ["CP-7(2)","Accessibility","CP-7",6],
  ["CP-7(3)","Priority of Service","CP-7",6],
  ["CP-7(4)","Preparation for Use","CP-7",4],
  ["CP-7(5)","Equivalent Information Security Safeguards","CP-7",0],
  ["CP-7(6)","Inability to Return to Primary Site","CP-7",0],
  ["CP-8","Telecommunications Services",null,6],
  ["CP-8(1)","Priority of Service Provisions","CP-8",6],
  ["CP-8(2)","Single Points of Failure","CP-8",6],
  ["CP-8(3)","Separation of Primary and Alternate Providers","CP-8",4],
  ["CP-8(4)","Provider Contingency Plan","CP-8",4],
  ["CP-8(5)","Alternate Telecommunication Service Testing","CP-8",0],
  ["CP-9","System Backup",null,7],
  ["CP-9(1)","Testing for Reliability and Integrity","CP-9",6],
  ["CP-9(2)","Test Restoration Using Sampling","CP-9",4],
  ["CP-9(3)","Separate Storage for Critical Information","CP-9",4],
  ["CP-9(4)","Protection from Unauthorized Modification","CP-9",0],
  ["CP-9(5)","Transfer to Alternate Storage Site","CP-9",4],
  ["CP-9(6)","Redundant Secondary System","CP-9",0],
  ["CP-9(7)","Dual Authorization for Deletion or Destruction","CP-9",0],
  ["CP-9(8)","Cryptographic Protection","CP-9",6],
  ["CP-10","System Recovery and Reconstitution",null,7],
  ["CP-10(1)","Contingency Plan Testing","CP-10",0],
  ["CP-10(2)","Transaction Recovery","CP-10",6],
  ["CP-10(3)","Compensating Security Controls","CP-10",0],
  ["CP-10(4)","Restore Within Time Period","CP-10",4],
  ["CP-10(5)","Failover Capability","CP-10",0],
  ["CP-10(6)","Component Protection","CP-10",0],
  ["CP-11","Alternate Communications Protocols",null,0],
  ["CP-12","Safe Mode",null,0],
  ["CP-13","Alternative Security Mechanisms",null,0],
  ["IA-1","Policy and Procedures",null,7],
  ["IA-2","Identification and Authentication (Organizational Users)",null,7],
  ["IA-2(1)","Multi-factor Authentication to Privileged Accounts","IA-2",7],
  ["IA-2(2)","Multi-factor Authentication to Non-privileged Accounts","IA-2",7],
  ["IA-2(3)","Local Access to Privileged Accounts","IA-2",0],
  ["IA-2(4)","Local Access to Non-privileged Accounts","IA-2",0],
  ["IA-2(5)","Individual Authentication with Group Authentication","IA-2",4],
  ["IA-2(6)","Access to Accounts —separate Device","IA-2",0],
  ["IA-2(7)","Network Access to Non-privileged Accounts — Separate Device","IA-2",0],
  ["IA-2(8)","Access to Accounts — Replay Resistant","IA-2",7],
  ["IA-2(9)","Network Access to Non-privileged Accounts — Replay Resistant","IA-2",0],
  ["IA-2(10)","Single Sign-on","IA-2",0],
  ["IA-2(11)","Remote Access — Separate Device","IA-2",0],
  ["IA-2(12)","Acceptance of PIV Credentials","IA-2",7],
  ["IA-2(13)","Out-of-band Authentication","IA-2",0],
  ["IA-3","Device Identification and Authentication",null,6],
  ["IA-3(1)","Cryptographic Bidirectional Authentication","IA-3",0],
  ["IA-3(2)","Cryptographic Bidirectional Network Authentication","IA-3",0],
  ["IA-3(3)","Dynamic Address Allocation","IA-3",0],
  ["IA-3(4)","Device Attestation","IA-3",0],
  ["IA-4","Identifier Management",null,7],
  ["IA-4(1)","Prohibit Account Identifiers as Public Identifiers","IA-4",0],
  ["IA-4(2)","Supervisor Authorization","IA-4",0],
  ["IA-4(3)","Multiple Forms of Certification","IA-4",0],
  ["IA-4(4)","Identify User Status","IA-4",6],
  ["IA-4(5)","Dynamic Management","IA-4",0],
  ["IA-4(6)","Cross-organization Management","IA-4",0],
  ["IA-4(7)","In-person Registration","IA-4",0],
  ["IA-4(8)","Pairwise Pseudonymous Identifiers","IA-4",0],
  ["IA-4(9)","Attribute Maintenance and Protection","IA-4",0],
  ["IA-5","Authenticator Management",null,7],
  ["IA-5(1)","Password-based Authentication","IA-5",7],
  ["IA-5(2)","Public Key-based Authentication","IA-5",6],
  ["IA-5(3)","In-person or Trusted External Party Registration","IA-5",0],
  ["IA-5(4)","Automated Support for Password Strength Determination","IA-5",0],
  ["IA-5(5)","Change Authenticators Prior to Delivery","IA-5",0],
  ["IA-5(6)","Protection of Authenticators","IA-5",6],
  ["IA-5(7)","No Embedded Unencrypted Static Authenticators","IA-5",0],
  ["IA-5(8)","Multiple System Accounts","IA-5",0],
  ["IA-5(9)","Federated Credential Management","IA-5",0],
  ["IA-5(10)","Dynamic Credential Binding","IA-5",0],
  ["IA-5(11)","Hardware Token-based Authentication","IA-5",0],
  ["IA-5(12)","Biometric Authentication Performance","IA-5",0],
  ["IA-5(13)","Expiration of Cached Authenticators","IA-5",0],
  ["IA-5(14)","Managing Content of PKI Trust Stores","IA-5",0],
  ["IA-5(15)","GSA-approved Products and Services","IA-5",0],
  ["IA-5(16)","In-person or Trusted External Party Authenticator Issuance","IA-5",0],
  ["IA-5(17)","Presentation Attack Detection for Biometric Authenticators","IA-5",0],
  ["IA-5(18)","Password Managers","IA-5",0],
  ["IA-6","Authentication Feedback",null,7],
  ["IA-7","Cryptographic Module Authentication",null,7],
  ["IA-8","Identification and Authentication (Non-organizational Users)",null,7],
  ["IA-8(1)","Acceptance of PIV Credentials from Other Agencies","IA-8",7],
  ["IA-8(2)","Acceptance of External Authenticators","IA-8",7],
  ["IA-8(3)","Use of FICAM-approved Products","IA-8",0],
  ["IA-8(4)","Use of Defined Profiles","IA-8",7],
  ["IA-8(5)","Acceptance of PIV-I Credentials","IA-8",0],
  ["IA-8(6)","Disassociability","IA-8",0],
  ["IA-9","Service Identification and Authentication",null,0],
  ["IA-9(1)","Information Exchange","IA-9",0],
  ["IA-9(2)","Transmission of Decisions","IA-9",0],
  ["IA-10","Adaptive Authentication",null,0],
  ["IA-11","Re-authentication",null,7],
  ["IA-12","Identity Proofing",null,6],
  ["IA-12(1)","Supervisor Authorization","IA-12",0],
  ["IA-12(2)","Identity Evidence","IA-12",6],
  ["IA-12(3)","Identity Evidence Validation and Verification","IA-12",6],
  ["IA-12(4)","In-person Validation and Verification","IA-12",4],
  ["IA-12(5)","Address Confirmation","IA-12",6],
  ["IA-12(6)","Accept Externally-proofed Identities","IA-12",0],
  ["IA-13","Identity Providers and Authorization Servers",null,0],
  ["IA-13(1)","Protection of Cryptographic Keys","IA-13",0],
  ["IA-13(2)","Verification of Identity Assertions and Access Tokens","IA-13",0],
  ["IA-13(3)","Token Management","IA-13",0],
  ["IR-1","Policy and Procedures",null,15],
  ["IR-2","Incident Response Training",null,15],
  ["IR-2(1)","Simulated Events","IR-2",4],
  ["IR-2(2)","Automated Training Environments","IR-2",4],
  ["IR-2(3)","Breach","IR-2",8],
  ["IR-3","Incident Response Testing",null,14],
  ["IR-3(1)","Automated Testing","IR-3",0],
  ["IR-3(2)","Coordination with Related Plans","IR-3",6],
  ["IR-3(3)","Continuous Improvement","IR-3",0],
  ["IR-4","Incident Handling",null,15],
  ["IR-4(1)","Automated Incident Handling Processes","IR-4",6],
  ["IR-4(2)","Dynamic Reconfiguration","IR-4",0],
  ["IR-4(3)","Continuity of Operations","IR-4",0],
  ["IR-4(4)","Information Correlation","IR-4",4],
  ["IR-4(5)","Automatic Disabling of System","IR-4",0],
  ["IR-4(6)","Insider Threats","IR-4",0],
  ["IR-4(7)","Insider Threats — Intra-organization Coordination","IR-4",0],
  ["IR-4(8)","Correlation with External Organizations","IR-4",0],
  ["IR-4(9)","Dynamic Response Capability","IR-4",0],
  ["IR-4(10)","Supply Chain Coordination","IR-4",0],
  ["IR-4(11)","Integrated Incident Response Team","IR-4",4],
  ["IR-4(12)","Malicious Code and Forensic Analysis","IR-4",0],
  ["IR-4(13)","Behavior Analysis","IR-4",0],
  ["IR-4(14)","Security Operations Center","IR-4",0],
  ["IR-4(15)","Public Relations and Reputation Repair","IR-4",0],
  ["IR-5","Incident Monitoring",null,15],
  ["IR-5(1)","Automated Tracking, Data Collection, and Analysis","IR-5",4],
  ["IR-6","Incident Reporting",null,15],
  ["IR-6(1)","Automated Reporting","IR-6",6],
  ["IR-6(2)","Vulnerabilities Related to Incidents","IR-6",0],
  ["IR-6(3)","Supply Chain Coordination","IR-6",6],
  ["IR-7","Incident Response Assistance",null,15],
  ["IR-7(1)","Automation Support for Availability of Information and Support","IR-7",6],
  ["IR-7(2)","Coordination with External Providers","IR-7",0],
  ["IR-8","Incident Response Plan",null,15],
  ["IR-8(1)","Breaches","IR-8",8],
  ["IR-9","Information Spillage Response",null,0],
  ["IR-9(1)","Responsible Personnel","IR-9",0],
  ["IR-9(2)","Training","IR-9",0],
  ["IR-9(3)","Post-spill Operations","IR-9",0],
  ["IR-9(4)","Exposure to Unauthorized Personnel","IR-9",0],
  ["IR-10","Integrated Information Security Analysis Team",null,0],
  ["MA-1","Policy and Procedures",null,7],
  ["MA-2","Controlled Maintenance",null,7],
  ["MA-2(1)","Record Content","MA-2",0],
  ["MA-2(2)","Automated Maintenance Activities","MA-2",4],
  ["MA-3","Maintenance Tools",null,6],
  ["MA-3(1)","Inspect Tools","MA-3",6],
  ["MA-3(2)","Inspect Media","MA-3",6],
  ["MA-3(3)","Prevent Unauthorized Removal","MA-3",6],
  ["MA-3(4)","Restricted Tool Use","MA-3",0],
  ["MA-3(5)","Execution with Privilege","MA-3",0],
  ["MA-3(6)","Software Updates and Patches","MA-3",0],
  ["MA-4","Nonlocal Maintenance",null,7],
  ["MA-4(1)","Logging and Review","MA-4",0],
  ["MA-4(2)","Document Nonlocal Maintenance","MA-4",0],
  ["MA-4(3)","Comparable Security and Sanitization","MA-4",4],
  ["MA-4(4)","Authentication and Separation of Maintenance Sessions","MA-4",0],
  ["MA-4(5)","Approvals and Notifications","MA-4",0],
  ["MA-4(6)","Cryptographic Protection","MA-4",0],
  ["MA-4(7)","Disconnect Verification","MA-4",0],
  ["MA-5","Maintenance Personnel",null,7],
  ["MA-5(1)","Individuals Without Appropriate Access","MA-5",4],
  ["MA-5(2)","Security Clearances for Classified Systems","MA-5",0],
  ["MA-5(3)","Citizenship Requirements for Classified Systems","MA-5",0],
  ["MA-5(4)","Foreign Nationals","MA-5",0],
  ["MA-5(5)","Non-system Maintenance","MA-5",0],
  ["MA-6","Timely Maintenance",null,6],
  ["MA-6(1)","Preventive Maintenance","MA-6",0],
  ["MA-6(2)","Predictive Maintenance","MA-6",0],
  ["MA-6(3)","Automated Support for Predictive Maintenance","MA-6",0],
  ["MA-7","Field Maintenance",null,0],
  ["MP-1","Policy and Procedures",null,15],
  ["MP-2","Media Access",null,7],
  ["MP-2(1)","Automated Restricted Access","MP-2",0],
  ["MP-2(2)","Cryptographic Protection","MP-2",0],
  ["MP-3","Media Marking",null,6],
  ["MP-4","Media Storage",null,6],
  ["MP-4(1)","Cryptographic Protection","MP-4",0],
  ["MP-4(2)","Automated Restricted Access","MP-4",0],
  ["MP-5","Media Transport",null,6],
  ["MP-5(1)","Protection Outside of Controlled Areas","MP-5",0],
  ["MP-5(2)","Documentation of Activities","MP-5",0],
  ["MP-5(3)","Custodians","MP-5",0],
  ["MP-5(4)","Cryptographic Protection","MP-5",0],
  ["MP-6","Media Sanitization",null,15],
  ["MP-6(1)","Review, Approve, Track, Document, and Verify","MP-6",4],
  ["MP-6(2)","Equipment Testing","MP-6",4],
  ["MP-6(3)","Nondestructive Techniques","MP-6",4],
  ["MP-6(4)","Controlled Unclassified Information","MP-6",0],
  ["MP-6(5)","Classified Information","MP-6",0],
  ["MP-6(6)","Media Destruction","MP-6",0],
  ["MP-6(7)","Dual Authorization","MP-6",0],
  ["MP-6(8)","Remote Purging or Wiping of Information","MP-6",0],
  ["MP-7","Media Use",null,7],
  ["MP-7(1)","Prohibit Use Without Owner","MP-7",0],
  ["MP-7(2)","Prohibit Use of Sanitization-resistant Media","MP-7",0],
  ["MP-8","Media Downgrading",null,0],
  ["MP-8(1)","Documentation of Process","MP-8",0],
  ["MP-8(2)","Equipment Testing","MP-8",0],
  ["MP-8(3)","Controlled Unclassified Information","MP-8",0],
  ["MP-8(4)","Classified Information","MP-8",0],
  ["PE-1","Policy and Procedures",null,7],
  ["PE-2","Physical Access Authorizations",null,7],
  ["PE-2(1)","Access by Position or Role","PE-2",0],
  ["PE-2(2)","Two Forms of Identification","PE-2",0],
  ["PE-2(3)","Restrict Unescorted Access","PE-2",0],
  ["PE-3","Physical Access Control",null,7],
  ["PE-3(1)","System Access","PE-3",4],
  ["PE-3(2)","Facility and Systems","PE-3",0],
  ["PE-3(3)","Continuous Guards","PE-3",0],
  ["PE-3(4)","Lockable Casings","PE-3",0],
  ["PE-3(5)","Tamper Protection","PE-3",0],
  ["PE-3(6)","Facility Penetration Testing","PE-3",0],
  ["PE-3(7)","Physical Barriers","PE-3",0],
  ["PE-3(8)","Access Control Vestibules","PE-3",0],
  ["PE-4","Access Control for Transmission",null,6],
  ["PE-5","Access Control for Output Devices",null,6],
  ["PE-5(1)","Access to Output by Authorized Individuals","PE-5",0],
  ["PE-5(2)","Link to Individual Identity","PE-5",0],
  ["PE-5(3)","Marking Output Devices","PE-5",0],
  ["PE-6","Monitoring Physical Access",null,7],
  ["PE-6(1)","Intrusion Alarms and Surveillance Equipment","PE-6",6],
  ["PE-6(2)","Automated Intrusion Recognition and Responses","PE-6",0],
  ["PE-6(3)","Video Surveillance","PE-6",0],
  ["PE-6(4)","Monitoring Physical Access to Systems","PE-6",4],
  ["PE-7","Visitor Control",null,0],
  ["PE-8","Visitor Access Records",null,7],
  ["PE-8(1)","Automated Records Maintenance and Review","PE-8",4],
  ["PE-8(2)","Physical Access Records","PE-8",0],
  ["PE-8(3)","Limit Personally Identifiable Information Elements","PE-8",8],
  ["PE-9","Power Equipment and Cabling",null,6],
  ["PE-9(1)","Redundant Cabling","PE-9",0],
  ["PE-9(2)","Automatic Voltage Controls","PE-9",0],
  ["PE-10","Emergency Shutoff",null,6],
  ["PE-10(1)","Accidental and Unauthorized Activation","PE-10",0],
  ["PE-11","Emergency Power",null,6],
  ["PE-11(1)","Alternate Power Supply — Minimal Operational Capability","PE-11",4],
  ["PE-11(2)","Alternate Power Supply — Self-contained","PE-11",0],
  ["PE-12","Emergency Lighting",null,7],
  ["PE-12(1)","Essential Mission and Business Functions","PE-12",0],
  ["PE-13","Fire Protection",null,7],
  ["PE-13(1)","Detection Systems — Automatic Activation and Notification","PE-13",6],
  ["PE-13(2)","Suppression Systems — Automatic Activation and Notification","PE-13",4],
  ["PE-13(3)","Automatic Fire Suppression","PE-13",0],
  ["PE-13(4)","Inspections","PE-13",0],
  ["PE-14","Environmental Controls",null,7],
  ["PE-14(1)","Automatic Controls","PE-14",0],
  ["PE-14(2)","Monitoring with Alarms and Notifications","PE-14",0],
  ["PE-15","Water Damage Protection",null,7],
  ["PE-15(1)","Automation Support","PE-15",4],
  ["PE-16","Delivery and Removal",null,7],
  ["PE-17","Alternate Work Site",null,6],
  ["PE-18","Location of System Components",null,4],
  ["PE-18(1)","Facility Site","PE-18",0],
  ["PE-19","Information Leakage",null,0],
  ["PE-19(1)","National Emissions Policies and Procedures","PE-19",0],
  ["PE-20","Asset Monitoring and Tracking",null,0],
  ["PE-21","Electromagnetic Pulse Protection",null,0],
  ["PE-22","Component Marking",null,0],
  ["PE-23","Facility Location",null,0],
  ["PL-1","Policy and Procedures",null,15],
  ["PL-2","System Security and Privacy Plans",null,15],
  ["PL-2(1)","Concept of Operations","PL-2",0],
  ["PL-2(2)","Functional Architecture","PL-2",0],
  ["PL-2(3)","Plan and Coordinate with Other Organizational Entities","PL-2",0],
  ["PL-3","System Security Plan Update",null,0],
  ["PL-4","Rules of Behavior",null,15],
  ["PL-4(1)","Social Media and External Site/Application Usage Restrictions","PL-4",15],
  ["PL-5","Privacy Impact Assessment",null,0],
  ["PL-6","Security-related Activity Planning",null,0],
  ["PL-7","Concept of Operations",null,0],
  ["PL-8","Security and Privacy Architectures",null,14],
  ["PL-8(1)","Defense in Depth","PL-8",0],
  ["PL-8(2)","Supplier Diversity","PL-8",0],
  ["PL-9","Central Management",null,8],
  ["PL-10","Baseline Selection",null,7],
  ["PL-11","Baseline Tailoring",null,7],
  ["PM-1","Information Security Program Plan",null,0],
  ["PM-2","Information Security Program Leadership Role",null,0],
  ["PM-3","Information Security and Privacy Resources",null,8],
  ["PM-4","Plan of Action and Milestones Process",null,8],
  ["PM-5","System Inventory",null,0],
  ["PM-5(1)","Inventory of Personally Identifiable Information","PM-5",8],
  ["PM-6","Measures of Performance",null,8],
  ["PM-7","Enterprise Architecture",null,8],
  ["PM-7(1)","Offloading","PM-7",0],
  ["PM-8","Critical Infrastructure Plan",null,8],
  ["PM-9","Risk Management Strategy",null,8],
  ["PM-10","Authorization Process",null,8],
  ["PM-11","Mission and Business Process Definition",null,8],
  ["PM-12","Insider Threat Program",null,0],
  ["PM-13","Security and Privacy Workforce",null,8],
  ["PM-14","Testing, Training, and Monitoring",null,8],
  ["PM-15","Security and Privacy Groups and Associations",null,0],
  ["PM-16","Threat Awareness Program",null,0],
  ["PM-16(1)","Automated Means for Sharing Threat Intelligence","PM-16",0],
  ["PM-17","Protecting Controlled Unclassified Information on External Systems",null,8],
  ["PM-18","Privacy Program Plan",null,8],
  ["PM-19","Privacy Program Leadership Role",null,8],
  ["PM-20","Dissemination of Privacy Program Information",null,8],
  ["PM-20(1)","Privacy Policies on Websites, Applications, and Digital Services","PM-20",8],
  ["PM-21","Accounting of Disclosures",null,8],
  ["PM-22","Personally Identifiable Information Quality Management",null,8],
  ["PM-23","Data Governance Body",null,0],
  ["PM-24","Data Integrity Board",null,8],
  ["PM-25","Minimization of Personally Identifiable Information Used in Testing, Training, and Research",null,8],
  ["PM-26","Complaint Management",null,8],
  ["PM-27","Privacy Reporting",null,8],
  ["PM-28","Risk Framing",null,8],
  ["PM-29","Risk Management Program Leadership Roles",null,0],
  ["PM-30","Supply Chain Risk Management Strategy",null,0],
  ["PM-30(1)","Suppliers of Critical or Mission-essential Items","PM-30",0],
  ["PM-31","Continuous Monitoring Strategy",null,8],
  ["PM-32","Purposing",null,0],
  ["PS-1","Policy and Procedures",null,7],
  ["PS-2","Position Risk Designation",null,7],
  ["PS-3","Personnel Screening",null,7],
  ["PS-3(1)","Classified Information","PS-3",0],
  ["PS-3(2)","Formal Indoctrination","PS-3",0],
  ["PS-3(3)","Information Requiring Special Protective Measures","PS-3",0],
  ["PS-3(4)","Citizenship Requirements","PS-3",0],
  ["PS-4","Personnel Termination",null,7],
  ["PS-4(1)","Post-employment Requirements","PS-4",0],
  ["PS-4(2)","Automated Actions","PS-4",4],
  ["PS-5","Personnel Transfer",null,7],
  ["PS-6","Access Agreements",null,15],
  ["PS-6(1)","Information Requiring Special Protection","PS-6",0],
  ["PS-6(2)","Classified Information Requiring Special Protection","PS-6",0],
  ["PS-6(3)","Post-employment Requirements","PS-6",0],
  ["PS-7","External Personnel Security",null,7],
  ["PS-8","Personnel Sanctions",null,7],
  ["PS-9","Position Descriptions",null,7],
  ["PT-1","Policy and Procedures",null,8],
  ["PT-2","Authority to Process Personally Identifiable Information",null,8],
  ["PT-2(1)","Data Tagging","PT-2",0],
  ["PT-2(2)","Automation","PT-2",0],
  ["PT-3","Personally Identifiable Information Processing Purposes",null,8],
  ["PT-3(1)","Data Tagging","PT-3",0],
  ["PT-3(2)","Automation","PT-3",0],
  ["PT-4","Consent",null,8],
  ["PT-4(1)","Tailored Consent","PT-4",0],
  ["PT-4(2)","Just-in-time Consent","PT-4",0],
  ["PT-4(3)","Revocation","PT-4",0],
  ["PT-5","Privacy Notice",null,8],
  ["PT-5(1)","Just-in-time Notice","PT-5",0],
  ["PT-5(2)","Privacy Act Statements","PT-5",8],
  ["PT-6","System of Records Notice",null,8],
  ["PT-6(1)","Routine Uses","PT-6",8],
  ["PT-6(2)","Exemption Rules","PT-6",8],
  ["PT-7","Specific Categories of Personally Identifiable Information",null,8],
  ["PT-7(1)","Social Security Numbers","PT-7",8],
  ["PT-7(2)","First Amendment Information","PT-7",8],
  ["PT-8","Computer Matching Requirements",null,8],
  ["RA-1","Policy and Procedures",null,15],
  ["RA-2","Security Categorization",null,7],
  ["RA-2(1)","Impact-level Prioritization","RA-2",0],
  ["RA-3","Risk Assessment",null,15],
  ["RA-3(1)","Supply Chain Risk Assessment","RA-3",7],
  ["RA-3(2)","Use of All-source Intelligence","RA-3",0],
  ["RA-3(3)","Dynamic Threat Awareness","RA-3",0],
  ["RA-3(4)","Predictive Cyber Analytics","RA-3",0],
  ["RA-4","Risk Assessment Update",null,0],
  ["RA-5","Vulnerability Monitoring and Scanning",null,7],
  ["RA-5(1)","Update Tool Capability","RA-5",0],
  ["RA-5(2)","Update Vulnerabilities to Be Scanned","RA-5",7],
  ["RA-5(3)","Breadth and Depth of Coverage","RA-5",0],
  ["RA-5(4)","Discoverable Information","RA-5",4],
  ["RA-5(5)","Privileged Access","RA-5",6],
  ["RA-5(6)","Automated Trend Analyses","RA-5",0],
  ["RA-5(7)","Automated Detection and Notification of Unauthorized Components","RA-5",0],
  ["RA-5(8)","Review Historic Audit Logs","RA-5",0],
  ["RA-5(9)","Penetration Testing and Analyses","RA-5",0],
  ["RA-5(10)","Correlate Scanning Information","RA-5",0],
  ["RA-5(11)","Public Disclosure Program","RA-5",7],
  ["RA-6","Technical Surveillance Countermeasures Survey",null,0],
  ["RA-7","Risk Response",null,15],
  ["RA-8","Privacy Impact Assessments",null,8],
  ["RA-9","Criticality Analysis",null,6],
  ["RA-10","Threat Hunting",null,0],
  ["SA-1","Policy and Procedures",null,15],
  ["SA-2","Allocation of Resources",null,15],
  ["SA-3","System Development Life Cycle",null,15],
  ["SA-3(1)","Manage Preproduction Environment","SA-3",0],
  ["SA-3(2)","Use of Live or Operational Data","SA-3",0],
  ["SA-3(3)","Technology Refresh","SA-3",0],
  ["SA-4","Acquisition Process",null,15],
  ["SA-4(1)","Functional Properties of Controls","SA-4",6],
  ["SA-4(2)","Design and Implementation Information for Controls","SA-4",6],
  ["SA-4(3)","Development Methods, Techniques, and Practices","SA-4",0],
  ["SA-4(4)","Assignment of Components to Systems","SA-4",0],
  ["SA-4(5)","System, Component, and Service Configurations","SA-4",4],
  ["SA-4(6)","Use of Information Assurance Products","SA-4",0],
  ["SA-4(7)","NIAP-approved Protection Profiles ","SA-4",0],
  ["SA-4(8)","Continuous Monitoring Plan for Controls","SA-4",0],
  ["SA-4(9)","Functions, Ports, Protocols, and Services in Use","SA-4",6],
  ["SA-4(10)","Use of Approved PIV Products","SA-4",7],
  ["SA-4(11)","System of Records","SA-4",0],
  ["SA-4(12)","Data Ownership","SA-4",0],
  ["SA-5","System Documentation",null,7],
  ["SA-5(1)","Functional Properties of Security Controls","SA-5",0],
  ["SA-5(2)","Security-relevant External System Interfaces","SA-5",0],
  ["SA-5(3)","High-level Design","SA-5",0],
  ["SA-5(4)","Low-level Design","SA-5",0],
  ["SA-5(5)","Source Code","SA-5",0],
  ["SA-6","Software Usage Restrictions",null,0],
  ["SA-7","User-installed Software",null,0],
  ["SA-8","Security and Privacy Engineering Principles",null,7],
  ["SA-8(1)","Clear Abstractions","SA-8",0],
  ["SA-8(2)","Least Common Mechanism","SA-8",0],
  ["SA-8(3)","Modularity and Layering","SA-8",0],
  ["SA-8(4)","Partially Ordered Dependencies","SA-8",0],
  ["SA-8(5)","Efficiently Mediated Access","SA-8",0],
  ["SA-8(6)","Minimized Sharing","SA-8",0],
  ["SA-8(7)","Reduced Complexity","SA-8",0],
  ["SA-8(8)","Secure Evolvability","SA-8",0],
  ["SA-8(9)","Trusted Components","SA-8",0],
  ["SA-8(10)","Hierarchical Trust","SA-8",0],
  ["SA-8(11)","Inverse Modification Threshold","SA-8",0],
  ["SA-8(12)","Hierarchical Protection","SA-8",0],
  ["SA-8(13)","Minimized Security Elements","SA-8",0],
  ["SA-8(14)","Least Privilege","SA-8",0],
  ["SA-8(15)","Predicate Permission","SA-8",0],
  ["SA-8(16)","Self-reliant Trustworthiness","SA-8",0],
  ["SA-8(17)","Secure Distributed Composition","SA-8",0],
  ["SA-8(18)","Trusted Communications Channels","SA-8",0],
  ["SA-8(19)","Continuous Protection","SA-8",0],
  ["SA-8(20)","Secure Metadata Management","SA-8",0],
  ["SA-8(21)","Self-analysis","SA-8",0],
  ["SA-8(22)","Accountability and Traceability","SA-8",0],
  ["SA-8(23)","Secure Defaults","SA-8",0],
  ["SA-8(24)","Secure Failure and Recovery","SA-8",0],
  ["SA-8(25)","Economic Security","SA-8",0],
  ["SA-8(26)","Performance Security","SA-8",0],
  ["SA-8(27)","Human Factored Security","SA-8",0],
  ["SA-8(28)","Acceptable Security","SA-8",0],
  ["SA-8(29)","Repeatable and Documented Procedures","SA-8",0],
  ["SA-8(30)","Procedural Rigor","SA-8",0],
  ["SA-8(31)","Secure System Modification","SA-8",0],
  ["SA-8(32)","Sufficient Documentation","SA-8",0],
  ["SA-8(33)","Minimization","SA-8",8],
  ["SA-9","External System Services",null,15],
  ["SA-9(1)","Risk Assessments and Organizational Approvals","SA-9",0],
  ["SA-9(2)","Identification of Functions, Ports, Protocols, and Services","SA-9",6],
  ["SA-9(3)","Establish and Maintain Trust Relationship with Providers","SA-9",0],
  ["SA-9(4)","Consistent Interests of Consumers and Providers","SA-9",0],
  ["SA-9(5)","Processing, Storage, and Service Location","SA-9",0],
  ["SA-9(6)","Organization-controlled Cryptographic Keys","SA-9",0],
  ["SA-9(7)","Organization-controlled Integrity Checking","SA-9",0],
  ["SA-9(8)","Processing and Storage Location — U.S. Jurisdiction","SA-9",0],
  ["SA-10","Developer Configuration Management",null,6],
  ["SA-10(1)","Software and Firmware Integrity Verification","SA-10",0],
  ["SA-10(2)","Alternative Configuration Management Processes","SA-10",0],
  ["SA-10(3)","Hardware Integrity Verification","SA-10",0],
  ["SA-10(4)","Trusted Generation","SA-10",0],
  ["SA-10(5)","Mapping Integrity for Version Control","SA-10",0],
  ["SA-10(6)","Trusted Distribution","SA-10",0],
  ["SA-10(7)","Security and Privacy Representatives","SA-10",0],
  ["SA-11","Developer Testing and Evaluation",null,14],
  ["SA-11(1)","Static Code Analysis","SA-11",0],
  ["SA-11(2)","Threat Modeling and Vulnerability Analyses","SA-11",0],
  ["SA-11(3)","Independent Verification of Assessment Plans and Evidence","SA-11",0],
  ["SA-11(4)","Manual Code Reviews","SA-11",0],
  ["SA-11(5)","Penetration Testing","SA-11",0],
  ["SA-11(6)","Attack Surface Reviews","SA-11",0],
  ["SA-11(7)","Verify Scope of Testing and Evaluation","SA-11",0],
  ["SA-11(8)","Dynamic Code Analysis","SA-11",0],
  ["SA-11(9)","Interactive Application Security Testing","SA-11",0],
  ["SA-12","Supply Chain Protection",null,0],
  ["SA-12(1)","Acquisition Strategies / Tools / Methods","SA-12",0],
  ["SA-12(2)","Supplier Reviews","SA-12",0],
  ["SA-12(3)","Trusted Shipping and Warehousing","SA-12",0],
  ["SA-12(4)","Diversity of Suppliers","SA-12",0],
  ["SA-12(5)","Limitation of Harm","SA-12",0],
  ["SA-12(6)","Minimizing Procurement Time","SA-12",0],
  ["SA-12(7)","Assessments Prior to Selection / Acceptance / Update","SA-12",0],
  ["SA-12(8)","Use of All-source Intelligence","SA-12",0],
  ["SA-12(9)","Operations Security","SA-12",0],
  ["SA-12(10)","Validate as Genuine and Not Altered","SA-12",0],
  ["SA-12(11)","Penetration Testing / Analysis of Elements, Processes, and Actors","SA-12",0],
  ["SA-12(12)","Inter-organizational Agreements","SA-12",0],
  ["SA-12(13)","Critical Information System Components","SA-12",0],
  ["SA-12(14)","Identity and Traceability","SA-12",0],
  ["SA-12(15)","Processes to Address Weaknesses or Deficiencies","SA-12",0],
  ["SA-13","Trustworthiness",null,0],
  ["SA-14","Criticality Analysis",null,0],
  ["SA-14(1)","Critical Components with No Viable Alternative Sourcing","SA-14",0],
  ["SA-15","Development Process, Standards, and Tools",null,6],
  ["SA-15(1)","Quality Metrics","SA-15",0],
  ["SA-15(2)","Security and Privacy Tracking Tools","SA-15",0],
  ["SA-15(3)","Criticality Analysis","SA-15",6],
  ["SA-15(4)","Threat Modeling and Vulnerability Analysis","SA-15",0],
  ["SA-15(5)","Attack Surface Reduction","SA-15",0],
  ["SA-15(6)","Continuous Improvement","SA-15",0],
  ["SA-15(7)","Automated Vulnerability Analysis","SA-15",0],
  ["SA-15(8)","Reuse of Threat and Vulnerability Information","SA-15",0],
  ["SA-15(9)","Use of Live Data","SA-15",0],
  ["SA-15(10)","Incident Response Plan","SA-15",0],
  ["SA-15(11)","Archive System or Component","SA-15",0],
  ["SA-15(12)","Minimize Personally Identifiable Information","SA-15",0],
  ["SA-15(13)","Logging Syntax","SA-15",0],
  ["SA-16","Developer-provided Training",null,4],
  ["SA-17","Developer Security and Privacy Architecture and Design",null,4],
  ["SA-17(1)","Formal Policy Model","SA-17",0],
  ["SA-17(2)","Security-relevant Components","SA-17",0],
  ["SA-17(3)","Formal Correspondence","SA-17",0],
  ["SA-17(4)","Informal Correspondence","SA-17",0],
  ["SA-17(5)","Conceptually Simple Design","SA-17",0],
  ["SA-17(6)","Structure for Testing","SA-17",0],
  ["SA-17(7)","Structure for Least Privilege","SA-17",0],
  ["SA-17(8)","Orchestration","SA-17",0],
  ["SA-17(9)","Design Diversity","SA-17",0],
  ["SA-18","Tamper Resistance and Detection",null,0],
  ["SA-18(1)","Multiple Phases of System Development Life Cycle","SA-18",0],
  ["SA-18(2)","Inspection of Systems or Components","SA-18",0],
  ["SA-19","Component Authenticity",null,0],
  ["SA-19(1)","Anti-counterfeit Training","SA-19",0],
  ["SA-19(2)","Configuration Control for Component Service and Repair","SA-19",0],
  ["SA-19(3)","Component Disposal","SA-19",0],
  ["SA-19(4)","Anti-counterfeit Scanning","SA-19",0],
  ["SA-20","Customized Development of Critical Components",null,0],
  ["SA-21","Developer Screening",null,4],
  ["SA-21(1)","Validation of Screening","SA-21",0],
  ["SA-22","Unsupported System Components",null,7],
  ["SA-22(1)","Alternative Sources for Continued Support","SA-22",0],
  ["SA-23","Specialization",null,0],
  ["SA-24","Design For Cyber Resiliency",null,0],
  ["SC-1","Policy and Procedures",null,7],
  ["SC-2","Separation of System and User Functionality",null,6],
  ["SC-2(1)","Interfaces for Non-privileged Users","SC-2",0],
  ["SC-2(2)","Disassociability","SC-2",0],
  ["SC-3","Security Function Isolation",null,4],
  ["SC-3(1)","Hardware Separation","SC-3",0],
  ["SC-3(2)","Access and Flow Control Functions","SC-3",0],
  ["SC-3(3)","Minimize Nonsecurity Functionality","SC-3",0],
  ["SC-3(4)","Module Coupling and Cohesiveness","SC-3",0],
  ["SC-3(5)","Layered Structures","SC-3",0],
  ["SC-4","Information in Shared System Resources",null,6],
  ["SC-4(1)","Security Levels","SC-4",0],
  ["SC-4(2)","Multilevel or Periods Processing","SC-4",0],
  ["SC-5","Denial-of-service Protection",null,7],
  ["SC-5(1)","Restrict Ability to Attack Other Systems","SC-5",0],
  ["SC-5(2)","Capacity, Bandwidth, and Redundancy","SC-5",0],
  ["SC-5(3)","Detection and Monitoring","SC-5",0],
  ["SC-6","Resource Availability",null,0],
  ["SC-7","Boundary Protection",null,7],
  ["SC-7(1)","Physically Separated Subnetworks","SC-7",0],
  ["SC-7(2)","Public Access","SC-7",0],
  ["SC-7(3)","Access Points","SC-7",6],
  ["SC-7(4)","External Telecommunications Services","SC-7",6],
  ["SC-7(5)","Deny by Default — Allow by Exception","SC-7",6],
  ["SC-7(6)","Response to Recognized Failures","SC-7",0],
  ["SC-7(7)","Split Tunneling for Remote Devices","SC-7",6],
  ["SC-7(8)","Route Traffic to Authenticated Proxy Servers","SC-7",6],
  ["SC-7(9)","Restrict Threatening Outgoing Communications Traffic","SC-7",0],
  ["SC-7(10)","Prevent Exfiltration","SC-7",0],
  ["SC-7(11)","Restrict Incoming Communications Traffic","SC-7",0],
  ["SC-7(12)","Host-based Protection","SC-7",0],
  ["SC-7(13)","Isolation of Security Tools, Mechanisms, and Support Components","SC-7",0],
  ["SC-7(14)","Protect Against Unauthorized Physical Connections","SC-7",0],
  ["SC-7(15)","Networked Privileged Accesses","SC-7",0],
  ["SC-7(16)","Prevent Discovery of System Components","SC-7",0],
  ["SC-7(17)","Automated Enforcement of Protocol Formats","SC-7",0],
  ["SC-7(18)","Fail Secure","SC-7",4],
  ["SC-7(19)","Block Communication from Non-organizationally Configured Hosts","SC-7",0],
  ["SC-7(20)","Dynamic Isolation and Segregation","SC-7",0],
  ["SC-7(21)","Isolation of System Components","SC-7",4],
  ["SC-7(22)","Separate Subnets for Connecting to Different Security Domains","SC-7",0],
  ["SC-7(23)","Disable Sender Feedback on Protocol Validation Failure","SC-7",0],
  ["SC-7(24)","Personally Identifiable Information","SC-7",8],
  ["SC-7(25)","Unclassified National Security System Connections","SC-7",0],
  ["SC-7(26)","Classified National Security System Connections","SC-7",0],
  ["SC-7(27)","Unclassified Non-national Security System Connections","SC-7",0],
  ["SC-7(28)","Connections to Public Networks","SC-7",0],
  ["SC-7(29)","Separate Subnets to Isolate Functions","SC-7",0],
  ["SC-8","Transmission Confidentiality and Integrity",null,6],
  ["SC-8(1)","Cryptographic Protection","SC-8",6],
  ["SC-8(2)","Pre- and Post-transmission Handling","SC-8",0],
  ["SC-8(3)","Cryptographic Protection for Message Externals","SC-8",0],
  ["SC-8(4)","Conceal or Randomize Communications","SC-8",0],
  ["SC-8(5)","Protected Distribution System","SC-8",0],
  ["SC-9","Transmission Confidentiality",null,0],
  ["SC-10","Network Disconnect",null,6],
  ["SC-11","Trusted Path",null,0],
  ["SC-11(1)","Irrefutable Communications Path","SC-11",0],
  ["SC-12","Cryptographic Key Establishment and Management",null,7],
  ["SC-12(1)","Availability","SC-12",4],
  ["SC-12(2)","Symmetric Keys","SC-12",0],
  ["SC-12(3)","Asymmetric Keys","SC-12",0],
  ["SC-12(4)","PKI Certificates","SC-12",0],
  ["SC-12(5)","PKI Certificates / Hardware Tokens","SC-12",0],
  ["SC-12(6)","Physical Control of Keys","SC-12",0],
  ["SC-13","Cryptographic Protection",null,7],
  ["SC-13(1)","FIPS-validated Cryptography","SC-13",0],
  ["SC-13(2)","NSA-approved Cryptography","SC-13",0],
  ["SC-13(3)","Individuals Without Formal Access Approvals","SC-13",0],
  ["SC-13(4)","Digital Signatures","SC-13",0],
  ["SC-14","Public Access Protections",null,0],
  ["SC-15","Collaborative Computing Devices and Applications",null,7],
  ["SC-15(1)","Physical or Logical Disconnect","SC-15",0],
  ["SC-15(2)","Blocking Inbound and Outbound Communications Traffic","SC-15",0],
  ["SC-15(3)","Disabling and Removal in Secure Work Areas","SC-15",0],
  ["SC-15(4)","Explicitly Indicate Current Participants","SC-15",0],
  ["SC-16","Transmission of Security and Privacy Attributes",null,0],
  ["SC-16(1)","Integrity Verification","SC-16",0],
  ["SC-16(2)","Anti-spoofing Mechanisms","SC-16",0],
  ["SC-16(3)","Cryptographic Binding","SC-16",0],
  ["SC-17","Public Key Infrastructure Certificates",null,6],
  ["SC-18","Mobile Code",null,6],
  ["SC-18(1)","Identify Unacceptable Code and Take Corrective Actions","SC-18",0],
  ["SC-18(2)","Acquisition, Development, and Use","SC-18",0],
  ["SC-18(3)","Prevent Downloading and Execution","SC-18",0],
  ["SC-18(4)","Prevent Automatic Execution","SC-18",0],
  ["SC-18(5)","Allow Execution Only in Confined Environments","SC-18",0],
  ["SC-19","Voice Over Internet Protocol",null,0],
  ["SC-20","Secure Name/Address Resolution Service (Authoritative Source)",null,7],
  ["SC-20(1)","Child Subspaces","SC-20",0],
  ["SC-20(2)","Data Origin and Integrity","SC-20",0],
  ["SC-21","Secure Name/Address Resolution Service (Recursive or Caching Resolver)",null,7],
  ["SC-21(1)","Data Origin and Integrity","SC-21",0],
  ["SC-22","Architecture and Provisioning for Name/Address Resolution Service",null,7],
  ["SC-23","Session Authenticity",null,6],
  ["SC-23(1)","Invalidate Session Identifiers at Logout","SC-23",0],
  ["SC-23(2)","User-initiated Logouts and Message Displays","SC-23",0],
  ["SC-23(3)","Unique System-generated Session Identifiers","SC-23",0],
  ["SC-23(4)","Unique Session Identifiers with Randomization","SC-23",0],
  ["SC-23(5)","Allowed Certificate Authorities","SC-23",0],
  ["SC-24","Fail in Known State",null,4],
  ["SC-25","Thin Nodes",null,0],
  ["SC-26","Decoys",null,0],
  ["SC-26(1)","Detection of Malicious Code","SC-26",0],
  ["SC-27","Platform-independent Applications",null,0],
  ["SC-28","Protection of Information at Rest",null,6],
  ["SC-28(1)","Cryptographic Protection","SC-28",6],
  ["SC-28(2)","Offline Storage","SC-28",0],
  ["SC-28(3)","Cryptographic Keys","SC-28",0],
  ["SC-29","Heterogeneity",null,0],
  ["SC-29(1)","Virtualization Techniques","SC-29",0],
  ["SC-30","Concealment and Misdirection",null,0],
  ["SC-30(1)","Virtualization Techniques","SC-30",0],
  ["SC-30(2)","Randomness","SC-30",0],
  ["SC-30(3)","Change Processing and Storage Locations","SC-30",0],
  ["SC-30(4)","Misleading Information","SC-30",0],
  ["SC-30(5)","Concealment of System Components","SC-30",0],
  ["SC-31","Covert Channel Analysis",null,0],
  ["SC-31(1)","Test Covert Channels for Exploitability","SC-31",0],
  ["SC-31(2)","Maximum Bandwidth","SC-31",0],
  ["SC-31(3)","Measure Bandwidth in Operational Environments","SC-31",0],
  ["SC-32","System Partitioning",null,0],
  ["SC-32(1)","Separate Physical Domains for Privileged Functions","SC-32",0],
  ["SC-33","Transmission Preparation Integrity",null,0],
  ["SC-34","Non-modifiable Executable Programs",null,0],
  ["SC-34(1)","No Writable Storage","SC-34",0],
  ["SC-34(2)","Integrity Protection on Read-only Media","SC-34",0],
  ["SC-34(3)","Hardware-based Protection","SC-34",0],
  ["SC-35","External Malicious Code Identification",null,0],
  ["SC-36","Distributed Processing and Storage",null,0],
  ["SC-36(1)","Polling Techniques","SC-36",0],
  ["SC-36(2)","Synchronization","SC-36",0],
  ["SC-37","Out-of-band Channels",null,0],
  ["SC-37(1)","Ensure Delivery and Transmission","SC-37",0],
  ["SC-38","Operations Security",null,0],
  ["SC-39","Process Isolation",null,7],
  ["SC-39(1)","Hardware Separation","SC-39",0],
  ["SC-39(2)","Separate Execution Domain Per Thread","SC-39",0],
  ["SC-40","Wireless Link Protection",null,0],
  ["SC-40(1)","Electromagnetic Interference","SC-40",0],
  ["SC-40(2)","Reduce Detection Potential","SC-40",0],
  ["SC-40(3)","Imitative or Manipulative Communications Deception","SC-40",0],
  ["SC-40(4)","Signal Parameter Identification","SC-40",0],
  ["SC-41","Port and I/O Device Access",null,0],
  ["SC-42","Sensor Capability and Data",null,0],
  ["SC-42(1)","Reporting to Authorized Individuals or Roles","SC-42",0],
  ["SC-42(2)","Authorized Use","SC-42",0],
  ["SC-42(3)","Prohibit Use of Devices","SC-42",0],
  ["SC-42(4)","Notice of Collection","SC-42",0],
  ["SC-42(5)","Collection Minimization","SC-42",0],
  ["SC-43","Usage Restrictions",null,0],
  ["SC-44","Detonation Chambers",null,0],
  ["SC-45","System Time Synchronization",null,0],
  ["SC-45(1)","Synchronization with Authoritative Time Source","SC-45",0],
  ["SC-45(2)","Secondary Authoritative Time Source","SC-45",0],
  ["SC-46","Cross Domain Policy Enforcement",null,0],
  ["SC-47","Alternate Communications Paths",null,0],
  ["SC-48","Sensor Relocation",null,0],
  ["SC-48(1)","Dynamic Relocation of Sensors or Monitoring Capabilities","SC-48",0],
  ["SC-49","Hardware-enforced Separation and Policy Enforcement",null,0],
  ["SC-50","Software-enforced Separation and Policy Enforcement",null,0],
  ["SC-51","Hardware-based Protection",null,0],
  ["SI-1","Policy and Procedures",null,15],
  ["SI-2","Flaw Remediation",null,7],
  ["SI-2(1)","Central Management","SI-2",0],
  ["SI-2(2)","Automated Flaw Remediation Status","SI-2",6],
  ["SI-2(3)","Time to Remediate Flaws and Benchmarks for Corrective Actions","SI-2",0],
  ["SI-2(4)","Automated Patch Management Tools","SI-2",0],
  ["SI-2(5)","Automatic Software and Firmware Updates","SI-2",0],
  ["SI-2(6)","Removal of Previous Versions of Software and Firmware","SI-2",0],
  ["SI-2(7)","Root Cause Analysis","SI-2",0],
  ["SI-3","Malicious Code Protection",null,7],
  ["SI-3(1)","Central Management","SI-3",0],
  ["SI-3(2)","Automatic Updates","SI-3",0],
  ["SI-3(3)","Non-privileged Users","SI-3",0],
  ["SI-3(4)","Updates Only by Privileged Users","SI-3",0],
  ["SI-3(5)","Portable Storage Devices","SI-3",0],
  ["SI-3(6)","Testing and Verification","SI-3",0],
  ["SI-3(7)","Nonsignature-based Detection","SI-3",0],
  ["SI-3(8)","Detect Unauthorized Commands","SI-3",0],
  ["SI-3(9)","Authenticate Remote Commands","SI-3",0],
  ["SI-3(10)","Malicious Code Analysis","SI-3",0],
  ["SI-4","System Monitoring",null,7],
  ["SI-4(1)","System-wide Intrusion Detection System","SI-4",0],
  ["SI-4(2)","Automated Tools and Mechanisms for Real-time Analysis","SI-4",6],
  ["SI-4(3)","Automated Tool and Mechanism Integration","SI-4",0],
  ["SI-4(4)","Inbound and Outbound Communications Traffic","SI-4",6],
  ["SI-4(5)","System-generated Alerts","SI-4",6],
  ["SI-4(6)","Restrict Non-privileged Users","SI-4",0],
  ["SI-4(7)","Automated Response to Suspicious Events","SI-4",0],
  ["SI-4(8)","Protection of Monitoring Information","SI-4",0],
  ["SI-4(9)","Testing of Monitoring Tools and Mechanisms","SI-4",0],
  ["SI-4(10)","Visibility of Encrypted Communications","SI-4",4],
  ["SI-4(11)","Analyze Communications Traffic Anomalies","SI-4",0],
  ["SI-4(12)","Automated Organization-generated Alerts","SI-4",4],
  ["SI-4(13)","Analyze Traffic and Event Patterns","SI-4",0],
  ["SI-4(14)","Wireless Intrusion Detection","SI-4",4],
  ["SI-4(15)","Wireless to Wireline Communications","SI-4",0],
  ["SI-4(16)","Correlate Monitoring Information","SI-4",0],
  ["SI-4(17)","Integrated Situational Awareness","SI-4",0],
  ["SI-4(18)","Analyze Traffic and Covert Exfiltration","SI-4",0],
  ["SI-4(19)","Risk for Individuals","SI-4",0],
  ["SI-4(20)","Privileged Users","SI-4",4],
  ["SI-4(21)","Probationary Periods","SI-4",0],
  ["SI-4(22)","Unauthorized Network Services","SI-4",4],
  ["SI-4(23)","Host-based Devices","SI-4",0],
  ["SI-4(24)","Indicators of Compromise","SI-4",0],
  ["SI-4(25)","Optimize Network Traffic Analysis","SI-4",0],
  ["SI-5","Security Alerts, Advisories, and Directives",null,7],
  ["SI-5(1)","Automated Alerts and Advisories","SI-5",4],
  ["SI-6","Security and Privacy Function Verification",null,4],
  ["SI-6(1)","Notification of Failed Security Tests","SI-6",0],
  ["SI-6(2)","Automation Support for Distributed Testing","SI-6",0],
  ["SI-6(3)","Report Verification Results","SI-6",0],
  ["SI-7","Software, Firmware, and Information Integrity",null,6],
  ["SI-7(1)","Integrity Checks","SI-7",6],
  ["SI-7(2)","Automated Notifications of Integrity Violations","SI-7",4],
  ["SI-7(3)","Centrally Managed Integrity Tools","SI-7",0],
  ["SI-7(4)","Tamper-evident Packaging","SI-7",0],
  ["SI-7(5)","Automated Response to Integrity Violations","SI-7",4],
  ["SI-7(6)","Cryptographic Protection","SI-7",0],
  ["SI-7(7)","Integration of Detection and Response","SI-7",6],
  ["SI-7(8)","Auditing Capability for Significant Events","SI-7",0],
  ["SI-7(9)","Verify Boot Process","SI-7",0],
  ["SI-7(10)","Protection of Boot Firmware","SI-7",0],
  ["SI-7(11)","Confined Environments with Limited Privileges","SI-7",0],
  ["SI-7(12)","Integrity Verification","SI-7",0],
  ["SI-7(13)","Code Execution in Protected Environments","SI-7",0],
  ["SI-7(14)","Binary or Machine Executable Code","SI-7",0],
  ["SI-7(15)","Code Authentication","SI-7",4],
  ["SI-7(16)","Time Limit on Process Execution Without Supervision","SI-7",0],
  ["SI-7(17)","Runtime Application Self-protection","SI-7",0],
  ["SI-8","Spam Protection",null,6],
  ["SI-8(1)","Central Management","SI-8",0],
  ["SI-8(2)","Automatic Updates","SI-8",6],
  ["SI-8(3)","Continuous Learning Capability","SI-8",0],
  ["SI-9","Information Input Restrictions",null,0],
  ["SI-10","Information Input Validation",null,6],
  ["SI-10(1)","Manual Override Capability","SI-10",0],
  ["SI-10(2)","Review and Resolve Errors","SI-10",0],
  ["SI-10(3)","Predictable Behavior","SI-10",0],
  ["SI-10(4)","Timing Interactions","SI-10",0],
  ["SI-10(5)","Restrict Inputs to Trusted Sources and Approved Formats","SI-10",0],
  ["SI-10(6)","Injection Prevention","SI-10",0],
  ["SI-11","Error Handling",null,6],
  ["SI-12","Information Management and Retention",null,15],
  ["SI-12(1)","Limit Personally Identifiable Information Elements","SI-12",8],
  ["SI-12(2)","Minimize Personally Identifiable Information in Testing, Training, and Research","SI-12",8],
  ["SI-12(3)","Information Disposal","SI-12",8],
  ["SI-13","Predictable Failure Prevention",null,0],
  ["SI-13(1)","Transferring Component Responsibilities","SI-13",0],
  ["SI-13(2)","Time Limit on Process Execution Without Supervision","SI-13",0],
  ["SI-13(3)","Manual Transfer Between Components","SI-13",0],
  ["SI-13(4)","Standby Component Installation and Notification","SI-13",0],
  ["SI-13(5)","Failover Capability","SI-13",0],
  ["SI-14","Non-persistence",null,0],
  ["SI-14(1)","Refresh from Trusted Sources","SI-14",0],
  ["SI-14(2)","Non-persistent Information","SI-14",0],
  ["SI-14(3)","Non-persistent Connectivity","SI-14",0],
  ["SI-15","Information Output Filtering",null,0],
  ["SI-16","Memory Protection",null,6],
  ["SI-17","Fail-safe Procedures",null,0],
  ["SI-18","Personally Identifiable Information Quality Operations",null,8],
  ["SI-18(1)","Automation Support","SI-18",0],
  ["SI-18(2)","Data Tags","SI-18",0],
  ["SI-18(3)","Collection","SI-18",0],
  ["SI-18(4)","Individual Requests","SI-18",8],
  ["SI-18(5)","Notice of Correction or Deletion","SI-18",0],
  ["SI-19","De-identification",null,8],
  ["SI-19(1)","Collection","SI-19",0],
  ["SI-19(2)","Archiving","SI-19",0],
  ["SI-19(3)","Release","SI-19",0],
  ["SI-19(4)","Removal, Masking, Encryption, Hashing, or Replacement of Direct Identifiers","SI-19",0],
  ["SI-19(5)","Statistical Disclosure Control","SI-19",0],
  ["SI-19(6)","Differential Privacy","SI-19",0],
  ["SI-19(7)","Validated Algorithms and Software","SI-19",0],
  ["SI-19(8)","Motivated Intruder","SI-19",0],
  ["SI-20","Tainting",null,0],
  ["SI-21","Information Refresh",null,0],
  ["SI-22","Information Diversity",null,0],
  ["SI-23","Information Fragmentation",null,0],
  ["SR-1","Policy and Procedures",null,7],
  ["SR-2","Supply Chain Risk Management Plan",null,7],
  ["SR-2(1)","Establish SCRM Team","SR-2",7],
  ["SR-3","Supply Chain Controls and Processes",null,7],
  ["SR-3(1)","Diverse Supply Base","SR-3",0],
  ["SR-3(2)","Limitation of Harm","SR-3",0],
  ["SR-3(3)","Sub-tier Flow Down","SR-3",0],
  ["SR-4","Provenance",null,0],
  ["SR-4(1)","Identity","SR-4",0],
  ["SR-4(2)","Track and Trace","SR-4",0],
  ["SR-4(3)","Validate as Genuine and Not Altered","SR-4",0],
  ["SR-4(4)","Supply Chain Integrity — Pedigree","SR-4",0],
  ["SR-5","Acquisition Strategies, Tools, and Methods",null,7],
  ["SR-5(1)","Adequate Supply","SR-5",0],
  ["SR-5(2)","Assessments Prior to Selection, Acceptance, Modification, or Update","SR-5",0],
  ["SR-6","Supplier Assessments and Reviews",null,6],
  ["SR-6(1)","Testing and Analysis","SR-6",0],
  ["SR-7","Supply Chain Operations Security",null,0],
  ["SR-8","Notification Agreements",null,7],
  ["SR-9","Tamper Resistance and Detection",null,4],
  ["SR-9(1)","Multiple Stages of System Development Life Cycle","SR-9",4],
  ["SR-10","Inspection of Systems or Components",null,7],
  ["SR-11","Component Authenticity",null,7],
  ["SR-11(1)","Anti-counterfeit Training","SR-11",7],
  ["SR-11(2)","Configuration Control for Component Service and Repair","SR-11",7],
  ["SR-11(3)","Anti-counterfeit Scanning","SR-11",0],
  ["SR-12","Component Disposal",null,7],
];

/** Withdrawn in Rev. 5 — kept in the index so historic references still resolve. */
const withdrawn = new Set<string>("AC-2(10) AC-3(1) AC-3(6) AC-4(16) AC-4(18) AC-7(1) AC-13 AC-14(1) AC-15 AC-17(5) AC-17(7) AC-17(8) AC-18(2) AC-19(1) AC-19(2) AC-19(3) AT-3(4) AT-5 AU-2(1) AU-2(2) AU-2(3) AU-2(4) AU-3(2) AU-6(2) AU-6(10) AU-7(2) AU-8(1) AU-8(2) AU-10(5) AU-14(2) AU-15 CA-3(1) CA-3(2) CA-3(3) CA-3(4) CA-3(5) CA-4 CA-7(2) CM-2(1) CM-2(4) CM-2(5) CM-5(2) CM-5(3) CM-5(7) CM-6(3) CM-6(4) CM-8(5) CM-11(1) CP-2(4) CP-5 CP-7(5) CP-9(4) CP-10(1) CP-10(3) CP-10(5) IA-2(3) IA-2(4) IA-2(7) IA-2(9) IA-2(11) IA-3(2) IA-4(2) IA-4(3) IA-4(7) IA-5(3) IA-5(4) IA-5(11) IA-8(3) IA-9(1) IA-9(2) IR-9(1) IR-10 MA-2(1) MA-4(2) MP-2(1) MP-2(2) MP-4(1) MP-5(1) MP-5(2) MP-5(4) MP-6(4) MP-6(5) MP-6(6) MP-7(1) PE-3(6) PE-5(1) PE-5(3) PE-7 PE-8(2) PE-10(1) PE-13(3) PE-18(1) PL-2(1) PL-2(2) PL-2(3) PL-3 PL-5 PL-6 PS-6(1) RA-4 RA-5(1) RA-5(7) RA-5(9) SA-4(4) SA-5(1) SA-5(2) SA-5(3) SA-5(4) SA-5(5) SA-6 SA-7 SA-12 SA-12(1) SA-12(2) SA-12(3) SA-12(4) SA-12(5) SA-12(6) SA-12(7) SA-12(8) SA-12(9) SA-12(10) SA-12(11) SA-12(12) SA-12(13) SA-12(14) SA-12(15) SA-13 SA-14 SA-14(1) SA-15(4) SA-15(9) SA-18 SA-18(1) SA-18(2) SA-19 SA-19(1) SA-19(2) SA-19(3) SA-19(4) SA-21(1) SA-22(1) SC-4(1) SC-7(1) SC-7(2) SC-7(6) SC-9 SC-12(4) SC-12(5) SC-13(1) SC-13(2) SC-13(3) SC-13(4) SC-14 SC-15(2) SC-19 SC-20(1) SC-21(1) SC-23(2) SC-23(4) SC-26(1) SC-30(1) SC-33 SC-34(3) SC-42(3) SI-2(1) SI-3(1) SI-3(2) SI-3(3) SI-3(5) SI-3(7) SI-3(9) SI-4(6) SI-4(8) SI-6(1) SI-7(4) SI-7(11) SI-7(13) SI-7(14) SI-8(1) SI-9 SI-13(2)".split(" "));

const incorporatedInto = new Map<string, string[]>([["AC-2(10)",["AC-2"]],["AC-3(1)",["AC-6"]],["AC-3(6)",["MP-4","SC-28"]],["AC-4(16)",["AC-4"]],["AC-4(18)",["AC-16"]],["AC-7(1)",["AC-7"]],["AC-13",["AC-2","AU-6"]],["AC-14(1)",["AC-14"]],["AC-15",["MP-3"]],["AC-17(5)",["SI-4"]],["AC-17(7)",["AC-3(10)"]],["AC-17(8)",["CM-7"]],["AC-18(2)",["SI-4"]],["AC-19(1)",["MP-7"]],["AC-19(2)",["MP-7"]],["AC-19(3)",["MP-7"]],["AT-5",["PM-15"]],["AU-2(1)",["AU-12"]],["AU-2(2)",["AU-12"]],["AU-2(3)",["AU-2"]],["AU-2(4)",["AC-6(9)"]],["AU-3(2)",["PL-9"]],["AU-6(2)",["SI-4"]],["AU-6(10)",["AU-6"]],["AU-7(2)",["AU-7(1)"]],["AU-10(5)",["SI-7"]],["AU-14(2)",["AU-14"]],["CA-4",["CA-2"]],["CA-7(2)",["CA-2"]],["CM-2(1)",["CM-2"]],["CM-2(4)",["CM-7(4)"]],["CM-2(5)",["CM-7(5)"]],["CM-5(2)",["CM-3(7)"]],["CM-5(7)",["SI-7"]],["CM-6(3)",["SI-7"]],["CM-6(4)",["CM-4"]],["CM-8(5)",["CM-8"]],["CM-11(1)",["CM-8(3)"]],["CP-2(4)",["CP-2(3)"]],["CP-5",["CP-2"]],["CP-7(5)",["CP-7"]],["CP-9(4)",["CP-9"]],["CP-10(1)",["CP-4"]],["CP-10(5)",["SI-13"]],["IA-2(3)",["IA-2(1)"]],["IA-2(4)",["IA-2(2)"]],["IA-2(7)",["IA-2(6)"]],["IA-2(9)",["IA-2(8)"]],["IA-2(11)",["IA-2(6)"]],["IA-3(2)",["IA-3(1)"]],["IA-4(2)",["IA-12(1)"]],["IA-4(3)",["IA-12(2)"]],["IA-4(7)",["IA-12(4)"]],["IA-5(3)",["IA-12(4)"]],["IA-5(4)",["IA-5(1)"]],["IA-5(11)",["IA-2(1)","IA-2(2)"]],["IA-8(3)",["IA-8(2)"]],["IA-9(1)",["IA-9"]],["IA-9(2)",["IA-9"]],["IR-9(1)",["IR-9"]],["MA-2(1)",["MA-2"]],["MA-4(2)",["MA-1","MA-4"]],["MP-2(1)",["MP-4(2)"]],["MP-2(2)",["SC-28(1)"]],["MP-4(1)",["SC-28(1)"]],["MP-5(1)",["MP-5"]],["MP-5(2)",["MP-5"]],["MP-5(4)",["SC-28(1)"]],["MP-6(4)",["MP-6"]],["MP-6(5)",["MP-6"]],["MP-6(6)",["MP-6"]],["MP-7(1)",["MP-7"]],["PE-3(6)",["CA-8"]],["PE-5(1)",["PE-5"]],["PE-5(3)",["PE-22"]],["PE-7",["PE-2","PE-3"]],["PE-8(2)",["PE-2"]],["PE-10(1)",["PE-10"]],["PE-13(3)",["PE-13(2)"]],["PL-2(1)",["PL-7"]],["PL-2(2)",["PL-8"]],["PL-2(3)",["PL-2"]],["PL-3",["PL-2"]],["PL-5",["RA-8"]],["PL-6",["PL-2"]],["PS-6(1)",["PS-3"]],["RA-4",["RA-3"]],["RA-5(1)",["RA-5"]],["RA-5(7)",["CM-8"]],["RA-5(9)",["CA-8"]],["SA-4(4)",["CM-8(9)"]],["SA-5(1)",["SA-4(1)"]],["SA-5(2)",["SA-4(2)"]],["SA-5(3)",["SA-4(2)"]],["SA-5(4)",["SA-4(2)"]],["SA-5(5)",["SA-4(2)"]],["SA-6",["CM-10","SI-7"]],["SA-7",["CM-11","SI-7"]],["SA-12",["SR"]],["SA-12(3)",["SR-3"]],["SA-12(6)",["SR-5(1)"]],["SA-12(8)",["RA-3(2)"]],["SA-12(13)",["MA-6","RA-9"]],["SA-12(14)",["SR-4(1)","SR-4(2)"]],["SA-12(15)",["SR-3"]],["SA-13",["SA-8"]],["SA-14",["RA-9"]],["SA-14(1)",["SA-20"]],["SA-15(4)",["SA-11(2)"]],["SA-15(9)",["SA-3(2)"]],["SA-21(1)",["SA-21"]],["SA-22(1)",["SA-22"]],["SC-4(1)",["SC-4"]],["SC-7(1)",["SC-7"]],["SC-7(2)",["SC-7"]],["SC-7(6)",["SC-7(18)"]],["SC-9",["SC-8"]],["SC-12(4)",["SC-12(3)"]],["SC-12(5)",["SC-12(3)"]],["SC-13(1)",["SC-13"]],["SC-13(2)",["SC-13"]],["SC-13(3)",["SC-13"]],["SC-13(4)",["SC-13"]],["SC-14",["AC-2","AC-3","AC-5","AC-6","SI-3","SI-4","SI-5","SI-7","SI-10"]],["SC-15(2)",["SC-7"]],["SC-20(1)",["SC-20"]],["SC-21(1)",["SC-21"]],["SC-23(2)",["AC-12(1)"]],["SC-23(4)",["SC-23(3)"]],["SC-26(1)",["SC-35"]],["SC-30(1)",["SC-29(1)"]],["SC-33",["SC-8"]],["SC-42(3)",["SC-42"]],["SI-2(1)",["PL-9"]],["SI-3(1)",["PL-9"]],["SI-3(2)",["SI-3"]],["SI-3(3)",["AC-6(10)"]],["SI-3(5)",["MP-7"]],["SI-3(7)",["SI-3"]],["SI-4(6)",["AC-6(10)"]],["SI-4(8)",["SI-4"]],["SI-6(1)",["SI-6"]],["SI-7(4)",["SR-9"]],["SI-8(1)",["PL-9"]],["SI-9",["AC-2","AC-3","AC-5","AC-6"]],["SI-13(2)",["SI-7(16)"]]]);
const movedTo = new Map<string, string[]>([["AT-3(4)",["AT-2(4)"]],["AU-8(1)",["SC-45(1)"]],["AU-8(2)",["SC-45(2)"]],["AU-15",["AU-5(5)"]],["CA-3(1)",["SC-7(25)"]],["CA-3(2)",["SC-7(26)"]],["CA-3(3)",["SC-7(27)"]],["CA-3(4)",["SC-7(28)"]],["CA-3(5)",["SC-7(5)"]],["CM-5(3)",["CM-14"]],["IR-10",["IR-4(11)"]],["PE-18(1)",["PE-23"]],["SA-12(1)",["SR-5"]],["SA-12(2)",["SR-6"]],["SA-12(4)",["SR-3(1)"]],["SA-12(5)",["SR-3(2)"]],["SA-12(7)",["SR-5(2)"]],["SA-12(9)",["SR-7"]],["SA-12(10)",["SR-4(3)"]],["SA-12(11)",["SR-6(1)"]],["SA-12(12)",["SR-8"]],["SA-18",["SR-9"]],["SA-18(1)",["SR-9(1)"]],["SA-18(2)",["SR-10"]],["SA-19",["SR-11"]],["SA-19(1)",["SR-11(1)"]],["SA-19(2)",["SR-11(2)"]],["SA-19(3)",["SR-12"]],["SA-19(4)",["SR-11(3)"]],["SC-34(3)",["SC-51"]],["SI-3(9)",["AC-17(10)"]],["SI-7(11)",["CM-7(6)"]],["SI-7(13)",["CM-7(7)"]],["SI-7(14)",["CM-7(8)"]]]);

const baselineNames: NistBaseline[] = ["Low", "Moderate", "High", "Privacy"];
const baselinesByMask = new Map<number, NistBaseline[]>();

function baselinesFor(mask: number): NistBaseline[] {
  let hit = baselinesByMask.get(mask);
  if (!hit) {
    hit = baselineNames.filter((_, i) => (mask & (1 << i)) !== 0);
    Object.freeze(hit);
    baselinesByMask.set(mask, hit);
  }
  return hit;
}

const titleByIdRaw = new Map(catalogRows.map((r) => [r[0], r[1]]));

export const nistControls: NistControl[] = catalogRows.map(([id, title, parent, mask]) => {
  const row: NistControl = {
    id,
    family: id.slice(0, id.indexOf("-")),
    title,
    parent,
    parentTitle: parent ? (titleByIdRaw.get(parent) ?? null) : null,
    baselines: baselinesFor(mask),
  };
  if (withdrawn.has(id)) row.withdrawn = true;
  const into = incorporatedInto.get(id);
  if (into) row.incorporatedInto = into;
  const moved = movedTo.get(id);
  if (moved) row.movedTo = moved;
  return row;
});

export const nistControlById = new Map(nistControls.map((c) => [c.id, c]));

const baselineCache = new Map<NistBaseline, NistControl[]>();

/** The SP 800-53B baseline for an impact level, in catalog order. */
export function baselineControls(level: NistBaseline): NistControl[] {
  const hit = baselineCache.get(level);
  if (hit) return hit;
  const rows = nistControls.filter((c) => c.baselines.includes(level));
  baselineCache.set(level, rows);
  return rows;
}

/** "Account Management | Disable Accounts" — how a control reads in an RMF tool. */
export function controlTitle(c: NistControl): string {
  return c.parentTitle ? `${c.parentTitle} | ${c.title}` : c.title;
}

/** Title for a bare id, falling back to the id itself. */
export function titleOf(id: string): string {
  const c = nistControlById.get(id);
  return c ? controlTitle(c) : id;
}
