import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

import ledger from "./packages/design-system/eslint-plugin/index.js";

const SERVER_ONLY = {
  name: "server-only",
  message:
    "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
};

const REFERENCE_KITS = [
  {
    group: ["@/ds", "@/ds/*"],
    message: "The kit is @ledger/design-system; the product shell is @/components/app/shell.",
  },
  {
    group: [
      "@/components/app/ui",
      "@/components/app/shapes",
      "@/components/app/compositions",
      "@/components/ui/*",
      "@/components/reui/*",
    ],
    message: "Product code imports the kit from @ledger/design-system, not a reference kit.",
  },
];

// Domain code never imports the UI: src/lib holds data access, commands and rules that screens
// compose. The workspace context is the one named exception until it moves into src/lib.
const DOMAIN_NEVER_IMPORTS_UI = {
  regex:
    "^(@ledger/design-system(/.*)?|@/components(/(?!app/workspace$).*)?|@/routes(/.*)?|react-dom(/.*)?)$",
  message:
    "src/lib is domain code and never imports the UI. Move the rendering into src/components or src/routes and keep the rule, hook or command here.",
};

// The product: routes, app components, domain code and the router. Reference kits are not the product.
const PRODUCT = [
  "src/routes/**/*.{ts,tsx}",
  "src/components/app/**/*.{ts,tsx}",
  "src/components/prototype/**/*.{ts,tsx}",
  "src/lib/**/*.{ts,tsx}",
  "src/router.tsx",
];

export default tseslint.config(
  {
    ignores: [
      // @ledger/design-system lints itself with its own preset (npm run lint in packages/design-system)
      "packages",
      "dist",
      ".output",
      ".vinxi",
      "storybook-static",
      "artifacts",
      ".playwright-mcp",
      // gitignored output; not source
      ".wrangler",
      ".tanstack",
      ".nitro",
      "Program Assurance UI Kit",
      "docs/examples",
      "tests/fixtures",
      "docs/examples.superpowers",
      // generated by scripts/gen-nist-catalog.mjs from the NIST OSCAL release
      "src/lib/nist-catalog.ts",
      "src/lib/nist-control-text.ts",
      "src/lib/nist-control-text",
      "src/lib/nist-baselines.ts",
      "src/lib/cnssi-1253.ts",
      "src/lib/cci-catalog.ts",
      "src/lib/cci-text",
      // look-only reference kits (shadcn preset, reui) and their samples; not the product and not on the tokens
      "src/components/ui",
      "src/components/reui",
      "src/components/examples",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [SERVER_ONLY],
          patterns: REFERENCE_KITS,
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // Product layout defaults are stricter than the kit's generic component variants.
    files: PRODUCT,
    extends: ledger.configs.recommended,
    rules: {
      "ledger/product-responsive-table": "error",
      "ledger/product-line-tabs": "error",
    },
  },
  {
    files: ["src/lib/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        { paths: [SERVER_ONLY], patterns: [...REFERENCE_KITS, DOMAIN_NEVER_IMPORTS_UI] },
      ],
    },
  },
  {
    // The product shell composes the package's Shell parts and keeps the name; it is the one intentional shadow.
    files: ["src/components/app/shell.tsx"],
    rules: { "ledger/no-kit-shadow": "off" },
  },
  eslintPluginPrettier,
);
