import { readFileSync } from "node:fs";

import js from "@eslint/js";
// Prettier runs as its own step (npm run format:check); this only turns off rules that would fight it.
import eslintConfigPrettier from "eslint-config-prettier/flat";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

import ledger from "./packages/design-system/eslint-plugin/index.js";

const SERVER_ONLY = {
  name: "server-only",
  message:
    "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
};

const REFERENCE_KITS = [
  {
    group: ["@/ds", "@/ds/*"],
    message: "The kit is @ledger/design-system; the product shell is @/components/app/shell.",
  },
  {
    group: [
      "@/components/app/ui",
      "@/components/app/shapes",
      "@/components/app/compositions",
      "@/components/ui/*",
      "@/components/reui/*",
      // Lint-ignored like the kits, so an import from it would bring unlinted styling into a screen.
      "@/components/examples",
      "@/components/examples/*",
    ],
    message: "Product code imports the kit from @ledger/design-system, not a reference kit.",
  },
  {
    // The same lint-ignored folders by any other spelling: the bare folder (`@/components/ui`), a
    // relative path (`../ui/button`) or one that climbs back into src/components.
    regex: String.raw`(^|/)components/(ui|reui|examples)(/|$)|^\.\.?/(\.\./)*(ui|reui|examples)(/|$)`,
    message: "Product code imports the kit from @ledger/design-system, not a reference kit.",
  },
];

// Domain code never imports the UI: src/lib holds data access, commands and rules that screens
// compose. The workspace context is the one named exception until it moves into src/lib.
const DOMAIN_NEVER_IMPORTS_UI = {
  regex:
    "^(@ledger/design-system(/.*)?|@/components(/(?!app/workspace$).*)?|@/routes(/.*)?|react-dom(/.*)?)$",
  message:
    "src/lib is domain code and never imports the UI. Move the rendering into src/components or src/routes and keep the rule, hook or command here.",
};

// Product sites that predate a rule, counted per rule and file; the counts may only shrink.
const PRODUCT_ALLOW = JSON.parse(
  readFileSync(new URL("./scripts/lint-allow.json", import.meta.url), "utf8"),
);
/** A rule at `severity`, with the product's allowance for it and any other options it takes. */
const allowing = (name, severity = "error", extra = {}) => {
  const options = { ...(PRODUCT_ALLOW[name] ? { allow: PRODUCT_ALLOW[name] } : {}), ...extra };
  return Object.keys(options).length ? [severity, options] : severity;
};

// Where the kit's advice names a generic part and this app has its own, each finding of the rule
// ends with the app's part (the rule's `note` option).
const RECORD_LINK = "A record's name is RecordLink (src/components/prototype/record-preview.tsx).";
const NOTES = {
  "ledger/no-native-confirm": "In this app: useConfirmation (src/components/app/confirmation.tsx).",
  "ledger/no-kit-shadow":
    "In this app a status is StatusBadge and a level LevelIndicator (src/components/app/status.tsx).",
  "ledger/no-plain-alert-role":
    "In this app: useFormFeedback (src/components/app/form-feedback.ts).",
  "ledger/prefer-text-link": RECORD_LINK,
  "ledger/text-link-navigation": RECORD_LINK,
};

// The product: routes, app components, domain code and the router. Reference kits are not the product.
const PRODUCT = [
  "src/routes/**/*.{ts,tsx}",
  "src/components/app/**/*.{ts,tsx}",
  "src/components/prototype/**/*.{ts,tsx}",
  "src/lib/**/*.{ts,tsx}",
  "src/router.tsx",
];

export default tseslint.config(
  {
    ignores: [
      // @ledger/design-system lints itself with its own preset (npm run lint in packages/design-system)
      "packages",
      "dist",
      ".output",
      ".vinxi",
      "storybook-static",
      "artifacts",
      ".playwright-mcp",
      // gitignored output; not source
      ".wrangler",
      ".tanstack",
      ".nitro",
      "Program Assurance UI Kit",
      "docs/examples",
      "tests/fixtures",
      "docs/examples.superpowers",
      // agent eval output (npm run eval:lint): what eval agents wrote, violations by design
      "evals/results",
      // generated by scripts/gen-nist-catalog.mjs from the NIST OSCAL release
      "src/lib/nist-catalog.ts",
      "src/lib/nist-control-text.ts",
      "src/lib/nist-control-text",
      "src/lib/nist-baselines.ts",
      "src/lib/cnssi-1253.ts",
      "src/lib/cci-catalog.ts",
      "src/lib/cci-text",
      // look-only reference kits (shadcn preset, reui) and their samples; not the product and not on the tokens
      "src/components/ui",
      "src/components/reui",
      "src/components/examples",
    ],
  },
  {
    // A disable that silences nothing fails the run, so a fixed site loses its comment with its fix.
    linterOptions: { reportUnusedDisableDirectives: "error" },
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [SERVER_ONLY],
          patterns: REFERENCE_KITS,
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // Product layout defaults are stricter than the kit's generic component variants.
    files: PRODUCT,
    extends: ledger.configs.recommended,
    rules: {
      "ledger/product-responsive-table": "error",
      "ledger/product-line-tabs": "error",
      // The preset warns; this product holds layout to the primitives and their props (TOO-13).
      "ledger/use-primitives": allowing("ledger/use-primitives"),
      ...Object.fromEntries(
        Object.entries(NOTES).map(([name, note]) => [name, allowing(name, "error", { note })]),
      ),
    },
  },
  {
    files: ["src/lib/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        { paths: [SERVER_ONLY], patterns: [...REFERENCE_KITS, DOMAIN_NEVER_IMPORTS_UI] },
      ],
    },
  },
  eslintConfigPrettier,
);
