import { createFileRoute, Link, notFound, useNavigate } from "@tanstack/react-router";
import { useMemo, useState } from "react";

import {
  BundleManifest,
  DownloadButton,
  EmassTable,
  OscalViewer,
  ReconcileTable,
  ReconcileVerdict,
  downloadText,
} from "@/components/app/export";
import {
  Badge,
  Box,
  Breadcrumb,
  Empty,
  Id,
  Inline,
  RecordHeader,
  Section,
  Select,
  ShowPage,
  Stack,
  Tabs,
  TextLink,
  Toolbar,
} from "@ledger/design-system";
import { Shell } from "@/components/app/shell";
import {
  bundleArtifactText,
  bundleManifest,
  buildBundle,
  digestAlgorithm,
  receivedBundlesFor,
  reconcile,
} from "@/lib/airgap";
import {
  emassCsv,
  emassExportFor,
  emassExportKinds,
  emassFileNames,
  type EmassExportKind,
} from "@/lib/emass";
import { programs } from "@/lib/grc-data";
import {
  oscalAssessmentPlan,
  oscalAssessmentResults,
  oscalJson,
  oscalModelLabels,
  oscalModels,
  oscalPoam,
  oscalSsp,
  oscalVersion,
  type OscalDocument,
  type OscalModel,
} from "@/lib/oscal";
import { useSctm, type SctmRow } from "@/lib/sctm";

const exportTabs = ["OSCAL", "eMASS", "Air-gap bundle", "Reconciliation"] as const;
type ExportTab = (typeof exportTabs)[number];

/**
 * The export basis is the published-requirement row set — one row per DISA CCI
 * where the catalog publishes one and one per control otherwise — which is why
 * this route does NOT pull in the 1.25 MB 800-53A objective text the SCTM page
 * loads dynamically.
 *
 * That is a deliberate choice about the artifacts, not a shortcut. eMASS
 * Control Information is a per-control/per-AP sheet and has no column that an
 * assessment-objective row could fill, so expanding to objectives would inflate
 * the sheet by roughly four rows for every one without adding a single eMASS
 * field. The same rows feed the OSCAL documents and the transfer bundle, and
 * the far-side bundle this page reconciles against was exported on the same
 * basis: swapping bases here would make every line of two artifacts differ and
 * bury the real two-determination difference the reconciliation exists to
 * surface.
 *
 * A comment is not a disclosure, though. The SCTM page rows per assessment
 * objective and publishes a larger total for the same controls, and this page
 * links straight to it, so the basis is stated on screen in the header strip
 * below the title — counted off the exported rows, never called "the matrix",
 * and never a figure hardcoded here.
 */
const oscalDocumentFor = (model: OscalModel, programId: string, rows: SctmRow[]): OscalDocument => {
  switch (model) {
    case "system-security-plan":
      return oscalSsp(programId, rows);
    case "assessment-plan":
      return oscalAssessmentPlan(programId);
    case "assessment-results":
      return oscalAssessmentResults(programId, rows);
    default:
      return oscalPoam(programId);
  }
};

export const Route = createFileRoute("/programs/$programId_/export")({
  // The router MERGES the validated object over the raw parsed search rather
  // than replacing it, so omitting `tab` on a miss would leave `?tab=Bogus`
  // intact and the `?? "OSCAL"` fallback below would never fire. Emitting the
  // key explicitly, as `undefined`, is what deletes it; `| undefined` in the
  // return type is load-bearing under `exactOptionalPropertyTypes`.
  validateSearch: (search: Record<string, unknown>): { tab?: ExportTab | undefined } => {
    const raw = String(search["tab"] ?? "");
    const match = exportTabs.find((t) => t.toLowerCase() === raw.toLowerCase());
    return { tab: match };
  },
  loader: ({ params }) => {
    const program = programs.find((p) => p.id.toLowerCase() === params.programId.toLowerCase());
    if (!program) throw notFound();
    return program;
  },
  head: ({ loaderData }) => {
    const name = loaderData?.name ?? "Program";
    const title = `${name} export and transfer — Equinox`;
    const description = `OSCAL ${oscalVersion}, eMASS and cross-domain transfer artifacts for ${
      loaderData?.id ?? "the program"
    }: the real JSON and CSV an assessor would import, a manifest whose digests are computed from the generated bytes, and a path-by-path reconciliation against what arrived on the media.`;
    return {
      meta: [
        { title },
        { name: "description", content: description },
        { property: "og:title", content: title },
        {
          property: "og:description",
          content:
            "Nothing leaves an air-gapped enclave by API. It leaves as files with a manifest, and the receiving side has to decide whether what arrived is what was sent.",
        },
        { property: "og:type", content: "website" },
        { name: "twitter:card", content: "summary_large_image" },
      ],
    };
  },
  component: ProgramExport,
});

function ProgramExport() {
  const { programId } = Route.useParams();
  const program = Route.useLoaderData();
  const tab = Route.useSearch().tab ?? "OSCAL";
  const navigate = useNavigate({ from: Route.fullPath });

  const sctm = useSctm(program.id, null);
  const rows = sctm.rows;

  // What a "requirement row" is on this page, counted off the rows that are
  // actually exported rather than asserted in prose. The header strip prints
  // it, because the SCTM link two elements away leads to a page that counts
  // the same controls per 800-53A objective and reports a larger total.
  const basis = useMemo(() => {
    const controls = new Set<string>();
    const cciControls = new Set<string>();
    let cciRows = 0;
    for (const row of rows) {
      controls.add(row.control);
      if (row.unit === "CCI") {
        cciRows += 1;
        cciControls.add(row.control);
      }
    }
    return {
      controls: controls.size,
      cciRows,
      cciControls: cciControls.size,
      controlRows: rows.length - cciRows,
    };
  }, [rows]);

  const [model, setModel] = useState<OscalModel>("system-security-plan");
  const [sheetKind, setSheetKind] = useState<EmassExportKind>("Control Information");
  const [receivedId, setReceivedId] = useState<string | null>(null);

  // Each artifact set is generated only for the tab that shows it. The SSP
  // alone serialises to megabytes — the viewer prints the exact byte count it
  // measures rather than any figure named here — and the bundle hashes every
  // artifact it holds; neither is work to do for a tab nobody is looking at.
  const doc = useMemo(
    () => (tab === "OSCAL" ? oscalDocumentFor(model, program.id, rows) : null),
    [tab, model, program.id, rows],
  );
  const json = useMemo(() => (doc ? oscalJson(doc) : ""), [doc]);

  const sheet = useMemo(
    () => (tab === "eMASS" ? emassExportFor(sheetKind, program.id, rows) : null),
    [tab, sheetKind, program.id, rows],
  );
  const sheetCsv = useMemo(() => (sheet ? emassCsv(sheet) : ""), [sheet]);

  const needsBundle = tab === "Air-gap bundle" || tab === "Reconciliation";
  const bundle = useMemo(
    () => (needsBundle ? buildBundle(program.id, rows) : null),
    [needsBundle, program.id, rows],
  );
  const manifest = useMemo(() => (bundle ? bundleManifest(bundle) : ""), [bundle]);

  const received = useMemo(() => receivedBundlesFor(program.id), [program.id]);
  const activeReceived = received.find((b) => b.id === receivedId) ?? received[0] ?? null;
  const reconciliation = useMemo(
    () => (bundle && activeReceived ? reconcile(bundle.id, activeReceived.id) : null),
    [bundle, activeReceived],
  );

  const slug = program.id.toLowerCase();

  // The bundle is only assembled for the tabs that show it, so its artifact
  // count would appear and disappear as the reader moves between tabs. The
  // count that belongs on a tab strip is one that is always true: the bundle's
  // own header states its artifact count and total bytes.
  const counts: Record<ExportTab, number | null> = {
    OSCAL: oscalModels.length,
    eMASS: emassExportKinds.length,
    "Air-gap bundle": null,
    Reconciliation: received.length,
  };

  return (
    <Shell>
      <ShowPage
        header={
          <RecordHeader
            back={<Link to="/programs/$programId" params={{ programId }} />}
            breadcrumb={
              <Breadcrumb>
                <Breadcrumb.Item asChild>
                  <Link to={"/programs"}>{"Programs"}</Link>
                </Breadcrumb.Item>
                <Breadcrumb.Item asChild>
                  <Link to={"/programs/$programId"} params={{ programId: program.id }}>
                    {program.name}
                  </Link>
                </Breadcrumb.Item>
                <Breadcrumb.Item isCurrent>{"Export and transfer"}</Breadcrumb.Item>
              </Breadcrumb>
            }
            id={program.id}
            title="Export and cross-domain transfer"
            meta={`${program.acronym} · OSCAL ${oscalVersion} · eMASS sheets · generated ${sctm.generated}`}
            actions={
              <>
                <Badge tone="neutral">{sctm.counts.total} exported requirement rows</Badge>
                <TextLink size="medium">
                  <Link to="/programs/$programId/sctm" params={{ programId }}>
                    Open SCTM →
                  </Link>
                </TextLink>
              </>
            }
            below={
              <p className="max-w-layout-measure font-body-small text-subtle">
                <span className="font-medium text-default">Export basis.</span> Every artifact on
                this page is generated from the same {sctm.counts.total} exported requirement rows,
                covering {basis.controls} controls: {basis.cciRows} rows keyed to a DISA CCI across{" "}
                {basis.cciControls} controls, and one row each for the {basis.controlRows} controls
                the catalog publishes no CCI for. The SCTM page rows those same controls per 800-53A
                assessment objective and so reports a larger total — a different unit, not a
                different program. That basis is not used here because eMASS Control Information is
                a per-control sheet with no column an objective row could fill, and the media
                reconciled below was written on the row set above, so switching would make every
                line of both manifests differ and bury the two-determination difference the
                reconciliation exists to surface.
              </p>
            }
          />
        }
        tabs={
          <Tabs>
            {exportTabs.map((t) => (
              <Tabs.Tab
                key={t}
                isSelected={t === tab}
                onClick={() => navigate({ search: { tab: t }, replace: true })}
                count={counts[t]}
              >
                {t}
              </Tabs.Tab>
            ))}
          </Tabs>
        }
      >
        {tab === "OSCAL" && doc ? (
          <Section
            title={`OSCAL ${oscalVersion} documents`}
            description="Four models, generated from the same record the pages elsewhere in this program render: the SSP from the control matrix and composition graph, the assessment plan from the T&E phases, the results from the findings and the residual-risk trail, and the POA&M from the register. Every uuid is a deterministic RFC 4122 v5 over a stable seed, so a re-export is byte-identical and an importer sees the same document rather than a new one."
          >
            <Toolbar
              actions={
                <span className="font-body-small text-subtle">
                  Import target: any OSCAL {oscalVersion} consumer
                </span>
              }
            >
              <Select
                value={model}
                onValueChange={(v) => setModel(v as OscalModel)}
                aria-label="OSCAL model"
                width={268}
              >
                {oscalModels.map((m) => (
                  <Select.Item key={m} value={m}>
                    {oscalModelLabels[m]}
                  </Select.Item>
                ))}
              </Select>
            </Toolbar>

            <Box paddingBlockStart="space.100">
              <OscalViewer
                doc={doc}
                text={json}
                label={oscalModelLabels[doc.model]}
                filename={`${slug}-${doc.model}.json`}
              />
            </Box>
          </Section>
        ) : null}

        {tab === "eMASS" && sheet ? (
          <Section
            title="eMASS import sheets"
            description="The five sheets an eMASS operator uploads, with eMASS's own column names. Every cell is derived from the record — a value this dataset does not carry is the em dash rather than a plausible-looking invention, because a fabricated serial number is worse than a blank one."
            action={
              <DownloadButton
                filename={`${slug}-${emassFileNames[sheet.kind]}`}
                text={sheetCsv}
                mime="text/csv;charset=utf-8"
                label="Download CSV"
                variant="primary"
              />
            }
          >
            <Toolbar
              actions={
                <span className="font-body-small text-subtle">RFC 4180, CRLF line endings</span>
              }
            >
              <Select
                value={sheetKind}
                onValueChange={(v) => setSheetKind(v as EmassExportKind)}
                aria-label="eMASS sheet"
                width={224}
              >
                {emassExportKinds.map((kind) => (
                  <Select.Item key={kind} value={kind}>
                    {kind}
                  </Select.Item>
                ))}
              </Select>
            </Toolbar>

            <Box paddingBlockStart="space.100">
              <EmassTable key={sheet.kind} sheet={sheet} />
            </Box>
          </Section>
        ) : null}

        {tab === "Air-gap bundle" && bundle ? (
          <Section
            title="Outbound transfer bundle"
            description="What is written to the write-once media, and the manifest that travels with it. The digests below are computed from the generated bytes at the moment the bundle is assembled; because every input is derived and no clock or random value is read, assembling it again reproduces the same manifest and the same manifest digest."
            action={
              <DownloadButton
                filename={`${slug}-${bundle.id.toLowerCase()}-manifest.txt`}
                text={manifest}
                mime="text/plain;charset=utf-8"
                label="Download manifest"
                variant="primary"
              />
            }
          >
            <Box paddingBlockStart="space.150">
              <BundleManifest
                bundle={bundle}
                manifest={manifest}
                onDownloadArtifact={(artifact) => {
                  const text = bundleArtifactText(bundle.id, artifact.path);
                  if (text === null) return;
                  const name = artifact.path.split("/").pop() ?? artifact.path;
                  downloadText(
                    `${slug}-${name}`,
                    text,
                    name.endsWith(".json")
                      ? "application/json;charset=utf-8"
                      : name.endsWith(".csv")
                        ? "text/csv;charset=utf-8"
                        : "text/plain;charset=utf-8",
                  );
                }}
              />
            </Box>
          </Section>
        ) : null}

        {tab === "Reconciliation" ? (
          reconciliation && activeReceived && bundle ? (
            <Section
              title="Received media against what this side generates"
              description={`Every path on either manifest, compared by ${digestAlgorithm}. The verdict is what a receiving ISSM acts on; the rows underneath are the comparison it rests on, down to the first differing line of each artifact this side also holds.`}
              action={
                received.length > 1 ? (
                  <Select
                    width={200}
                    value={activeReceived.id}
                    onValueChange={setReceivedId}
                    aria-label="Received media"
                  >
                    {received.map((b) => (
                      <Select.Item key={b.id} value={b.id}>
                        {b.id} · {b.created}
                      </Select.Item>
                    ))}
                  </Select>
                ) : (
                  <span className="font-body-small text-subtle">
                    Media created {activeReceived.created}
                  </span>
                )
              }
            >
              <Stack className="pt-150" space="space.200">
                <ReconcileVerdict reconciliation={reconciliation} />

                <Inline
                  className="font-body-small"
                  space="space.400"
                  rowSpace="space.100"
                  shouldWrap
                >
                  <span>
                    <span className="text-subtle">Received bundle</span>{" "}
                    <Id>{activeReceived.id}</Id>
                  </span>
                  <span>
                    <span className="text-subtle">From</span> {activeReceived.createdBy}
                  </span>
                  <span>
                    <span className="text-subtle">Baseline</span> <Id>{activeReceived.build}</Id>
                  </span>
                  <span>
                    <span className="text-subtle">Local bundle</span> <Id>{bundle.id}</Id>
                  </span>
                </Inline>

                <p className="font-body-small text-subtle">{activeReceived.note}</p>

                <ReconcileTable reconciliation={reconciliation} />
              </Stack>
            </Section>
          ) : (
            <Section
              title="Received media"
              description="Reconciliation compares a manifest that arrived on media against the bundle this side generates, path by path."
            >
              <Box paddingBlockStart="space.150">
                <Empty
                  title={`No media has been received for ${program.id}`}
                  description="When a bundle arrives from the far side, its manifest is registered here and every path on either side is compared by digest — identical, changed, present only here, or present only on the media — with the manifest's own digest re-derived rather than trusted."
                />
              </Box>
            </Section>
          )
        ) : null}
      </ShowPage>
    </Shell>
  );
}
