/** Fictional, scoped assurance records for the product-model design study. */
import type { AssuranceObject, ObjectControl, Requirement, Evidence, Program, ProgramInstance, ProfileAssignment, DecisionMap } from './assurance-model';
import { controls as definitions } from './vision-data';
export const controls = definitions;

type Row = [id: string, status: ObjectControl['status'], implementation: string, responsibility?: string, contributions?: ObjectControl['contributions']];
type Req = [suffix: string, title: string, controlIds: string[], status: Requirement['status'], evidenceSuffixes: string[]];
type Proof = [suffix: string, title: string, kind: string, scope: string];
type Spec = Omit<AssuranceObject, 'controls' | 'requirements' | 'evidence' | 'assessments'> & { prefix: string; rows: Row[]; reqs: Req[]; proofs: Proof[]; assessmentDate: string; assessmentNote: string };
const localResponsibilities: Record<string, string> = {
  'AU-1': 'Name the consuming program’s audit owner and record local procedures.',
  'AU-2': 'Approve the deployed event selection and verify application-specific events.',
  'AU-3': 'Verify time and identity correlation across the consuming system.',
  'AU-6': 'Assign reviewers and exercise the local escalation route.',
  'AU-9': 'Confirm custody and permissions for every deployed audit destination.',
  'AU-12': 'Verify end-to-end generation under the intended workload.',
  'AC-2': 'Inventory deployed accounts and approve their sponsors.',
  'AC-3': 'Approve the deployed authorization matrix and interface permissions.',
  'AC-6': 'Review actual user and service privileges in the deployed configuration.',
  'IA-2': 'Verify authentication paths and disconnected-operation exceptions.',
  'IA-5': 'Assign credential custodians and confirm local recovery procedures.',
  'CM-2': 'Record the installed version, serial identities, and approved deviations.',
  'CM-3': 'Identify the program change authority and retain deployment decisions.',
  'CM-6': 'Verify effective settings against the selected product configuration.',
  'SI-2': 'Review applicable advisories and approve the program remediation schedule.',
  'SI-3': 'Verify that the deployed software set remains inside the assessed scope.',
  'SI-7': 'Confirm production trust anchors and installed image signatures.',
  'SC-8': 'Verify endpoints, routing, and protection beyond the product boundary.',
  'SC-12': 'Define operational key ownership, provisioning, and recovery.',
  'SC-13': 'Confirm the selected operating mode and consuming-system requirements.',
  'CA-2': 'Determine which master findings apply and assess the remaining local scope.',
  'CA-7': 'Name local monitoring owners and review product changes.',
  'IR-4': 'Exercise mission-safe containment and the provider handoff.',
  'IR-6': 'Validate the program’s incident contacts and reporting route.',
  'CP-9': 'Decide which deployed state and mission data require backup.',
  'CP-10': 'Demonstrate restoration using the actual deployment configuration.',
};
const ref = (objectId: string, controlId: string, note: string) => ({objectId, controlId, note});
function record(spec: Spec): AssuranceObject {
  const {prefix, rows, reqs, proofs, assessmentDate, assessmentNote, ...base} = spec;
  const evidence: Evidence[] = proofs.map(([suffix, title, kind, scope]) => ({id:`${prefix}-E-${suffix}`, title, kind, scope, date:assessmentDate}));
  const requirements: Requirement[] = reqs.map(([suffix,title,controlIds,status,evidenceSuffixes]) => ({id:`${prefix}-${suffix}`,title,controlIds,status,evidenceIds:evidenceSuffixes.map(id=>`${prefix}-E-${id}`)}));
  return {...base, evidence, requirements, controls:rows.map(([id,status,implementation,responsibility,contributions=[]]) => {
    const mapped = requirements.filter(requirement=>requirement.controlIds.includes(id));
    return {id, status, applicability:status==='Not applicable'?'Not applicable':'Applicable', implementation,
      responsibility: responsibility ?? localResponsibilities[id] ?? 'Confirm applicability for the consuming context.',
      rationale:status==='Satisfied' ? `Assessed within the ${base.name} ${base.version} boundary; consumer conditions still apply.` : status==='Partial' ? 'Implemented portions are supported; the stated remaining responsibility prevents a complete conclusion.' : status==='Not applicable' ? implementation : 'No assessment conclusion has been recorded for this scope.',
      requirementIds:mapped.map(item=>item.id),
      evidenceIds:status==='Not assessed'||status==='Not applicable'?[]:[...new Set(mapped.flatMap(item=>item.evidenceIds).concat(`${prefix}-E-01`))], contributions};
  }), assessments:[
    {id:`${prefix}-AS-02`,date:assessmentDate,assessor:'Independent Assurance',scope:`${base.name} v${base.version}`,result:'Complete',note:assessmentNote},
    {id:`${prefix}-AS-01`,date:'2026-04-16',assessor:base.owner,scope:'Scope and applicability review',result:'Complete',note:'Scope approved.'},
  ]};
}
export const objects: AssuranceObject[] = [
record({id:'system-a', name:'System A',version:'1.0',kind:'System',owner:'Integrated Products',prefix:'SYSA',
 
 
 conditions:['Qualified assembly: A.1 v2.1 and A.2 v1.4.','Program confirms host attachment, mission event selection, and operational roles.'],
 children:[{slot:'A.1',objectId:'subsystem-a1',label:'Mission processing'},{slot:'A.2',objectId:'subsystem-a2',label:'Communications'}],consumers:['alpha'],
 assessmentDate:'2026-08-25',assessmentNote:"Open findings: event selection, audit custody, recovery.",
 proofs:[['01','System A 1.0 assessment report','Assessment report','System-level interfaces and integration claims'],['02','Integrated event-path test','Integration test','Event delivery from A.1 and A.2 to system collector'],['03','System configuration and interface index','Baseline record','Approved subsystem versions, interfaces, and settings'],['04','Recovery and offload finding register','Finding record','Open system-level integration responsibilities']],
 reqs:[['LOG-01','Correlate security events from both subsystems.',['AU-2','AU-3','AU-12'],'Open',['02']],['INT-04','Enforce only approved inter-subsystem flows.',['AC-3','SC-8'],'Verified',['01','03']],['CFG-02','Identify all installed subsystem and firmware baselines.',['CM-2','CM-6','SI-7'],'Verified',['03']],['REC-03','Restore an approved system image and verify retained state.',['CP-9','CP-10'],'Open',['04']],['INT-099','The attachment adapter shall identify the connected host configuration.',[],'Open',['03']]],
 rows:[
 ['AU-1','Partial','The system audit procedure allocates product responsibilities; operational review roles belong to the consumer.'],
 ['AU-2','Partial','The system event dictionary incorporates compute and gateway events. Cross-subsystem event selection remains open.','Approve the integrated event dictionary and demonstrate mission-event coverage.',[ref('subsystem-a1','AU-2','Processing event dictionary supports the compute portion.'),ref('subsystem-a2','AU-2','Gateway events support the communications portion.')]],
 ['AU-3','Partial','Both subsystems emit actor and outcome fields; synchronization to the chosen host is unverified.'],
 ['AU-6','Not assessed','A review workflow is specified, but operational review has not been exercised.'],
 ['AU-9','Partial','Local audit buffers are protected. Custody after external offload awaits the host agreement.'],
 ['AU-12','Satisfied','Integration tests demonstrate selected reference events crossing both subsystem paths.'],
 ['AC-2','Partial','Product maintenance accounts are inventoried; deployed account sponsorship remains open.'],
 ['AC-3','Satisfied','The integration policy permits only declared A.1-to-A.2 interfaces.'],
 ['AC-6','Satisfied','Reference service roles have distinct maintenance and mission privileges.'],
 ['IA-2','Partial','Maintenance identity handoff is implemented; the selected host binding requires verification.'],
 ['IA-5','Partial','Credential storage is defined; the operational issuance authority is outside the product.'],
 ['CM-2','Satisfied','The release index pins A.1 v2.1 and A.2 v1.4, including their nested component versions.'],
 ['CM-3','Satisfied','The product change board reviews security impact for the complete assembly.'],
 ['CM-6','Satisfied','Interface and service settings are checked against the released reference configuration.'],
 ['SI-2','Partial','Product advisories are triaged; deployment remediation timing remains with each program.'],
 ['SI-3','Not applicable','The fixed-function release does not support executable content ingestion outside the verified image path.','Reassess if the deployment introduces file transfer or general-purpose application execution.'],
 ['SI-7','Satisfied','The release verification checks the component boot chains and the system installation manifest.','Verify installed production keys and any consumer-added images.',[ref('subsystem-a1','SI-7','Processing boot results support one part of the assembly claim.'),ref('subsystem-a2','SI-7','Gateway image verification supports the communications boundary.')]],
 ['SC-8','Partial','Internal protected channels are verified; external host and peer routes are outside the test scope.'],
 ['SC-12','Partial','The product defines key interfaces; programs provide key custodians and operating procedures.'],
 ['SC-13','Satisfied','The approved reference transport uses the declared CipherCore operating mode.'],
 ['CA-2','Satisfied','An independent assessment records each system-level conclusion and open integration finding.'],
 ['CA-7','Partial','The product team monitors release changes; deployment telemetry is supplied by consumers.'],
 ['IR-4','Not assessed','Product containment hooks exist; the operational response exercise is pending.'],
 ['IR-6','Partial','The product support escalation route is documented; program contacts are not assigned.'],
 ['CP-9','Partial','Released images are preserved; mission-state backup requirements remain unresolved.'],
 ['CP-10','Partial','Reference image restoration passes; recovery of integrated mission state is open.'],
 ]}),
record({id:'subsystem-a1',name:'Subsystem A.1',version:'2.1',kind:'Subsystem',owner:'Mission Processing',prefix:'A1',
 
 conditions:['Uses A.11 v1.2 and A.12 v1.0.','Consumer supplies mission applications, external time source, and upstream collection.'],children:[{slot:'A.11',objectId:'component-a11',label:'Mission computer'},{slot:'A.12',objectId:'component-a12',label:'Sensor interface'}],consumers:['alpha','beta'],assessmentDate:'2026-08-12',assessmentNote:"Compute tests passed; sensor-event selection open.",
 proofs:[['01','A.1 independent assembly assessment','Assessment report','Processing boundary and compute-to-sensor integration'],['02','Processing event and isolation tests','Test report','Reference compute and sensor traffic'],['03','A.1 release manifest','Baseline record','Nested component versions and signed settings']],
 reqs:[['LOG-01','Report compute and sensor security events through a common interface.',['AU-2','AU-3','AU-12'],'Open',['02']],['ISO-02','Restrict sensor traffic to its declared processing partition.',['AC-3','AC-6'],'Verified',['02']],['CFG-03','Verify the processing assembly against its released manifest.',['CM-2','CM-6','SI-7'],'Verified',['03']],['INT-05','Maintain sensor data ordering across a compute restart.',[],'Verified',['02']]],
 rows:[['AU-2','Partial','Compute events are selected; the sensor-reconnect event rationale remains open.','Confirm reconnect and malformed-sensor events for the consuming mission.',[ref('component-a11','AU-2','The component’s privileged-event selection is satisfied within its own boundary.'),ref('component-a12','AU-2','Sensor event capabilities inform the remaining assembly selection.')]],['AU-3','Partial','The assembly preserves source identities; external time quality awaits consumer verification.'],['AU-9','Satisfied','Only the processing audit service can alter the local event buffer.'],['AU-12','Satisfied','The common event interface receives reference compute and sensor events.'],['AC-3','Satisfied','Partition gates isolate sensor input from maintenance services.'],['AC-6','Satisfied','Sensor and compute services run under separate restricted identities.'],['CM-2','Satisfied','The assembly manifest identifies both child releases and wiring settings.'],['CM-3','Satisfied','Assembly changes require interface-impact review before release.'],['CM-6','Satisfied','Reference sensor channels and partition settings are verified.'],['SI-2','Partial','Child advisories are reviewed; one sensor driver correction awaits regression.'],['SI-7','Satisfied','Only signed compute and sensor images are admitted by the assembly manifest.'],['CA-2','Satisfied','Independent reviewers assessed the assembly boundary and its open findings.'],['CA-7','Partial','Release monitoring is active; deployed sensor fault trends require consumer input.'],['CP-10','Partial','Compute restart passes; mission-state resynchronization requires local verification.']]}),
record({id:'subsystem-a2',name:'Subsystem A.2',version:'1.4',kind:'Subsystem',owner:'Secure Communications',prefix:'A2',conditions:['Gateway policy bundle must match the approved peer set.','The consumer owns operational keys and external endpoint configuration.'],children:[{slot:'A.21',objectId:'component-a21',label:'Communications gateway'},{slot:'A.22',objectId:'component-a22',label:'Cryptographic module'}],consumers:['alpha'],assessmentDate:'2026-08-15',assessmentNote:"Transport tests passed; provisioning and peer selection open.",
 proofs:[['01','A.2 communications assembly assessment','Assessment report','Gateway-to-module security boundary'],['02','Protected transport integration tests','Test report','Approved reference peers and failure paths'],['03','A.2 policy and version index','Baseline record','Gateway, module, and peer-policy releases']],
 reqs:[['FLOW-01','Permit only declared reference peer flows.',['AC-3','CM-6'],'Verified',['02','03']],['LOG-02','Record rejected peers and transport failures.',['AU-2','AU-3','AU-12'],'Verified',['02']],['KEY-03','Protect keys across the gateway-to-module interface.',['SC-8','SC-12','SC-13'],'Verified',['02']],['CFG-04','Pin gateway and cryptographic module releases.',['CM-2','SI-7'],'Verified',['03']]],
 rows:[['AU-2','Satisfied','The reference event dictionary includes peer denial, link failure, and key-service errors.'],['AU-3','Partial','Connection records contain source and outcome; consuming-system time alignment is unverified.'],['AU-9','Satisfied','Gateway records use a protected local queue with restricted export.'],['AU-12','Satisfied','Failure-path tests generate the selected communications records.'],['AC-3','Satisfied','The signed reference policy restricts gateway peers and management routes.'],['CM-2','Satisfied','The index pins gateway 4.2 and crypto module 2.1.'],['CM-6','Satisfied','The approved policy bundle is loaded and checked after restart.'],['SI-2','Partial','Advisories are evaluated; deployment maintenance windows remain consumer-owned.'],['SI-7','Satisfied','Unsigned gateway images and policy bundles are rejected.'],['SC-8','Satisfied','Reference payload links use the approved protected transport profile.','Verify all deployed peers and external routes.',[ref('component-a22','SC-13','The module provides the assessed cryptographic service within its boundary.')]],['SC-12','Partial','The key-service interface is verified; live provisioning is outside the assembly boundary.'],['SC-13','Satisfied','The reference gateway integration invokes only the approved cryptographic mode.']]}),
record({id:'component-a11',name:'Component A.11 · Mission Computer X',version:'1.2',kind:'Component',owner:'Mission Computing',prefix:'MCX',conditions:['Production trust anchors; debug port disabled.','Application events, external time, and deployment identities are supplied by the consumer.'],children:[],consumers:['alpha','beta'],assessmentDate:'2026-07-18',assessmentNote:"Privileged-event tests passed.",
 proofs:[['01','MC-X 1.2 independent assessment','Assessment report','Qualified compute module'],['02','Privileged-event bench verification','Test report','Boot, maintenance, partition, and privileged actions'],['03','Partition and signed-boot test results','Test report','Production image and partition boundary']],
 reqs:[['SEC-014','Record privileged actions with actor and outcome.',['AU-2','AU-3','AU-12'],'Verified',['02']],['SEC-021','Execute only approved signed platform images.',['CM-2','SI-7'],'Verified',['03']],['SEC-032','Enforce partition resource boundaries.',['AC-3','AC-6'],'Verified',['03']],['INT-040','Each installed module shall expose its distinct configuration identity.',[],'Verified',['01']]],
 rows:[['AU-2','Satisfied','The module event catalog covers every privileged operation within its qualified firmware scope.'],['AU-3','Satisfied','Module records include event, local timestamp, actor, source, and outcome.'],['AU-9','Satisfied','The privileged audit service exclusively controls the protected local buffer.'],['AU-12','Satisfied','Bench tests generate every selected module event, including storage exhaustion.'],['AC-3','Satisfied','Partition access gates reject undeclared memory and device access.'],['AC-6','Satisfied','Maintenance and application partitions have distinct minimum capability sets.'],['CM-2','Satisfied','The module identity reports the qualified hardware, firmware, and image tuple.'],['CM-6','Partial','The qualified settings are documented; customer-loaded partition maps need confirmation.'],['SI-7','Satisfied','Modified boot images fail verification before execution.'],['SI-2','Partial','The release advisory register is maintained; deployment-specific exposure is not assessed.']]}),
record({id:'component-a12',name:'Component A.12 · Sensor Interface',version:'1.0',kind:'Component',owner:'Sensor Products',prefix:'SIF',conditions:['Only declared sensor protocols are enabled.','Malformed-data handling must be verified with the selected sensor.'],children:[],consumers:['alpha','beta'],assessmentDate:'2026-07-11',assessmentNote:"Channel and firmware tests passed; reconnect logging open.",
 proofs:[['01','Sensor Interface 1.0 assessment','Assessment report','Adapter boundary and fixed-function firmware'],['02','Sensor input negative-path tests','Test report','Malformed frames, reconnects, and unauthorized channels'],['03','Sensor adapter release manifest','Baseline record','Firmware and channel configuration']],
 reqs:[['CH-01','Reject inputs outside the configured channel and format.',['AC-3','CM-6'],'Verified',['02']],['LOG-02','Record rejected frames and reconnect events.',['AU-2','AU-12'],'Open',['02']],['FW-03','Accept only approved signed adapter firmware.',['CM-2','SI-7'],'Verified',['03']]],
 rows:[['AU-2','Partial','Malformed-frame events are selected; reconnect event classification remains open.'],['AU-3','Satisfied','Adapter events carry channel identity, frame counter, and outcome.'],['AU-12','Partial','Rejected frames generate records; a reconnect path does not yet emit an event.'],['AC-3','Satisfied','The adapter rejects undeclared input channels and command types.'],['CM-2','Satisfied','The release manifest identifies adapter firmware and channel schema.'],['CM-6','Satisfied','Disabled channels remain disabled across a power cycle.'],['SI-7','Satisfied','The firmware loader rejects unsigned images.'],['SI-2','Partial','The known reconnect issue is tracked for the next corrective release.']]}),
record({id:'component-a21',name:'Component A.21 · Gateway G4',version:'4.2',kind:'Component',owner:'Network Products',prefix:'GW',conditions:['A signed policy bundle defines allowed peers.','Consumers validate their own routes and external endpoint behavior.'],children:[],consumers:['alpha'],assessmentDate:'2026-07-22',assessmentNote:"Enforcement and audit tests passed.",
 proofs:[['01','Gateway 4.2 assessment','Assessment report','Appliance reference configuration'],['02','Gateway policy enforcement tests','Test report','Permitted and rejected peer flows'],['03','Gateway transport guide','Configuration guide','Supported protected transport profiles']],
 reqs:[['NET-08','Enforce the signed peer and route policy.',['AC-3','CM-6'],'Verified',['02']],['NET-12','Record connection decisions with peer identity.',['AU-2','AU-3','AU-12'],'Verified',['02']],['NET-19','Protect supported transport sessions.',['SC-8','SC-13'],'Verified',['03']]],
 rows:[['AU-2','Satisfied','The appliance selects management, connection, and policy-failure events.'],['AU-3','Satisfied','Gateway records include peer identity and policy decision.'],['AU-12','Satisfied','Policy enforcement tests produce all selected reference records.'],['AC-3','Satisfied','Only signed-policy peer and route combinations are admitted.'],['CM-2','Satisfied','The gateway exports image and policy fingerprints.'],['CM-6','Satisfied','Unauthorized policy changes are rejected and logged.'],['SI-7','Satisfied','The image loader verifies the gateway release signature.'],['SC-8','Partial','Supported protected sessions pass; complete external route coverage is consumer-owned.'],['SC-13','Satisfied','The appliance invokes supported cryptographic profiles without silent downgrade.']]}),
record({id:'component-a22',name:'Component A.22 · CipherCore C2',version:'2.1',kind:'Component',owner:'Cryptographic Engineering',prefix:'C2',conditions:['Approved operating mode is selected.','Operational keys and protocol integration are owned by consumers.'],children:[],consumers:['alpha'],assessmentDate:'2026-07-08',assessmentNote:"Module service tests complete.",
 proofs:[['01','CipherCore 2.1 boundary assessment','Assessment report','Module firmware and service API'],['02','Key lifecycle interface verification','Test report','Provisioning, use, zeroization, and unauthorized access'],['03','CipherCore approved-mode guide','Operating guide','Supported service configuration']],
 reqs:[['KEY-04','Restrict key use and zeroization to authorized services.',['AC-3','SC-12'],'Verified',['02']],['CRY-08','Provide cryptographic services in the declared approved mode.',['SC-8','SC-13'],'Verified',['03']],['FW-02','Verify the module image before service availability.',['CM-2','SI-7'],'Verified',['01']]],
 rows:[['AU-2','Satisfied','The service records failed key operations and administrative state changes.'],['AC-3','Satisfied','Service authorization restricts key-slot access and zeroization.'],['CM-2','Satisfied','The module reports its assessed firmware and mode identifier.'],['CM-6','Satisfied','The approved-mode configuration rejects incompatible service options.'],['SI-7','Satisfied','The module verifies its signed image before enabling key services.'],['SC-8','Partial','Module primitives are verified; end-to-end protocol protection is outside its boundary.'],['SC-12','Satisfied','Key lifecycle APIs enforce protected storage, authorized use, and zeroization.'],['SC-13','Satisfied','The declared service profile passes the module assurance tests.']]}),
record({id:'system-b',name:'System B',version:'2.0',kind:'System',owner:'Ground Products',prefix:'SYSB',conditions:['Subsystem A.1 v2.1','The consuming deployment supplies its identity tenant and ground network configuration.'],children:[{slot:'B.1',objectId:'subsystem-a1',label:'Shared mission processing'},{slot:'B.21',objectId:'component-b21',label:'Ground operator console'}],consumers:[],assessmentDate:'2026-08-28',assessmentNote:"Integration tests complete.",
 proofs:[['01','System B 2.0 integration assessment','Assessment report','Processing-to-console integration'],['02','Ground identity and event-flow tests','Integration test','Reference console roles and audit forwarding'],['03','System B release index','Baseline record','A.1 and console release pins']],
 reqs:[['INT-01','Preserve processing event identities at the operator console.',['AU-3','AU-12'],'Verified',['02']],['IAM-02','Enforce distinct operator and maintainer roles.',['AC-3','AC-6','IA-2'],'Verified',['02']],['CFG-03','Identify shared processing and console releases.',['CM-2','CM-6'],'Verified',['03']],['INT-099','Provide a visible indication when the processing link is unavailable.',[],'Verified',['02']]],
 rows:[['AU-1','Partial','Ground procedures define review responsibilities but require local owner assignment.'],['AU-2','Partial','Console events are selected; A.1 sensor reconnect selection remains unresolved.','Complete the shared processing finding and approve ground-operation events.',[ref('subsystem-a1','AU-2','The shared subsystem retains its own partial conclusion.')]],['AU-3','Satisfied','Reference console integration preserves processing source identities.'],['AU-6','Partial','The review console is implemented; operator review frequency is deployment-owned.'],['AU-9','Satisfied','The console protects received records and limits audit export roles.'],['AU-12','Satisfied','Reference integration tests cover operator and processing event paths.'],['AC-2','Partial','The account schema is defined; operational sponsors are not assigned.'],['AC-3','Satisfied','The reference integration enforces operator and maintainer command separation.'],['AC-6','Satisfied','Maintenance privileges are isolated from ordinary ground operation.'],['IA-2','Partial','Reference federation passes; the consumer tenant requires validation.'],['IA-5','Partial','Credential recovery flows are documented for local adoption.'],['CM-2','Satisfied','The system index pins shared A.1 v2.1 and console v7.0.'],['CM-3','Satisfied','Ground-system changes have documented security-impact review.'],['CM-6','Satisfied','Reference role and endpoint settings match the release index.'],['SI-7','Satisfied','The integration verifies signed processing and console release manifests.'],['CA-2','Satisfied','Independent review records system-level findings and reused child claims.'],['CP-9','Partial','Release images are protected; operator workspace data needs local backup decisions.'],['CP-10','Partial','Reference image restoration passes; deployed tenant recovery is untested.']]}),
record({id:'component-b21',name:'Component B.21 · Operator Console',version:'7.0',kind:'Component',owner:'Ground Products',prefix:'OC',conditions:['The declared identity tenant is configured.','Mission applications and emergency accounts receive local review.'],children:[],consumers:[],assessmentDate:'2026-07-30',assessmentNote:"Role and session tests passed.",
 proofs:[['01','Operator Console 7.0 assessment','Assessment report','Reference workstation image'],['02','Role and session verification','Test report','Operator, maintainer, and emergency access paths'],['03','Application allowlist baseline','Baseline record','Approved operator-shell packages']],
 reqs:[['ROLE-04','Separate operator and maintenance permissions.',['AC-3','AC-6'],'Verified',['02']],['AUTH-05','Identify and authenticate interactive sessions.',['IA-2','IA-5'],'Verified',['02']],['APP-12','Record shell actions and restrict executable packages.',['AU-12','SI-3','SI-7'],'Verified',['03']]],
 rows:[['AU-2','Satisfied','The console selects sign-in, role changes, and shell administration events.'],['AU-12','Satisfied','Reference shell actions generate attributable session events.'],['AC-3','Satisfied','The shell denies maintenance functions to operator roles.'],['AC-6','Satisfied','Ordinary operator sessions have no local administrator capability.'],['IA-2','Partial','The reference tenant authenticates sessions; deployment tenant validation remains.'],['IA-5','Partial','Emergency credential storage is supported; local custody is unassigned.'],['CM-2','Satisfied','The console reports its signed workstation-image manifest.'],['SI-3','Satisfied','The approved allowlist blocks unlisted application execution.'],['SI-7','Satisfied','Signed package checks protect the operator shell and platform image.']]}),
record({id:'host-h',name:'Host Platform H',version:'3.2',kind:'Host platform',owner:'Platform H Authority',prefix:'HOST',conditions:['Equipment is attached through approved interface H-17.','Detached operation is outside the host service boundary.','Protection of offloaded records begins at acknowledged receipt.'],children:[],consumers:['alpha'],assessmentDate:'2026-08-02',assessmentNote:"Host service review complete.",
 proofs:[['01','Platform H 3.2 provider assessment','Assessment report','Time, maintenance access, and offload service'],['02','H-17 interface assurance report','Integration test','Attached-mode service handoff'],['03','Host receipt and custody procedure','Operating procedure','Acknowledged audit transfer boundary']],
 reqs:[['TIME-04','Provide the declared time reference to attached equipment.',['AU-3'],'Verified',['02']],['ACCESS-09','Authenticate maintainers at the platform entry boundary.',['AC-3','IA-2'],'Verified',['01']],['LOG-16','Protect received audit records and their transfer channel.',['AU-9','SC-8'],'Verified',['02','03']],['INT-099','Identify attachment state and acknowledged transfer status.',[],'Verified',['02']]],
 rows:[['AU-3','Satisfied','The H-17 time service supplies an authenticated platform time reference.'],['AU-6','Satisfied','Host operations reviews received platform-service audit records.'],['AU-9','Satisfied','Received records enter access-controlled host custody after acknowledgment.'],['AC-3','Satisfied','The platform entry service restricts maintenance access by approved role.'],['IA-2','Satisfied','The host authenticates maintenance sessions at its declared boundary.'],['CM-2','Satisfied','The host provider identifies the assessed platform and interface configuration.'],['SC-8','Satisfied','The attached-mode offload channel protects transfer to acknowledged receipt.'],['IR-6','Partial','The host reports service incidents; consumer-specific contact validation remains.'],['CP-9','Satisfied','Received audit records are included in the host service backup scope.']]}),
record({id:'company-a',name:'Company A Profile',version:'3.0',kind:'Organizational profile',owner:'Company A Security Office',prefix:'ORGA',conditions:['The consuming program operates under Company A governance.','The program names local owners and adopts applicable procedures.'],children:[],consumers:['alpha','beta'],assessmentDate:'2026-08-20',assessmentNote:"Procedure review complete.",
 proofs:[['01','Company A profile assessment','Assessment report','Corporate governance and shared procedure execution'],['02','Audit policy and sampled governance review','Policy and review record','Corporate audit ownership and event-selection method'],['03','Workforce and change-governance samples','Operating records','Account reviews and security-impact approvals'],['04','Incident coordination exercise','Exercise record','Corporate triage and notification workflow']],
 reqs:[['AUD-01','Maintain approved audit responsibilities and event-selection procedures.',['AU-1','AU-2','AU-6'],'Verified',['02']],['IAM-02','Sponsor and periodically review workforce access.',['AC-2','AC-6'],'Verified',['03']],['CFG-03','Review security impact before approving controlled changes.',['CM-2','CM-3'],'Verified',['03']],['IR-04','Coordinate incident triage and program notification.',['IR-4','IR-6'],'Verified',['04']],['GOV-099','Every consuming program shall name an accountable assurance owner.',[],'Verified',['01']]],
 rows:[['AU-1','Satisfied','Company A maintains approved audit policy, ownership, and procedure review records.'],['AU-2','Satisfied','The corporate process requires documented event selection, rationale, and approval.'],['AU-6','Satisfied','Corporate oversight samples audit-review completion and tracks escalated findings.'],['AC-2','Satisfied','Workforce sponsorship and access review procedures have sampled execution evidence.'],['AC-6','Satisfied','Privileged-role approval includes duty justification and periodic review.'],['CM-2','Satisfied','The corporate configuration procedure requires controlled release and deployment indexes.'],['CM-3','Satisfied','Security-impact review is recorded by the corporate change authority.'],['CA-2','Satisfied','The assessment procedure defines scope, evidence review, and independent conclusions.'],['CA-7','Partial','Corporate metrics are reviewed; two operating units have incomplete reporting.'],['IR-4','Satisfied','The corporate triage team demonstrated its notification and coordination workflow.'],['IR-6','Satisfied','The exercise verified corporate reporting channels and escalation ownership.'],['CP-9','Partial','The corporate archive is assessed; operational program datasets are outside the profile.']]}),
record({id:'europe',name:'Europe Operations Overlay',version:'1.1',kind:'Overlay',owner:'European Security Office',baseProfileId:'company-a',prefix:'EU',conditions:['Applies only to explicitly selected European operations and program instances.','Company A Profile v3.0 is adopted as the base.','The program records its applicable retention and escalation decisions.'],children:[],consumers:['beta'],assessmentDate:'2026-08-26',assessmentNote:"Regional supplement review complete.",
 proofs:[['01','Europe overlay assessment','Assessment report','Regional governance responsibilities'],['02','Regional custody and escalation supplement','Approved procedure','Declared European operations'],['03','Regional coordination exercise','Exercise record','Security office and participating program contacts']],
 reqs:[['AUD-01','Name regional audit owners and custody destinations.',['AU-1','AU-9'],'Verified',['02']],['IR-02','Record and exercise regional incident escalation contacts.',['IR-6'],'Verified',['03']],['MON-03','Review regional custody exceptions with the base-profile owner.',['CA-7'],'Open',['01']],['GOV-099','Record the operating locations covered by the overlay.',[],'Verified',['02']]],
 rows:[['AU-1','Satisfied','The regional supplement adds named office responsibilities to the base audit policy.'],['AU-6','Satisfied','Regional oversight reviews custody exceptions and escalated audit findings.'],['AU-9','Partial','Regional custody rules are defined; each deployed storage destination needs approval.'],['CA-7','Partial','A regional exception review is scheduled; the first complete evidence cycle is pending.'],['IR-6','Satisfied','The regional exercise verified the office escalation and coordination route.']]}),
record({id:'company-b',name:'Company B Profile',version:'2.0',kind:'Organizational profile',owner:'Company B Assurance',prefix:'ORGB',conditions:['The consuming program operates under Company B governance.','Use with another corporate profile requires explicit responsibility allocation.'],children:[],consumers:[],assessmentDate:'2026-08-05',assessmentNote:"Governance review complete.",
 proofs:[['01','Company B governance assessment','Assessment report','Company B policy and process boundary'],['02','Policy and access-review register','Operating records','Company B audit and workforce governance'],['03','Supplier release and incident exercise','Review and exercise records','Supplier change review and coordination']],
 reqs:[['POL-01','Maintain approved audit procedures and named corporate owners.',['AU-1','AU-6'],'Verified',['02']],['ACC-02','Review workforce accounts and privilege exceptions.',['AC-2','AC-6'],'Verified',['02']],['CHG-03','Assess supplier release impacts before acceptance.',['CM-3','CA-7'],'Open',['03']],['IR-04','Exercise supplier-to-company incident notification.',['IR-4','IR-6'],'Verified',['03']],['GOV-099','Record the legal entity accountable for each program.',[],'Verified',['01']]],
 rows:[['AU-1','Satisfied','Company B policy assigns corporate audit responsibilities and annual review.'],['AU-6','Satisfied','Corporate reviewers sample completion of operating-unit audit reviews.'],['AC-2','Satisfied','The workforce register records sponsors, reviews, and offboarding decisions.'],['AC-6','Partial','Privilege exceptions are recorded; one business unit awaits its periodic review.'],['CM-3','Satisfied','Supplier changes receive recorded security-impact acceptance.'],['CA-2','Satisfied','Corporate assessments record scope, findings, and evidence references.'],['CA-7','Partial','Supplier monitoring is established; current reporting is incomplete for one supplier.'],['IR-4','Satisfied','The supplier exercise demonstrated coordinated incident triage.'],['IR-6','Satisfied','Corporate and supplier escalation routes passed the notification exercise.']]})
];

export const programs: Program[] = [
 {id:'alpha',name:'Program Alpha',owner:'Alpha Assurance Team',context:"Attached deployment",
  requirements:[{id:'ALPHA-LOG-01',title:'Demonstrate selected mission events across System A and the host offload boundary.',controlIds:['AU-2','AU-9','AU-12'],status:'Open',evidenceIds:['ALPHA-E-01']},{id:'ALPHA-CFG-02',title:'Verify installed serial identities against the approved deployment index.',controlIds:['CM-2'],status:'Verified',evidenceIds:['ALPHA-E-02']},{id:'ALPHA-INT-03',title:'Demonstrate attached and detached transition behavior.',controlIds:[],status:'Open',evidenceIds:[]}],
  evidence:[{id:'ALPHA-E-01',title:'Alpha integrated event-selection draft',kind:'Working record',date:'2026-09-04',scope:'Alpha System A instance; awaiting mission-event sign-off'},{id:'ALPHA-E-02',title:'Alpha installed configuration verification',kind:'Deployment test',date:'2026-09-05',scope:'Alpha installation serials and release pins'}]},
 {id:'beta',name:'Program Beta',owner:'Beta Assurance Team',context:"European ground deployment",
  requirements:[{id:'BETA-LOG-01',title:'Approve ground-operation event selection for the standalone processing assembly.',controlIds:['AU-2','AU-12'],status:'Open',evidenceIds:['BETA-E-01']},{id:'BETA-CUST-02',title:'Approve the regional audit storage destination.',controlIds:['AU-9'],status:'Open',evidenceIds:[]},{id:'BETA-INT-03',title:'Maintain sensor ordering during the ground integration restart sequence.',controlIds:[],status:'Verified',evidenceIds:['BETA-E-02']}],
  evidence:[{id:'BETA-E-01',title:'Beta ground-operation event review',kind:'Review record',date:'2026-09-03',scope:'Beta A.1 instance only'},{id:'BETA-E-02',title:'Beta sensor restart integration test',kind:'Integration test',date:'2026-09-06',scope:'Beta ground configuration; not the master A.1 release'}]},
];
export const initialInstances: ProgramInstance[] = [
 {id:'alpha-system-a',programId:'alpha',productId:'system-a',name:'System A · Alpha installation',role:'Product',hostInstanceId:'alpha-host-h',applicableControlIds:controls.map(control=>control.id)},
 {id:'alpha-a1',programId:'alpha',productId:'subsystem-a1',parentInstanceId:'alpha-system-a',name:'Subsystem A.1 · Mission processing',role:'Product'},
 {id:'alpha-a11',programId:'alpha',productId:'component-a11',parentInstanceId:'alpha-a1',name:'A.11 · Alpha mission computer',role:'Product'},
 {id:'alpha-a12',programId:'alpha',productId:'component-a12',parentInstanceId:'alpha-a1',name:'A.12 · Alpha sensor interface',role:'Product'},
 {id:'alpha-a2',programId:'alpha',productId:'subsystem-a2',parentInstanceId:'alpha-system-a',name:'Subsystem A.2 · Communications',role:'Product'},
 {id:'alpha-a21',programId:'alpha',productId:'component-a21',parentInstanceId:'alpha-a2',name:'A.21 · Alpha gateway',role:'Product'},
 {id:'alpha-a22',programId:'alpha',productId:'component-a22',parentInstanceId:'alpha-a2',name:'A.22 · Alpha cryptographic module',role:'Product'},
 {id:'alpha-host-h',programId:'alpha',productId:'host-h',name:'Host Platform H · Alpha attachment',role:'Host'},
 {id:'beta-a1',programId:'beta',productId:'subsystem-a1',name:'Subsystem A.1 · Beta ground installation',role:'Product'},
 {id:'beta-a11',programId:'beta',productId:'component-a11',parentInstanceId:'beta-a1',name:'A.11 · Beta mission computer',role:'Product'},
 {id:'beta-a12',programId:'beta',productId:'component-a12',parentInstanceId:'beta-a1',name:'A.12 · Beta sensor interface',role:'Product'},
];
export const initialProfiles: ProfileAssignment[] = [
 {id:'alpha-company-a',programId:'alpha',profileId:'company-a',targetInstanceIds:['alpha-system-a','alpha-a1','alpha-a11','alpha-a12','alpha-a2','alpha-a21','alpha-a22']},
 {id:'beta-company-a',programId:'beta',profileId:'company-a',targetInstanceIds:['beta-a1','beta-a11','beta-a12']},
 {id:'beta-europe',programId:'beta',profileId:'europe',targetInstanceIds:['beta-a1']},
];
export const initialDecisions: DecisionMap = {
 'alpha|alpha-system-a|AU-1':{confirmedSourceIds:['company-a'],excludedSourceIds:[],localNarrative:'Alpha adopts Company A audit policy v3.0. The Alpha assurance lead owns the local procedure and annual review.',localComplete:true},
 'alpha|alpha-system-a|AU-2':{confirmedSourceIds:['system-a','company-a'],excludedSourceIds:[],localNarrative:'The product event dictionary and company selection procedure apply. Alpha must still approve mission-specific events and verify the integrated sensor reconnect path.',localComplete:false},
 'alpha|alpha-system-a|CM-2':{confirmedSourceIds:['system-a','company-a'],excludedSourceIds:[],localNarrative:'Alpha’s installed configuration index records each serial identity and the approved System A v1.0 assembly. Deployment verification is recorded in ALPHA-E-02.',localComplete:true},
 'alpha|alpha-a11|AU-2':{confirmedSourceIds:['component-a11'],excludedSourceIds:[],localNarrative:'The compute-module event catalog applies to Alpha’s qualified hardware. Mission application events remain part of the system-level event review.',localComplete:false},
 'beta|beta-a1|AU-2':{confirmedSourceIds:['subsystem-a1','company-a'],excludedSourceIds:[],localNarrative:'Beta uses the processing assembly in a ground deployment. Its operator workflow adds sensor reconnect events distinct from Alpha’s attached mission configuration.',localComplete:false},
 'beta|beta-a1|AU-1':{confirmedSourceIds:['company-a','europe'],excludedSourceIds:[],localNarrative:'Beta names its regional audit coordinator and adopts the European supplement for this A.1 instance only.',localComplete:true},
 'beta|beta-a11|AU-2':{confirmedSourceIds:['component-a11'],excludedSourceIds:[],localNarrative:'Beta reuses MC-X 1.2 bench conclusions for the qualified module and separately validates its ground application events.',localComplete:false},
};
