/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as StigsRouteImport } from './routes/stigs'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as LibraryComponentsRouteImport } from './routes/library.components'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as RisksRiskIdRouteImport } from './routes/risks.$riskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const StigsRoute = StigsRouteImport.update({
  id: '/stigs',
  path: '/stigs',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryComponentsRoute = LibraryComponentsRouteImport.update({
  id: '/library/components',
  path: '/library/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProgramsRoute,
} as any)
const RisksRiskIdRoute = RisksRiskIdRouteImport.update({
  id: '/$riskId',
  path: '/$riskId',
  getParentRoute: () => RisksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/campaigns': typeof CampaignsRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/findings': typeof FindingsRoute
  '/packages': typeof PackagesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/register': typeof RegisterRoute
  '/risks': typeof RisksRouteWithChildren
  '/scope': typeof ScopeRoute
  '/stigs': typeof StigsRoute
  '/vendors': typeof VendorsRoute
  '/library/components': typeof LibraryComponentsRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/campaigns': typeof CampaignsRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/findings': typeof FindingsRoute
  '/packages': typeof PackagesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/register': typeof RegisterRoute
  '/risks': typeof RisksRouteWithChildren
  '/scope': typeof ScopeRoute
  '/stigs': typeof StigsRoute
  '/vendors': typeof VendorsRoute
  '/library/components': typeof LibraryComponentsRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/campaigns': typeof CampaignsRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/findings': typeof FindingsRoute
  '/packages': typeof PackagesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/register': typeof RegisterRoute
  '/risks': typeof RisksRouteWithChildren
  '/scope': typeof ScopeRoute
  '/stigs': typeof StigsRoute
  '/vendors': typeof VendorsRoute
  '/library/components': typeof LibraryComponentsRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefing'
    | '/campaigns'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/findings'
    | '/packages'
    | '/programs'
    | '/register'
    | '/risks'
    | '/scope'
    | '/stigs'
    | '/vendors'
    | '/library/components'
    | '/programs/$programId'
    | '/risks/$riskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefing'
    | '/campaigns'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/findings'
    | '/packages'
    | '/programs'
    | '/register'
    | '/risks'
    | '/scope'
    | '/stigs'
    | '/vendors'
    | '/library/components'
    | '/programs/$programId'
    | '/risks/$riskId'
  id:
    | '__root__'
    | '/'
    | '/briefing'
    | '/campaigns'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/findings'
    | '/packages'
    | '/programs'
    | '/register'
    | '/risks'
    | '/scope'
    | '/stigs'
    | '/vendors'
    | '/library/components'
    | '/programs/$programId'
    | '/risks/$riskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  CampaignsRoute: typeof CampaignsRoute
  ComponentsRoute: typeof ComponentsRoute
  ControlsRoute: typeof ControlsRoute
  EvidenceRoute: typeof EvidenceRoute
  FindingsRoute: typeof FindingsRoute
  PackagesRoute: typeof PackagesRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  RisksRoute: typeof RisksRouteWithChildren
  ScopeRoute: typeof ScopeRoute
  StigsRoute: typeof StigsRoute
  VendorsRoute: typeof VendorsRoute
  LibraryComponentsRoute: typeof LibraryComponentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stigs': {
      id: '/stigs'
      path: '/stigs'
      fullPath: '/stigs'
      preLoaderRoute: typeof StigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/components': {
      id: '/library/components'
      path: '/library/components'
      fullPath: '/library/components'
      preLoaderRoute: typeof LibraryComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/risks/$riskId': {
      id: '/risks/$riskId'
      path: '/$riskId'
      fullPath: '/risks/$riskId'
      preLoaderRoute: typeof RisksRiskIdRouteImport
      parentRoute: typeof RisksRoute
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface RisksRouteChildren {
  RisksRiskIdRoute: typeof RisksRiskIdRoute
}

const RisksRouteChildren: RisksRouteChildren = {
  RisksRiskIdRoute: RisksRiskIdRoute,
}

const RisksRouteWithChildren = RisksRoute._addFileChildren(RisksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  CampaignsRoute: CampaignsRoute,
  ComponentsRoute: ComponentsRoute,
  ControlsRoute: ControlsRoute,
  EvidenceRoute: EvidenceRoute,
  FindingsRoute: FindingsRoute,
  PackagesRoute: PackagesRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  RisksRoute: RisksRouteWithChildren,
  ScopeRoute: ScopeRoute,
  StigsRoute: StigsRoute,
  VendorsRoute: VendorsRoute,
  LibraryComponentsRoute: LibraryComponentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
