/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as StigsRouteImport } from './routes/stigs'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as FindingsIndexRouteImport } from './routes/findings.index'
import { Route as FindingsFindingIdRouteImport } from './routes/findings.$findingId'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesPkgIdRouteImport } from './routes/packages.$pkgId'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RisksRiskIdRouteImport } from './routes/risks.$riskId'
import { Route as WorkstreamsWorkstreamIdRouteImport } from './routes/workstreams.$workstreamId'
import { Route as FindingsAssetsAssetIdRouteImport } from './routes/findings.assets.$assetId'
import { Route as LibraryComponentsIndexRouteImport } from './routes/library.components.index'
import { Route as LibraryComponentsComponentKeyRouteImport } from './routes/library.components.$componentKey'
import { Route as ProgramsProgramIdDashboardRouteImport } from './routes/programs.$programId_.dashboard'
import { Route as RegisterPoamPoamIdRouteImport } from './routes/register.poam.$poamId'
import { Route as RegisterRisksRiskIdRouteImport } from './routes/register.risks.$riskId'
import { Route as ProgramsProgramIdControlsControlIdRouteImport } from './routes/programs.$programId_.controls.$controlId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const StigsRoute = StigsRouteImport.update({
  id: '/stigs',
  path: '/stigs',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsFindingIdRoute = FindingsFindingIdRouteImport.update({
  id: '/findings/$findingId',
  path: '/findings/$findingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPkgIdRoute = PackagesPkgIdRouteImport.update({
  id: '/packages/$pkgId',
  path: '/packages/$pkgId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProgramsRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRiskIdRoute = RisksRiskIdRouteImport.update({
  id: '/$riskId',
  path: '/$riskId',
  getParentRoute: () => RisksRoute,
} as any)
const WorkstreamsWorkstreamIdRoute = WorkstreamsWorkstreamIdRouteImport.update({
  id: '/workstreams/$workstreamId',
  path: '/workstreams/$workstreamId',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsAssetsAssetIdRoute = FindingsAssetsAssetIdRouteImport.update({
  id: '/findings/assets/$assetId',
  path: '/findings/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryComponentsIndexRoute = LibraryComponentsIndexRouteImport.update({
  id: '/library/components/',
  path: '/library/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryComponentsComponentKeyRoute =
  LibraryComponentsComponentKeyRouteImport.update({
    id: '/library/components/$componentKey',
    path: '/library/components/$componentKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsProgramIdDashboardRoute =
  ProgramsProgramIdDashboardRouteImport.update({
    id: '/$programId_/dashboard',
    path: '/$programId/dashboard',
    getParentRoute: () => ProgramsRoute,
  } as any)
const RegisterPoamPoamIdRoute = RegisterPoamPoamIdRouteImport.update({
  id: '/register/poam/$poamId',
  path: '/register/poam/$poamId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRisksRiskIdRoute = RegisterRisksRiskIdRouteImport.update({
  id: '/register/risks/$riskId',
  path: '/register/risks/$riskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdControlsControlIdRoute =
  ProgramsProgramIdControlsControlIdRouteImport.update({
    id: '/$programId_/controls/$controlId',
    path: '/$programId/controls/$controlId',
    getParentRoute: () => ProgramsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/campaigns': typeof CampaignsRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/risks': typeof RisksRouteWithChildren
  '/scope': typeof ScopeRoute
  '/stigs': typeof StigsRoute
  '/vendors': typeof VendorsRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/packages/$pkgId': typeof PackagesPkgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
  '/workstreams/$workstreamId': typeof WorkstreamsWorkstreamIdRoute
  '/findings/': typeof FindingsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/findings/assets/$assetId': typeof FindingsAssetsAssetIdRoute
  '/library/components/$componentKey': typeof LibraryComponentsComponentKeyRoute
  '/programs/$programId/dashboard': typeof ProgramsProgramIdDashboardRoute
  '/register/poam/$poamId': typeof RegisterPoamPoamIdRoute
  '/register/risks/$riskId': typeof RegisterRisksRiskIdRoute
  '/library/components/': typeof LibraryComponentsIndexRoute
  '/programs/$programId/controls/$controlId': typeof ProgramsProgramIdControlsControlIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/campaigns': typeof CampaignsRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/risks': typeof RisksRouteWithChildren
  '/scope': typeof ScopeRoute
  '/stigs': typeof StigsRoute
  '/vendors': typeof VendorsRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/packages/$pkgId': typeof PackagesPkgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
  '/workstreams/$workstreamId': typeof WorkstreamsWorkstreamIdRoute
  '/findings': typeof FindingsIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/register': typeof RegisterIndexRoute
  '/findings/assets/$assetId': typeof FindingsAssetsAssetIdRoute
  '/library/components/$componentKey': typeof LibraryComponentsComponentKeyRoute
  '/programs/$programId/dashboard': typeof ProgramsProgramIdDashboardRoute
  '/register/poam/$poamId': typeof RegisterPoamPoamIdRoute
  '/register/risks/$riskId': typeof RegisterRisksRiskIdRoute
  '/library/components': typeof LibraryComponentsIndexRoute
  '/programs/$programId/controls/$controlId': typeof ProgramsProgramIdControlsControlIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/campaigns': typeof CampaignsRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/risks': typeof RisksRouteWithChildren
  '/scope': typeof ScopeRoute
  '/stigs': typeof StigsRoute
  '/vendors': typeof VendorsRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/packages/$pkgId': typeof PackagesPkgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
  '/workstreams/$workstreamId': typeof WorkstreamsWorkstreamIdRoute
  '/findings/': typeof FindingsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/findings/assets/$assetId': typeof FindingsAssetsAssetIdRoute
  '/library/components/$componentKey': typeof LibraryComponentsComponentKeyRoute
  '/programs/$programId_/dashboard': typeof ProgramsProgramIdDashboardRoute
  '/register/poam/$poamId': typeof RegisterPoamPoamIdRoute
  '/register/risks/$riskId': typeof RegisterRisksRiskIdRoute
  '/library/components/': typeof LibraryComponentsIndexRoute
  '/programs/$programId_/controls/$controlId': typeof ProgramsProgramIdControlsControlIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefing'
    | '/campaigns'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/programs'
    | '/risks'
    | '/scope'
    | '/stigs'
    | '/vendors'
    | '/findings/$findingId'
    | '/packages/$pkgId'
    | '/people/$personId'
    | '/programs/$programId'
    | '/risks/$riskId'
    | '/workstreams/$workstreamId'
    | '/findings/'
    | '/packages/'
    | '/register/'
    | '/findings/assets/$assetId'
    | '/library/components/$componentKey'
    | '/programs/$programId/dashboard'
    | '/register/poam/$poamId'
    | '/register/risks/$riskId'
    | '/library/components/'
    | '/programs/$programId/controls/$controlId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefing'
    | '/campaigns'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/programs'
    | '/risks'
    | '/scope'
    | '/stigs'
    | '/vendors'
    | '/findings/$findingId'
    | '/packages/$pkgId'
    | '/people/$personId'
    | '/programs/$programId'
    | '/risks/$riskId'
    | '/workstreams/$workstreamId'
    | '/findings'
    | '/packages'
    | '/register'
    | '/findings/assets/$assetId'
    | '/library/components/$componentKey'
    | '/programs/$programId/dashboard'
    | '/register/poam/$poamId'
    | '/register/risks/$riskId'
    | '/library/components'
    | '/programs/$programId/controls/$controlId'
  id:
    | '__root__'
    | '/'
    | '/briefing'
    | '/campaigns'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/programs'
    | '/risks'
    | '/scope'
    | '/stigs'
    | '/vendors'
    | '/findings/$findingId'
    | '/packages/$pkgId'
    | '/people/$personId'
    | '/programs/$programId'
    | '/risks/$riskId'
    | '/workstreams/$workstreamId'
    | '/findings/'
    | '/packages/'
    | '/register/'
    | '/findings/assets/$assetId'
    | '/library/components/$componentKey'
    | '/programs/$programId_/dashboard'
    | '/register/poam/$poamId'
    | '/register/risks/$riskId'
    | '/library/components/'
    | '/programs/$programId_/controls/$controlId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  CampaignsRoute: typeof CampaignsRoute
  ComponentsRoute: typeof ComponentsRoute
  ControlsRoute: typeof ControlsRoute
  EvidenceRoute: typeof EvidenceRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  RisksRoute: typeof RisksRouteWithChildren
  ScopeRoute: typeof ScopeRoute
  StigsRoute: typeof StigsRoute
  VendorsRoute: typeof VendorsRoute
  FindingsFindingIdRoute: typeof FindingsFindingIdRoute
  PackagesPkgIdRoute: typeof PackagesPkgIdRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  WorkstreamsWorkstreamIdRoute: typeof WorkstreamsWorkstreamIdRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  FindingsAssetsAssetIdRoute: typeof FindingsAssetsAssetIdRoute
  LibraryComponentsComponentKeyRoute: typeof LibraryComponentsComponentKeyRoute
  RegisterPoamPoamIdRoute: typeof RegisterPoamPoamIdRoute
  RegisterRisksRiskIdRoute: typeof RegisterRisksRiskIdRoute
  LibraryComponentsIndexRoute: typeof LibraryComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stigs': {
      id: '/stigs'
      path: '/stigs'
      fullPath: '/stigs'
      preLoaderRoute: typeof StigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/': {
      id: '/findings/'
      path: '/findings'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/$findingId': {
      id: '/findings/$findingId'
      path: '/findings/$findingId'
      fullPath: '/findings/$findingId'
      preLoaderRoute: typeof FindingsFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$pkgId': {
      id: '/packages/$pkgId'
      path: '/packages/$pkgId'
      fullPath: '/packages/$pkgId'
      preLoaderRoute: typeof PackagesPkgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks/$riskId': {
      id: '/risks/$riskId'
      path: '/$riskId'
      fullPath: '/risks/$riskId'
      preLoaderRoute: typeof RisksRiskIdRouteImport
      parentRoute: typeof RisksRoute
    }
    '/workstreams/$workstreamId': {
      id: '/workstreams/$workstreamId'
      path: '/workstreams/$workstreamId'
      fullPath: '/workstreams/$workstreamId'
      preLoaderRoute: typeof WorkstreamsWorkstreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/assets/$assetId': {
      id: '/findings/assets/$assetId'
      path: '/findings/assets/$assetId'
      fullPath: '/findings/assets/$assetId'
      preLoaderRoute: typeof FindingsAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/components/': {
      id: '/library/components/'
      path: '/library/components'
      fullPath: '/library/components/'
      preLoaderRoute: typeof LibraryComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/components/$componentKey': {
      id: '/library/components/$componentKey'
      path: '/library/components/$componentKey'
      fullPath: '/library/components/$componentKey'
      preLoaderRoute: typeof LibraryComponentsComponentKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId_/dashboard': {
      id: '/programs/$programId_/dashboard'
      path: '/$programId/dashboard'
      fullPath: '/programs/$programId/dashboard'
      preLoaderRoute: typeof ProgramsProgramIdDashboardRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/register/poam/$poamId': {
      id: '/register/poam/$poamId'
      path: '/register/poam/$poamId'
      fullPath: '/register/poam/$poamId'
      preLoaderRoute: typeof RegisterPoamPoamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/risks/$riskId': {
      id: '/register/risks/$riskId'
      path: '/register/risks/$riskId'
      fullPath: '/register/risks/$riskId'
      preLoaderRoute: typeof RegisterRisksRiskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId_/controls/$controlId': {
      id: '/programs/$programId_/controls/$controlId'
      path: '/$programId/controls/$controlId'
      fullPath: '/programs/$programId/controls/$controlId'
      preLoaderRoute: typeof ProgramsProgramIdControlsControlIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
  ProgramsProgramIdDashboardRoute: typeof ProgramsProgramIdDashboardRoute
  ProgramsProgramIdControlsControlIdRoute: typeof ProgramsProgramIdControlsControlIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
  ProgramsProgramIdDashboardRoute: ProgramsProgramIdDashboardRoute,
  ProgramsProgramIdControlsControlIdRoute:
    ProgramsProgramIdControlsControlIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface RisksRouteChildren {
  RisksRiskIdRoute: typeof RisksRiskIdRoute
}

const RisksRouteChildren: RisksRouteChildren = {
  RisksRiskIdRoute: RisksRiskIdRoute,
}

const RisksRouteWithChildren = RisksRoute._addFileChildren(RisksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  CampaignsRoute: CampaignsRoute,
  ComponentsRoute: ComponentsRoute,
  ControlsRoute: ControlsRoute,
  EvidenceRoute: EvidenceRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  RisksRoute: RisksRouteWithChildren,
  ScopeRoute: ScopeRoute,
  StigsRoute: StigsRoute,
  VendorsRoute: VendorsRoute,
  FindingsFindingIdRoute: FindingsFindingIdRoute,
  PackagesPkgIdRoute: PackagesPkgIdRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  WorkstreamsWorkstreamIdRoute: WorkstreamsWorkstreamIdRoute,
  FindingsIndexRoute: FindingsIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  FindingsAssetsAssetIdRoute: FindingsAssetsAssetIdRoute,
  LibraryComponentsComponentKeyRoute: LibraryComponentsComponentKeyRoute,
  RegisterPoamPoamIdRoute: RegisterPoamPoamIdRoute,
  RegisterRisksRiskIdRoute: RegisterRisksRiskIdRoute,
  LibraryComponentsIndexRoute: LibraryComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
