/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as StigsRouteImport } from './routes/stigs'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as FindingsIndexRouteImport } from './routes/findings.index'
import { Route as FindingsFindingIdRouteImport } from './routes/findings.$findingId'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesPkgIdRouteImport } from './routes/packages.$pkgId'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RisksRiskIdRouteImport } from './routes/risks.$riskId'
import { Route as WorkstreamsWorkstreamIdRouteImport } from './routes/workstreams.$workstreamId'
import { Route as FindingsAssetsAssetIdRouteImport } from './routes/findings.assets.$assetId'
import { Route as LibraryComponentsIndexRouteImport } from './routes/library.components.index'
import { Route as LibraryComponentsComponentKeyRouteImport } from './routes/library.components.$componentKey'
import { Route as ProgramsProgramIdBaselineRouteImport } from './routes/programs.$programId_.baseline'
import { Route as ProgramsProgramIdCompositionRouteImport } from './routes/programs.$programId_.composition'
import { Route as ProgramsProgramIdConmonRouteImport } from './routes/programs.$programId_.conmon'
import { Route as ProgramsProgramIdDashboardRouteImport } from './routes/programs.$programId_.dashboard'
import { Route as ProgramsProgramIdExportRouteImport } from './routes/programs.$programId_.export'
import { Route as ProgramsProgramIdIngestionRouteImport } from './routes/programs.$programId_.ingestion'
import { Route as ProgramsProgramIdInheritanceRouteImport } from './routes/programs.$programId_.inheritance'
import { Route as ProgramsProgramIdRiskRouteImport } from './routes/programs.$programId_.risk'
import { Route as ProgramsProgramIdSctmRouteImport } from './routes/programs.$programId_.sctm'
import { Route as ProgramsProgramIdTePhasesRouteImport } from './routes/programs.$programId_.te-phases'
import { Route as RegisterPoamPoamIdRouteImport } from './routes/register.poam.$poamId'
import { Route as RegisterRisksRiskIdRouteImport } from './routes/register.risks.$riskId'
import { Route as ProgramsProgramIdComponentsComponentIdRouteImport } from './routes/programs.$programId_.components.$componentId'
import { Route as ProgramsProgramIdControlsControlIdRouteImport } from './routes/programs.$programId_.controls.$controlId'
import { Route as ProgramsProgramIdRequirementsRequirementIdRouteImport } from './routes/programs.$programId_.requirements.$requirementId'
import { Route as ProgramsProgramIdSystemsScopeIdRouteImport } from './routes/programs.$programId_.systems.$scopeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const StigsRoute = StigsRouteImport.update({
  id: '/stigs',
  path: '/stigs',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsFindingIdRoute = FindingsFindingIdRouteImport.update({
  id: '/findings/$findingId',
  path: '/findings/$findingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPkgIdRoute = PackagesPkgIdRouteImport.update({
  id: '/packages/$pkgId',
  path: '/packages/$pkgId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProgramsRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRiskIdRoute = RisksRiskIdRouteImport.update({
  id: '/$riskId',
  path: '/$riskId',
  getParentRoute: () => RisksRoute,
} as any)
const WorkstreamsWorkstreamIdRoute = WorkstreamsWorkstreamIdRouteImport.update({
  id: '/workstreams/$workstreamId',
  path: '/workstreams/$workstreamId',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsAssetsAssetIdRoute = FindingsAssetsAssetIdRouteImport.update({
  id: '/findings/assets/$assetId',
  path: '/findings/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryComponentsIndexRoute = LibraryComponentsIndexRouteImport.update({
  id: '/library/components/',
  path: '/library/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryComponentsComponentKeyRoute =
  LibraryComponentsComponentKeyRouteImport.update({
    id: '/library/components/$componentKey',
    path: '/library/components/$componentKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsProgramIdBaselineRoute =
  ProgramsProgramIdBaselineRouteImport.update({
    id: '/$programId_/baseline',
    path: '/$programId/baseline',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsProgramIdCompositionRoute =
  ProgramsProgramIdCompositionRouteImport.update({
    id: '/$programId_/composition',
    path: '/$programId/composition',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsProgramIdConmonRoute = ProgramsProgramIdConmonRouteImport.update({
  id: '/$programId_/conmon',
  path: '/$programId/conmon',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsProgramIdDashboardRoute =
  ProgramsProgramIdDashboardRouteImport.update({
    id: '/$programId_/dashboard',
    path: '/$programId/dashboard',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsProgramIdExportRoute = ProgramsProgramIdExportRouteImport.update({
  id: '/$programId_/export',
  path: '/$programId/export',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsProgramIdIngestionRoute =
  ProgramsProgramIdIngestionRouteImport.update({
    id: '/$programId_/ingestion',
    path: '/$programId/ingestion',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsProgramIdInheritanceRoute =
  ProgramsProgramIdInheritanceRouteImport.update({
    id: '/$programId_/inheritance',
    path: '/$programId/inheritance',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsProgramIdRiskRoute = ProgramsProgramIdRiskRouteImport.update({
  id: '/$programId_/risk',
  path: '/$programId/risk',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsProgramIdSctmRoute = ProgramsProgramIdSctmRouteImport.update({
  id: '/$programId_/sctm',
  path: '/$programId/sctm',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsProgramIdTePhasesRoute =
  ProgramsProgramIdTePhasesRouteImport.update({
    id: '/$programId_/te-phases',
    path: '/$programId/te-phases',
    getParentRoute: () => ProgramsRoute,
  } as any)
const RegisterPoamPoamIdRoute = RegisterPoamPoamIdRouteImport.update({
  id: '/register/poam/$poamId',
  path: '/register/poam/$poamId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRisksRiskIdRoute = RegisterRisksRiskIdRouteImport.update({
  id: '/register/risks/$riskId',
  path: '/register/risks/$riskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdComponentsComponentIdRoute =
  ProgramsProgramIdComponentsComponentIdRouteImport.update({
    id: '/$programId_/components/$componentId',
    path: '/$programId/components/$componentId',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsProgramIdControlsControlIdRoute =
  ProgramsProgramIdControlsControlIdRouteImport.update({
    id: '/$programId_/controls/$controlId',
    path: '/$programId/controls/$controlId',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsProgramIdRequirementsRequirementIdRoute =
  ProgramsProgramIdRequirementsRequirementIdRouteImport.update({
    id: '/$programId_/requirements/$requirementId',
    path: '/$programId/requirements/$requirementId',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsProgramIdSystemsScopeIdRoute =
  ProgramsProgramIdSystemsScopeIdRouteImport.update({
    id: '/$programId_/systems/$scopeId',
    path: '/$programId/systems/$scopeId',
    getParentRoute: () => ProgramsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/risks': typeof RisksRouteWithChildren
  '/scope': typeof ScopeRoute
  '/stigs': typeof StigsRoute
  '/vendors': typeof VendorsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/packages/$pkgId': typeof PackagesPkgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
  '/workstreams/$workstreamId': typeof WorkstreamsWorkstreamIdRoute
  '/findings/': typeof FindingsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/findings/assets/$assetId': typeof FindingsAssetsAssetIdRoute
  '/library/components/$componentKey': typeof LibraryComponentsComponentKeyRoute
  '/programs/$programId/baseline': typeof ProgramsProgramIdBaselineRoute
  '/programs/$programId/composition': typeof ProgramsProgramIdCompositionRoute
  '/programs/$programId/conmon': typeof ProgramsProgramIdConmonRoute
  '/programs/$programId/dashboard': typeof ProgramsProgramIdDashboardRoute
  '/programs/$programId/export': typeof ProgramsProgramIdExportRoute
  '/programs/$programId/ingestion': typeof ProgramsProgramIdIngestionRoute
  '/programs/$programId/inheritance': typeof ProgramsProgramIdInheritanceRoute
  '/programs/$programId/risk': typeof ProgramsProgramIdRiskRoute
  '/programs/$programId/sctm': typeof ProgramsProgramIdSctmRoute
  '/programs/$programId/te-phases': typeof ProgramsProgramIdTePhasesRoute
  '/register/poam/$poamId': typeof RegisterPoamPoamIdRoute
  '/register/risks/$riskId': typeof RegisterRisksRiskIdRoute
  '/library/components/': typeof LibraryComponentsIndexRoute
  '/programs/$programId/components/$componentId': typeof ProgramsProgramIdComponentsComponentIdRoute
  '/programs/$programId/controls/$controlId': typeof ProgramsProgramIdControlsControlIdRoute
  '/programs/$programId/requirements/$requirementId': typeof ProgramsProgramIdRequirementsRequirementIdRoute
  '/programs/$programId/systems/$scopeId': typeof ProgramsProgramIdSystemsScopeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/risks': typeof RisksRouteWithChildren
  '/scope': typeof ScopeRoute
  '/stigs': typeof StigsRoute
  '/vendors': typeof VendorsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/packages/$pkgId': typeof PackagesPkgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
  '/workstreams/$workstreamId': typeof WorkstreamsWorkstreamIdRoute
  '/findings': typeof FindingsIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/register': typeof RegisterIndexRoute
  '/findings/assets/$assetId': typeof FindingsAssetsAssetIdRoute
  '/library/components/$componentKey': typeof LibraryComponentsComponentKeyRoute
  '/programs/$programId/baseline': typeof ProgramsProgramIdBaselineRoute
  '/programs/$programId/composition': typeof ProgramsProgramIdCompositionRoute
  '/programs/$programId/conmon': typeof ProgramsProgramIdConmonRoute
  '/programs/$programId/dashboard': typeof ProgramsProgramIdDashboardRoute
  '/programs/$programId/export': typeof ProgramsProgramIdExportRoute
  '/programs/$programId/ingestion': typeof ProgramsProgramIdIngestionRoute
  '/programs/$programId/inheritance': typeof ProgramsProgramIdInheritanceRoute
  '/programs/$programId/risk': typeof ProgramsProgramIdRiskRoute
  '/programs/$programId/sctm': typeof ProgramsProgramIdSctmRoute
  '/programs/$programId/te-phases': typeof ProgramsProgramIdTePhasesRoute
  '/register/poam/$poamId': typeof RegisterPoamPoamIdRoute
  '/register/risks/$riskId': typeof RegisterRisksRiskIdRoute
  '/library/components': typeof LibraryComponentsIndexRoute
  '/programs/$programId/components/$componentId': typeof ProgramsProgramIdComponentsComponentIdRoute
  '/programs/$programId/controls/$controlId': typeof ProgramsProgramIdControlsControlIdRoute
  '/programs/$programId/requirements/$requirementId': typeof ProgramsProgramIdRequirementsRequirementIdRoute
  '/programs/$programId/systems/$scopeId': typeof ProgramsProgramIdSystemsScopeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/risks': typeof RisksRouteWithChildren
  '/scope': typeof ScopeRoute
  '/stigs': typeof StigsRoute
  '/vendors': typeof VendorsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/packages/$pkgId': typeof PackagesPkgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
  '/workstreams/$workstreamId': typeof WorkstreamsWorkstreamIdRoute
  '/findings/': typeof FindingsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/findings/assets/$assetId': typeof FindingsAssetsAssetIdRoute
  '/library/components/$componentKey': typeof LibraryComponentsComponentKeyRoute
  '/programs/$programId_/baseline': typeof ProgramsProgramIdBaselineRoute
  '/programs/$programId_/composition': typeof ProgramsProgramIdCompositionRoute
  '/programs/$programId_/conmon': typeof ProgramsProgramIdConmonRoute
  '/programs/$programId_/dashboard': typeof ProgramsProgramIdDashboardRoute
  '/programs/$programId_/export': typeof ProgramsProgramIdExportRoute
  '/programs/$programId_/ingestion': typeof ProgramsProgramIdIngestionRoute
  '/programs/$programId_/inheritance': typeof ProgramsProgramIdInheritanceRoute
  '/programs/$programId_/risk': typeof ProgramsProgramIdRiskRoute
  '/programs/$programId_/sctm': typeof ProgramsProgramIdSctmRoute
  '/programs/$programId_/te-phases': typeof ProgramsProgramIdTePhasesRoute
  '/register/poam/$poamId': typeof RegisterPoamPoamIdRoute
  '/register/risks/$riskId': typeof RegisterRisksRiskIdRoute
  '/library/components/': typeof LibraryComponentsIndexRoute
  '/programs/$programId_/components/$componentId': typeof ProgramsProgramIdComponentsComponentIdRoute
  '/programs/$programId_/controls/$controlId': typeof ProgramsProgramIdControlsControlIdRoute
  '/programs/$programId_/requirements/$requirementId': typeof ProgramsProgramIdRequirementsRequirementIdRoute
  '/programs/$programId_/systems/$scopeId': typeof ProgramsProgramIdSystemsScopeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefing'
    | '/campaigns'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/programs'
    | '/risks'
    | '/scope'
    | '/stigs'
    | '/vendors'
    | '/campaigns/$campaignId'
    | '/findings/$findingId'
    | '/packages/$pkgId'
    | '/people/$personId'
    | '/programs/$programId'
    | '/risks/$riskId'
    | '/workstreams/$workstreamId'
    | '/findings/'
    | '/packages/'
    | '/register/'
    | '/findings/assets/$assetId'
    | '/library/components/$componentKey'
    | '/programs/$programId/baseline'
    | '/programs/$programId/composition'
    | '/programs/$programId/conmon'
    | '/programs/$programId/dashboard'
    | '/programs/$programId/export'
    | '/programs/$programId/ingestion'
    | '/programs/$programId/inheritance'
    | '/programs/$programId/risk'
    | '/programs/$programId/sctm'
    | '/programs/$programId/te-phases'
    | '/register/poam/$poamId'
    | '/register/risks/$riskId'
    | '/library/components/'
    | '/programs/$programId/components/$componentId'
    | '/programs/$programId/controls/$controlId'
    | '/programs/$programId/requirements/$requirementId'
    | '/programs/$programId/systems/$scopeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefing'
    | '/campaigns'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/programs'
    | '/risks'
    | '/scope'
    | '/stigs'
    | '/vendors'
    | '/campaigns/$campaignId'
    | '/findings/$findingId'
    | '/packages/$pkgId'
    | '/people/$personId'
    | '/programs/$programId'
    | '/risks/$riskId'
    | '/workstreams/$workstreamId'
    | '/findings'
    | '/packages'
    | '/register'
    | '/findings/assets/$assetId'
    | '/library/components/$componentKey'
    | '/programs/$programId/baseline'
    | '/programs/$programId/composition'
    | '/programs/$programId/conmon'
    | '/programs/$programId/dashboard'
    | '/programs/$programId/export'
    | '/programs/$programId/ingestion'
    | '/programs/$programId/inheritance'
    | '/programs/$programId/risk'
    | '/programs/$programId/sctm'
    | '/programs/$programId/te-phases'
    | '/register/poam/$poamId'
    | '/register/risks/$riskId'
    | '/library/components'
    | '/programs/$programId/components/$componentId'
    | '/programs/$programId/controls/$controlId'
    | '/programs/$programId/requirements/$requirementId'
    | '/programs/$programId/systems/$scopeId'
  id:
    | '__root__'
    | '/'
    | '/briefing'
    | '/campaigns'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/programs'
    | '/risks'
    | '/scope'
    | '/stigs'
    | '/vendors'
    | '/campaigns/$campaignId'
    | '/findings/$findingId'
    | '/packages/$pkgId'
    | '/people/$personId'
    | '/programs/$programId'
    | '/risks/$riskId'
    | '/workstreams/$workstreamId'
    | '/findings/'
    | '/packages/'
    | '/register/'
    | '/findings/assets/$assetId'
    | '/library/components/$componentKey'
    | '/programs/$programId_/baseline'
    | '/programs/$programId_/composition'
    | '/programs/$programId_/conmon'
    | '/programs/$programId_/dashboard'
    | '/programs/$programId_/export'
    | '/programs/$programId_/ingestion'
    | '/programs/$programId_/inheritance'
    | '/programs/$programId_/risk'
    | '/programs/$programId_/sctm'
    | '/programs/$programId_/te-phases'
    | '/register/poam/$poamId'
    | '/register/risks/$riskId'
    | '/library/components/'
    | '/programs/$programId_/components/$componentId'
    | '/programs/$programId_/controls/$controlId'
    | '/programs/$programId_/requirements/$requirementId'
    | '/programs/$programId_/systems/$scopeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  ComponentsRoute: typeof ComponentsRoute
  ControlsRoute: typeof ControlsRoute
  EvidenceRoute: typeof EvidenceRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  RisksRoute: typeof RisksRouteWithChildren
  ScopeRoute: typeof ScopeRoute
  StigsRoute: typeof StigsRoute
  VendorsRoute: typeof VendorsRoute
  FindingsFindingIdRoute: typeof FindingsFindingIdRoute
  PackagesPkgIdRoute: typeof PackagesPkgIdRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  WorkstreamsWorkstreamIdRoute: typeof WorkstreamsWorkstreamIdRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  FindingsAssetsAssetIdRoute: typeof FindingsAssetsAssetIdRoute
  LibraryComponentsComponentKeyRoute: typeof LibraryComponentsComponentKeyRoute
  RegisterPoamPoamIdRoute: typeof RegisterPoamPoamIdRoute
  RegisterRisksRiskIdRoute: typeof RegisterRisksRiskIdRoute
  LibraryComponentsIndexRoute: typeof LibraryComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stigs': {
      id: '/stigs'
      path: '/stigs'
      fullPath: '/stigs'
      preLoaderRoute: typeof StigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/findings/': {
      id: '/findings/'
      path: '/findings'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/$findingId': {
      id: '/findings/$findingId'
      path: '/findings/$findingId'
      fullPath: '/findings/$findingId'
      preLoaderRoute: typeof FindingsFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$pkgId': {
      id: '/packages/$pkgId'
      path: '/packages/$pkgId'
      fullPath: '/packages/$pkgId'
      preLoaderRoute: typeof PackagesPkgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks/$riskId': {
      id: '/risks/$riskId'
      path: '/$riskId'
      fullPath: '/risks/$riskId'
      preLoaderRoute: typeof RisksRiskIdRouteImport
      parentRoute: typeof RisksRoute
    }
    '/workstreams/$workstreamId': {
      id: '/workstreams/$workstreamId'
      path: '/workstreams/$workstreamId'
      fullPath: '/workstreams/$workstreamId'
      preLoaderRoute: typeof WorkstreamsWorkstreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/assets/$assetId': {
      id: '/findings/assets/$assetId'
      path: '/findings/assets/$assetId'
      fullPath: '/findings/assets/$assetId'
      preLoaderRoute: typeof FindingsAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/components/': {
      id: '/library/components/'
      path: '/library/components'
      fullPath: '/library/components/'
      preLoaderRoute: typeof LibraryComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/components/$componentKey': {
      id: '/library/components/$componentKey'
      path: '/library/components/$componentKey'
      fullPath: '/library/components/$componentKey'
      preLoaderRoute: typeof LibraryComponentsComponentKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId_/baseline': {
      id: '/programs/$programId_/baseline'
      path: '/$programId/baseline'
      fullPath: '/programs/$programId/baseline'
      preLoaderRoute: typeof ProgramsProgramIdBaselineRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/composition': {
      id: '/programs/$programId_/composition'
      path: '/$programId/composition'
      fullPath: '/programs/$programId/composition'
      preLoaderRoute: typeof ProgramsProgramIdCompositionRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/conmon': {
      id: '/programs/$programId_/conmon'
      path: '/$programId/conmon'
      fullPath: '/programs/$programId/conmon'
      preLoaderRoute: typeof ProgramsProgramIdConmonRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/dashboard': {
      id: '/programs/$programId_/dashboard'
      path: '/$programId/dashboard'
      fullPath: '/programs/$programId/dashboard'
      preLoaderRoute: typeof ProgramsProgramIdDashboardRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/export': {
      id: '/programs/$programId_/export'
      path: '/$programId/export'
      fullPath: '/programs/$programId/export'
      preLoaderRoute: typeof ProgramsProgramIdExportRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/ingestion': {
      id: '/programs/$programId_/ingestion'
      path: '/$programId/ingestion'
      fullPath: '/programs/$programId/ingestion'
      preLoaderRoute: typeof ProgramsProgramIdIngestionRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/inheritance': {
      id: '/programs/$programId_/inheritance'
      path: '/$programId/inheritance'
      fullPath: '/programs/$programId/inheritance'
      preLoaderRoute: typeof ProgramsProgramIdInheritanceRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/risk': {
      id: '/programs/$programId_/risk'
      path: '/$programId/risk'
      fullPath: '/programs/$programId/risk'
      preLoaderRoute: typeof ProgramsProgramIdRiskRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/sctm': {
      id: '/programs/$programId_/sctm'
      path: '/$programId/sctm'
      fullPath: '/programs/$programId/sctm'
      preLoaderRoute: typeof ProgramsProgramIdSctmRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/te-phases': {
      id: '/programs/$programId_/te-phases'
      path: '/$programId/te-phases'
      fullPath: '/programs/$programId/te-phases'
      preLoaderRoute: typeof ProgramsProgramIdTePhasesRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/register/poam/$poamId': {
      id: '/register/poam/$poamId'
      path: '/register/poam/$poamId'
      fullPath: '/register/poam/$poamId'
      preLoaderRoute: typeof RegisterPoamPoamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/risks/$riskId': {
      id: '/register/risks/$riskId'
      path: '/register/risks/$riskId'
      fullPath: '/register/risks/$riskId'
      preLoaderRoute: typeof RegisterRisksRiskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId_/components/$componentId': {
      id: '/programs/$programId_/components/$componentId'
      path: '/$programId/components/$componentId'
      fullPath: '/programs/$programId/components/$componentId'
      preLoaderRoute: typeof ProgramsProgramIdComponentsComponentIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/controls/$controlId': {
      id: '/programs/$programId_/controls/$controlId'
      path: '/$programId/controls/$controlId'
      fullPath: '/programs/$programId/controls/$controlId'
      preLoaderRoute: typeof ProgramsProgramIdControlsControlIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/requirements/$requirementId': {
      id: '/programs/$programId_/requirements/$requirementId'
      path: '/$programId/requirements/$requirementId'
      fullPath: '/programs/$programId/requirements/$requirementId'
      preLoaderRoute: typeof ProgramsProgramIdRequirementsRequirementIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId_/systems/$scopeId': {
      id: '/programs/$programId_/systems/$scopeId'
      path: '/$programId/systems/$scopeId'
      fullPath: '/programs/$programId/systems/$scopeId'
      preLoaderRoute: typeof ProgramsProgramIdSystemsScopeIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface ProgramsRouteChildren {
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
  ProgramsProgramIdBaselineRoute: typeof ProgramsProgramIdBaselineRoute
  ProgramsProgramIdCompositionRoute: typeof ProgramsProgramIdCompositionRoute
  ProgramsProgramIdConmonRoute: typeof ProgramsProgramIdConmonRoute
  ProgramsProgramIdDashboardRoute: typeof ProgramsProgramIdDashboardRoute
  ProgramsProgramIdExportRoute: typeof ProgramsProgramIdExportRoute
  ProgramsProgramIdIngestionRoute: typeof ProgramsProgramIdIngestionRoute
  ProgramsProgramIdInheritanceRoute: typeof ProgramsProgramIdInheritanceRoute
  ProgramsProgramIdRiskRoute: typeof ProgramsProgramIdRiskRoute
  ProgramsProgramIdSctmRoute: typeof ProgramsProgramIdSctmRoute
  ProgramsProgramIdTePhasesRoute: typeof ProgramsProgramIdTePhasesRoute
  ProgramsProgramIdComponentsComponentIdRoute: typeof ProgramsProgramIdComponentsComponentIdRoute
  ProgramsProgramIdControlsControlIdRoute: typeof ProgramsProgramIdControlsControlIdRoute
  ProgramsProgramIdRequirementsRequirementIdRoute: typeof ProgramsProgramIdRequirementsRequirementIdRoute
  ProgramsProgramIdSystemsScopeIdRoute: typeof ProgramsProgramIdSystemsScopeIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
  ProgramsProgramIdBaselineRoute: ProgramsProgramIdBaselineRoute,
  ProgramsProgramIdCompositionRoute: ProgramsProgramIdCompositionRoute,
  ProgramsProgramIdConmonRoute: ProgramsProgramIdConmonRoute,
  ProgramsProgramIdDashboardRoute: ProgramsProgramIdDashboardRoute,
  ProgramsProgramIdExportRoute: ProgramsProgramIdExportRoute,
  ProgramsProgramIdIngestionRoute: ProgramsProgramIdIngestionRoute,
  ProgramsProgramIdInheritanceRoute: ProgramsProgramIdInheritanceRoute,
  ProgramsProgramIdRiskRoute: ProgramsProgramIdRiskRoute,
  ProgramsProgramIdSctmRoute: ProgramsProgramIdSctmRoute,
  ProgramsProgramIdTePhasesRoute: ProgramsProgramIdTePhasesRoute,
  ProgramsProgramIdComponentsComponentIdRoute:
    ProgramsProgramIdComponentsComponentIdRoute,
  ProgramsProgramIdControlsControlIdRoute:
    ProgramsProgramIdControlsControlIdRoute,
  ProgramsProgramIdRequirementsRequirementIdRoute:
    ProgramsProgramIdRequirementsRequirementIdRoute,
  ProgramsProgramIdSystemsScopeIdRoute: ProgramsProgramIdSystemsScopeIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface RisksRouteChildren {
  RisksRiskIdRoute: typeof RisksRiskIdRoute
}

const RisksRouteChildren: RisksRouteChildren = {
  RisksRiskIdRoute: RisksRiskIdRoute,
}

const RisksRouteWithChildren = RisksRoute._addFileChildren(RisksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  ComponentsRoute: ComponentsRoute,
  ControlsRoute: ControlsRoute,
  EvidenceRoute: EvidenceRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  RisksRoute: RisksRouteWithChildren,
  ScopeRoute: ScopeRoute,
  StigsRoute: StigsRoute,
  VendorsRoute: VendorsRoute,
  FindingsFindingIdRoute: FindingsFindingIdRoute,
  PackagesPkgIdRoute: PackagesPkgIdRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  WorkstreamsWorkstreamIdRoute: WorkstreamsWorkstreamIdRoute,
  FindingsIndexRoute: FindingsIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  FindingsAssetsAssetIdRoute: FindingsAssetsAssetIdRoute,
  LibraryComponentsComponentKeyRoute: LibraryComponentsComponentKeyRoute,
  RegisterPoamPoamIdRoute: RegisterPoamPoamIdRoute,
  RegisterRisksRiskIdRoute: RegisterRisksRiskIdRoute,
  LibraryComponentsIndexRoute: LibraryComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
