/**
 * DISA CCI definitions — CA — Assessment, Authorization, and Monitoring.
 *
 * Do not hand-edit — regenerate with: node scripts/gen-cci-catalog.mjs
 *
 * Loaded on demand by loadCciFamily("CA") in @/lib/cci-catalog. The index
 * there carries every other field; this chunk is only the definition prose.
 *
 * Source: U_CCI_List_2024.xml (DISA CCI list 2024-01-10), via a public mirror of the
 * DISA Cyber Exchange list. DISA CCI is a US Government work.
 */

export const cciDefinitions: Record<string, string> = {
  "CCI-000238": "Defines the frequency to review and update the current assessment, authorization, and monitoring policy.",
  "CCI-000239": "Develop and document an organization-level; mission/business process; system-level assessment, authorization, and monitoring policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance.",
  "CCI-000240": "Disseminates to organization-defined personnel or roles an organization-level; mission/business process; system-level assessment, authorization, and monitoring policy.",
  "CCI-000241": "Review and update the current assessment, authorization, and monitoring policy on an organization-defined frequency.",
  "CCI-000242": "Develop and document procedures to facilitate the implementation of the assessment, authorization, and monitoring policy and associated assessment, authorization, and monitoring controls.",
  "CCI-000243": "Disseminate to organization-defined personnel or roles procedures to facilitate the implementation of the assessment, authorization, and monitoring policy and associated assessment, authorization, and monitoring controls.",
  "CCI-000244": "Review and update the current assessment, authorization, and monitoring procedures on an organization-defined frequency.",
  "CCI-000245": "The organization develops a security assessment plan for the information system and its environment of operation.",
  "CCI-000246": "Develop a control assessment plan that describes the scope of the assessment including controls and control enhancements under assessment.",
  "CCI-000247": "Develop a control assessment plan that describes the scope of the assessment including assessment procedures to be used to determine control effectiveness.",
  "CCI-000248": "Develop a control assessment plan that describes the scope of the assessment including assessment environment.",
  "CCI-000249": "The organizations security assessment plan describes the assessment team.",
  "CCI-000250": "The organization's security assessment plan describes assessment roles and responsibilities.",
  "CCI-000251": "Assess the controls in the systems and its environment of operation on an organization-defined frequency, to determine the extent to which the controls are implemented correctly, operating as intended, and producing the desired outcome with respect to meeting the security requirements.",
  "CCI-000252": "Defines the frequency on which the security controls in the system and its environment of operation are assessed.",
  "CCI-000253": "Produce a control assessment report that document the results of the assessment.",
  "CCI-000254": "Provide the results of the control assessment to organization-defined individuals or roles.",
  "CCI-000255": "Employ independent assessors or assessment teams to conduct control assessments.",
  "CCI-000256": "Include as part of the control assessments, announced or unannounced, on an organization-defined frequency, in-depth monitoring; security instrumentation; automated security test cases; vulnerability scanning; malicious user testing; insider threat assessment; performance and load testing; data leakage or data loss assessment; and/or organization-defined other forms of assessment.",
  "CCI-000257": "The organization authorizes connections from the information system to other information systems through the use of Interconnection Security Agreements.",
  "CCI-000258": "Document, as part of each exchange agreement, the interface characteristics.",
  "CCI-000259": "Document, as part of each exchange agreement,, the security requirements, controls and responsibilities for each system, and the impact level of the information communicated.",
  "CCI-000260": "The organization documents, for each interconnection, the nature of the information communicated.",
  "CCI-000261": "The organization monitors the information system connections on an ongoing basis to verify enforcement of security requirements.",
  "CCI-000262": "The organization prohibits the direct connection of an organization-defined unclassified, national security system to an external network without the use of an organization-defined boundary protection device.",
  "CCI-000263": "The organization prohibits the direct connection of a classified, national security system to an external network without the use of organization-defined boundary protection device.",
  "CCI-000264": "Develop a plan of action and milestones for the system to document the planned remediation actions of the organization to correct weaknesses or deficiencies noted during the assessment of the controls and to reduce or eliminate known vulnerabilities in the system.",
  "CCI-000265": "Defines the frequency with which to update the existing plan of action and milestones for the system.",
  "CCI-000266": "Update, on an organization-defined frequency, the existing plan of action and milestones based on the findings from control assessments, independent audits or reviews, and continuous monitoring activities.",
  "CCI-000267": "Ensure the accuracy of the plan of action and milestones for the system using organization-defined automated mechanisms.",
  "CCI-000268": "Ensure the currency of the plan of action and milestones for the system using organization-defined automated mechanisms.",
  "CCI-000269": "Ensure the availability of the plan of action and milestones for the system using organization-defined automated mechanisms.",
  "CCI-000270": "Assign a senior official as the authorizing official for the system.",
  "CCI-000271": "Ensure the authorizing official for the system authorizes the system to operate before commencing operations.",
  "CCI-000272": "Update the authorization on an organization-defined frequency.",
  "CCI-000273": "Defines the frequency with which to update the authorizations.",
  "CCI-000274": "Develop a continuous monitoring strategy.",
  "CCI-000275": "The organization implements a continuous monitoring program that includes a configuration management process for the information system.",
  "CCI-000276": "The organization implements a continuous monitoring program that includes a configuration management process for the information system constituent components.",
  "CCI-000277": "The organization implements a continuous monitoring program that includes a determination of the security impact of changes to the information system.",
  "CCI-000278": "The organization implements a continuous monitoring program that includes a determination of the security impact of changes to the environment of operation.",
  "CCI-000279": "Implement ongoing control assessments in accordance with the continuous monitoring strategy.",
  "CCI-000280": "Implement a continuous monitoring program that includes reporting the security status to organization-defined personnel or roles on an organization-defined frequency.",
  "CCI-000281": "Defines the frequency with which to report the security status to organization-defined personnel or roles.",
  "CCI-000282": "Employ independent assessors or assessment teams to monitor the controls in the system on an ongoing basis.",
  "CCI-000283": "The organization plans announced or unannounced assessments (in-depth monitoring, malicious user testing, penetration testing, red team exercises, or other organization-defined forms of security assessment), on an organization-defined frequency, to ensure compliance with all vulnerability mitigation procedures.",
  "CCI-000284": "The organization schedules announced or unannounced assessments (in-depth monitoring, malicious user testing, penetration testing, red team exercises, or other organization-defined forms of security assessment), on an organization-defined frequency, to ensure compliance with all vulnerability mitigation procedures.",
  "CCI-000285": "The organization conducts announced or unannounced assessments (in-depth monitoring, malicious user testing, penetration testing, red team exercises, or other organization-defined forms of security assessment), on an organization-defined frequency, to ensure compliance with all vulnerability mitigation procedures.",
  "CCI-001578": "Defines the frequency to review and update the current assessment, authorization, and monitoring procedures.",
  "CCI-001579": "The organization conducts security control assessments using organization-defined forms of testing in accordance with organization-defined frequency and assessment techniques.",
  "CCI-001580": "The organization identifies connections to external information systems (i.e., information systems outside of the authorization boundary).",
  "CCI-001581": "The organization defines personnel or roles to whom the security status of the organization and the information system should be reported.",
  "CCI-001582": "Defines other forms of control assessments other than in-depth monitoring; security instrumentation; automated security test cases; vulnerability scanning; malicious user testing; insider threat assessment; performance and load testing; data leakage or data loss assessment that should be included as part of the control assessments.",
  "CCI-001583": "The organization selects announced or unannounced assessments for each form of security control assessment.",
  "CCI-001681": "The organization defines the frequency at which each form of security control assessment should be conducted.",
  "CCI-002060": "The organization develops and documents a security assessment and authorization policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance.",
  "CCI-002061": "Defines the personnel or roles to whom the organization-level; mission/business process; system-level assessment, authorization, and monitoring policy is to be disseminated.",
  "CCI-002062": "Defines the personnel or roles to whom the assessment, authorization, monitoring procedures are to be disseminated.",
  "CCI-002063": "The organization defines the level of independence for assessors or assessment teams to conduct security control assessments of organizational information systems.",
  "CCI-002064": "The organization selects one or more security assessment techniques to be conducted.",
  "CCI-002065": "Defines the frequency at which to conduct control assessments.",
  "CCI-002066": "Leverage the results of control assessments of the organization-defined system performed by an organization-defined external organization when the assessment meets organization-defined requirements.",
  "CCI-002067": "Defines the system for which the results of control assessments will be leveraged.",
  "CCI-002068": "Defines the external organizations from which control assessment results for organization-defined systems will be accepted.",
  "CCI-002069": "Defines the requirements the control assessments for organization-defined systems from organization-defined external organizations must meet.",
  "CCI-002070": "Develop a control assessment plan that describes the scope of the assessment including assessment team, and assessment roles and responsibilities.",
  "CCI-002071": "Defines the individuals or roles to whom the results of the control assessment are to be provided.",
  "CCI-002072": "The organization defines the unclassified, national security systems that are prohibited from directly connecting to an external network without the use of an organization-defined boundary protection device.",
  "CCI-002073": "The organization defines the boundary protection device to be used to connect organization-defined unclassified, national security systems to an external network.",
  "CCI-002074": "The organization defines the boundary protection device to be used for the direct connection of classified, national security system to an external network.",
  "CCI-002075": "The organization prohibits the direct connection of an organization-defined unclassified, non-national security system to an external network without the use of organization-defined boundary protection device.",
  "CCI-002076": "The organization defines the unclassified, non-national security system that is prohibited from directly connecting to an external network without the use of an organization-defined boundary protection device.",
  "CCI-002077": "The organization defines the boundary protection device to be used to directly connect an organization-defined unclassified, non-national security system to an external network.",
  "CCI-002078": "The organization prohibits the direct connection of an organization-defined information system to a public network.",
  "CCI-002079": "The organization defines the information system that is prohibited from directly connecting to a public network.",
  "CCI-002080": "The organization employs either an allow-all, deny-by-exception or a deny-all, permit-by-exception policy for allowing organization-defined information systems to connect to external information systems.",
  "CCI-002081": "The organization defines the information systems that employ either an allow-all, deny-by-exception or a deny-all, permit-by-exception policy for allowing connections to external information systems.",
  "CCI-002082": "The organization selects either an allow-all, deny-by-exception or a deny-all, permit-by-exception policy for allowing organization-defined information systems to connect to external information systems.",
  "CCI-002083": "Review and update the agreements on an organization-defined frequency.",
  "CCI-002084": "Defines the frequency at which reviews and updates to the agreements must be conducted.",
  "CCI-002085": "The organization defines the level of independence the assessors or assessment teams must have to monitor the security controls in the information system on an ongoing basis.",
  "CCI-002086": "Employ trend analyses to determine if control implementations, the frequency of continuous monitoring activities, and the types of activities used in the continuous monitoring process need to be modified based on empirical data.",
  "CCI-002087": "Establish organization-defined system-level metrics to be monitored.",
  "CCI-002088": "Establish organization-defined frequencies for monitoring.",
  "CCI-002089": "The organization establishes and defines the frequencies for assessments supporting continuous monitoring.",
  "CCI-002090": "Implement ongoing monitoring of system and organization-defined metrics in accordance with the continuous monitoring strategy.",
  "CCI-002091": "Implement a continuous monitoring program that includes correlation and analysis of information generated by assessments and monitoring.",
  "CCI-002092": "Implement a continuous monitoring program that includes response actions to address results of the analysis of control assessment and monitoring information.",
  "CCI-002093": "Conduct penetration testing in accordance with organization-defined frequency on organization-defined systems or system components.",
  "CCI-002094": "Defines the frequency for conducting penetration testing on organization-defined systems or system components.",
  "CCI-002095": "Defines the systems or system components on which penetration testing will be conducted.",
  "CCI-002096": "Employ an independent penetration agent or penetration team to perform penetration testing on the system or system components.",
  "CCI-002097": "Defines red team exercises to simulate attempts by adversaries to compromise organizational systems.",
  "CCI-002098": "The organization defines rules of engagement for red team exercises to simulate attempts by adversaries to compromise organizational information systems.",
  "CCI-002099": "Employ organization-defined red team exercises to simulate attempts by adversaries to compromise organizational systems in accordance with applicable rules of engagement.",
  "CCI-002100": "Perform security compliance checks on constituent components prior to the establishment of the internal connection.",
  "CCI-002101": "Authorizes internal connections of organization-defined system components or classes of components to the system.",
  "CCI-002102": "Defines the system components or classes of components that are authorized internal connections to the system.",
  "CCI-002103": "Document, for each internal connection, the interface characteristics.",
  "CCI-002104": "Document, for each internal connection, the security requirements.",
  "CCI-002105": "Document, for each internal connection, the nature of the information communicated.",
  "CCI-003849": "Disseminate an organization-level; mission/business process; system-level assessment, authorization, and monitoring policy that is consistent with applicable laws, Executive Orders, directives, regulations, policies, standards, and guidelines.",
  "CCI-003850": "Defines the personnel or roles to whom the assessment, authorization, and monitoring policy is to be disseminated.",
  "CCI-003851": "Designate an organization-defined official to manage the development and documentation of the assessment, authorization, and monitoring policy.",
  "CCI-003852": "Designate an organization-defined official to manage the development and documentation of the assessment, authorization, and monitoring procedures.",
  "CCI-003853": "Designate an organization-defined official to manage the dissemination of the assessment, authorization, and monitoring policy.",
  "CCI-003854": "Designate an organization-defined official to manage the dissemination of the assessment, authorization, and monitoring procedures.",
  "CCI-003855": "Review and update the current assessment, authorization, and monitoring policy following organization-defined events.",
  "CCI-003856": "Defines the events following reviewing and updating the current assessment, authorization, and monitoring policy.",
  "CCI-003857": "Review and update the current assessment and authorization procedures following organization-defined events.",
  "CCI-003858": "Defines the events following reviewing and updating the current assessment, authorization, and monitoring procedures.",
  "CCI-003859": "Select the appropriate assessor or assessment team for the type of assessment to be conducted.",
  "CCI-003860": "Ensure the control assessment plan is reviewed and approved by the authorizing official or designated representative prior to conducting the assessment.",
  "CCI-003861": "Assess the controls in the systems and its environment of operation on an organization-defined frequency, to determine the extent to which the controls are implemented correctly, operating as intended, and producing the desired outcome with respect to meeting the privacy requirements.",
  "CCI-003862": "Approve and manage the exchange of information between the system and other systems using interconnection security agreements; information exchange security agreements; memoranda of understanding or agreement; service level agreements; user agreement; and/or nondisclosure agreements with an organization-defined type of agreement.",
  "CCI-003863": "Document, as part of each exchange agreement, the privacy requirements, controls and responsibilities for each system, and the impact level of the information communicated.",
  "CCI-003864": "Verify that individuals or systems transferring data between interconnecting systems have the requisite authorizations (i.e., write permissions or privileges) prior to accepting such data.",
  "CCI-003865": "Identify transitive (downstream) information exchanges with other systems through the systems identified in CA-3a.",
  "CCI-003866": "Take measures to ensure that transitive (downstream) information exchanges cease when the controls on identified transitive (downstream) systems cannot be verified or validated.",
  "CCI-003867": "Defines the automated mechanisms to ensure the accuracy, currency, and availability of the plan of actions and milestones.",
  "CCI-003868": "Assign a senior official as the authorizing official for common controls available for inheritance by organizational systems.",
  "CCI-003869": "Ensure the authorizing official accepts the use of common controls inherited by the system, before commencing operations.",
  "CCI-003870": "Ensure that the authorizing official for common controls authorizes the use of those controls for inheritance by organizational systems.",
  "CCI-003871": "Employ a joint authorization process for the system that includes multiple authorizing officials from the same organization conducting the authorization.",
  "CCI-003872": "Employ a joint authorization process for the system that includes multiple authorizing officials with at least one authorizing official from an organization external to the organization conducting the authorization.",
  "CCI-003873": "Implement continuous monitoring in accordance with the organization-level continuous monitoring strategy.",
  "CCI-003874": "Defines the system-level metrics to be monitored.",
  "CCI-003875": "Establish organization-defined frequencies for assessment of control effectiveness.",
  "CCI-003876": "Defines the frequencies for monitoring of control effectiveness.",
  "CCI-003877": "Defines the frequencies for assessment of control effectiveness.",
  "CCI-003878": "Develop ongoing control assessments in accordance with the continuous monitoring strategy.",
  "CCI-003879": "Implement a continuous monitoring program that includes reporting the privacy status to organization-defined personnel or roles on an organization-defined frequency.",
  "CCI-003880": "Defines the frequency with which to report the privacy status to organization-defined personnel or roles.",
  "CCI-003881": "Ensure risk monitoring is an integral part of the continuous monitoring strategy that includes effectiveness monitoring.",
  "CCI-003882": "Ensure risk monitoring is an integral part of the continuous monitoring strategy that includes compliance monitoring.",
  "CCI-003883": "Ensure risk monitoring is an integral part of the continuous monitoring strategy that includes change monitoring.",
  "CCI-003884": "Employ organization-defined actions to validate that policies are established.",
  "CCI-003885": "Employ organization-defined actions to validate that implemented controls are operating in a consistent manner.",
  "CCI-003886": "Defines the actions used to validate policies.",
  "CCI-003887": "Ensure the accuracy, currency, and availability of monitoring results for the system using organization-defined automated mechanisms.",
  "CCI-003888": "Defines the automated mechanisms for ensuring accuracy, currency, and availability of monitoring results.",
  "CCI-003889": "Employ a penetration testing process, on an organization-defined frequency, that includes announced or unannounced attempts to bypass or circumvent controls associated with physical access points to the facility.",
  "CCI-003890": "Defines the frequency the penetration testing process will be employed.",
  "CCI-003891": "Document, for each internal connection, the privacy requirements.",
  "CCI-003892": "Terminate internal system connections after organization-defined conditions.",
  "CCI-003893": "Defines the conditions for terminating internal system connections.",
  "CCI-003894": "Review on an organization-defined frequency the continued need for each internal connection.",
  "CCI-003895": "Defines the frequency for reviewing each internal connection.",
  "CCI-003896": "Perform privacy compliance checks on constituent components prior to the establishment of the internal connection.",
};
