/**
 * DISA CCI definitions — IA — Identification and Authentication.
 *
 * Do not hand-edit — regenerate with: node scripts/gen-cci-catalog.mjs
 *
 * Loaded on demand by loadCciFamily("IA") in @/lib/cci-catalog. The index
 * there carries every other field; this chunk is only the definition prose.
 *
 * Source: U_CCI_List_2024.xml (DISA CCI list 2024-01-10), via a public mirror of the
 * DISA Cyber Exchange list. DISA CCI is a US Government work.
 */

export const cciDefinitions: Record<string, string> = {
  "CCI-000175": "The organization manages information system authenticators for users and devices by verifying, as part of the initial authenticator distribution, the identity of the individual and/or device receiving the authenticator.",
  "CCI-000176": "Manage system authenticators by establishing initial authenticator content for authenticators issued by the organization.",
  "CCI-000177": "The organization manages information system authenticators for users and devices by establishing and implementing administrative procedures for initial authenticator distribution, for lost/compromised, or damaged authenticators, and for revoking authenticators.",
  "CCI-000178": "The organization manages information system authenticators for users and devices by changing default content of authenticators upon information system installation.",
  "CCI-000179": "The organization manages information system authenticators by establishing minimum lifetime restrictions for authenticators.",
  "CCI-000180": "The organization manages information system authenticators by establishing maximum lifetime restrictions for authenticators.",
  "CCI-000181": "The organization manages information system authenticators by establishing reuse conditions for authenticators.",
  "CCI-000182": "Manage system authenticators by changing or refreshing authenticators in accordance with the organization-defined time period by authenticator type or when organization-defined events occur.",
  "CCI-000183": "Manage system authenticators by protecting authenticator content from unauthorized disclosure.",
  "CCI-000184": "Manages system authenticators by requiring individuals to take, and having devices implement, specific security controls to protect authenticators.",
  "CCI-000185": "For public key-based authentication, validate certificates by constructing and verifying a certification path to an accepted trust anchor including checking certificate status information.",
  "CCI-000186": "For public key-based authentication, enforce authorized access to the corresponding private key.",
  "CCI-000187": "For public key-based authentication, map the authenticated identity to the account of the individual or group.",
  "CCI-000188": "The organization requires that the registration process to receive an organizational-defined type of authenticator be carried out in person before a designated registration authority with authorization by a designated organizational official (e.g., a supervisor).",
  "CCI-000189": "The organization employs automated tools to determine if authenticators are sufficiently strong to resist attacks intended to discover or otherwise compromise the authenticators.",
  "CCI-000190": "The organization requires vendors/manufacturers of information system components to provide unique authenticators or change default authenticators prior to delivery.",
  "CCI-000191": "The organization enforces password complexity by the number of special characters used.",
  "CCI-000192": "The information system enforces password complexity by the minimum number of upper case characters used.",
  "CCI-000193": "The information system enforces password complexity by the minimum number of lower case characters used.",
  "CCI-000194": "The information system enforces password complexity by the minimum number of numeric characters used.",
  "CCI-000195": "The information system, for password-based authentication, when new passwords are created, enforces that at least an organization-defined number of characters are changed.",
  "CCI-000196": "The information system, for password-based authentication, stores only cryptographically-protected passwords.",
  "CCI-000197": "For password-based authentication, transmit passwords only cryptographically-protected channels.",
  "CCI-000198": "The information system enforces minimum password lifetime restrictions.",
  "CCI-000199": "The information system enforces maximum password lifetime restrictions.",
  "CCI-000200": "The information system prohibits password reuse for the organization-defined number of generations.",
  "CCI-000201": "Protect authenticators commensurate with the security category of the information to which use of the authenticator permits access.",
  "CCI-000202": "The organization ensures unencrypted static authenticators are not embedded in access scripts.",
  "CCI-000203": "The organization ensures unencrypted static authenticators are not stored on function keys.",
  "CCI-000204": "Defines the security controls required to manage the risk of compromise due to individuals having accounts on multiple information systems.",
  "CCI-000205": "The information system enforces minimum password length.",
  "CCI-000206": "Obscure feedback of authentication information during the authentication process to protect the information from possible exploitation and use by unauthorized individuals.",
  "CCI-000756": "The organization develops an identification and authentication policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance.",
  "CCI-000757": "Disseminate an organization-level; mission/business process-level; and/or system-level identification and authentication policy to organization-defined personnel.",
  "CCI-000758": "Review and update the current identification and authentication policy in accordance with the organization-defined frequency.",
  "CCI-000759": "Defines a frequency for reviewing and updating the identification and authentication policy.",
  "CCI-000760": "The organization develops procedures to facilitate the implementation of the identification and authentication policy and associated identification and authentication controls.",
  "CCI-000761": "The organization disseminates to organization-defined personnel or roles procedures to facilitate the implementation of the identification and authentication policy and associated identification and authentication controls.",
  "CCI-000762": "Review and update the current identification and authentication procedures in accordance with the organization-defined frequency.",
  "CCI-000763": "Defines a frequency for reviewing and updating the identification and authentication procedures.",
  "CCI-000764": "Uniquely identify and authenticate organizational users and associate that unique identification with processes acting on behalf of those users.",
  "CCI-000765": "Implement multifactor authentication for network access to privileged accounts.",
  "CCI-000766": "Implement multifactor authentication for network access to non-privileged accounts.",
  "CCI-000767": "The information system implements multifactor authentication for local access to privileged accounts.",
  "CCI-000768": "The information system implements multifactor authentication for local access to non-privileged accounts.",
  "CCI-000769": "The organization allows the use of group authenticators only when used in conjunction with an individual/unique authenticator.",
  "CCI-000770": "The organization requires individuals to be authenticated with an individual authenticator when a group authenticator is employed.",
  "CCI-000771": "The information system uses multifactor authentication for network access to privileged accounts where one of the factors is provided by a device separate from the information system being accessed.",
  "CCI-000772": "The information system uses multifactor authentication for network access to non-privileged accounts where one of the factors is provided by a device separate from the information system being accessed.",
  "CCI-000773": "The organization defines replay-resistant authentication mechanisms to be used for network access to privileged accounts.",
  "CCI-000774": "The information system uses organization-defined replay-resistant authentication mechanisms for network access to privileged accounts.",
  "CCI-000775": "The organization defines replay-resistant authentication mechanisms to be used for network access to non-privileged accounts.",
  "CCI-000776": "The information system uses organization-defined replay-resistant authentication mechanisms for network access to non-privileged accounts.",
  "CCI-000777": "Defines devices and/or types of devices for which identification and authentication is required before establishing a connection.",
  "CCI-000778": "Uniquely identify organization-defined devices and/or types of devices before establishing a local, remote, and/or network connection.",
  "CCI-000779": "The information system authenticates devices before establishing remote network connections using bidirectional authentication between devices that is cryptographically based.",
  "CCI-000780": "The information system authenticates devices before establishing wireless network connections using bidirectional authentication between devices that is cryptographically based.",
  "CCI-000781": "The information system authenticates devices before establishing network connections using bidirectional authentication between devices that is cryptographically based.",
  "CCI-000782": "The organization standardizes, with regard to dynamic address allocation, Dynamic Host Control Protocol (DHCP) lease information and the time assigned to DHCP-enabled devices.",
  "CCI-000783": "Audit lease information when assigned to a device.",
  "CCI-000784": "The organization manages information system identifiers for users and devices by receiving authorization from a designated organizational official to assign a user identifier.",
  "CCI-000785": "The organization manages information system identifiers for users and devices by receiving authorization from a designated organizational official to assign a device identifier.",
  "CCI-000786": "The organization manages information system identifiers for users and devices by selecting an identifier that uniquely identifies an individual.",
  "CCI-000787": "The organization manages information system identifiers for users and devices by selecting an identifier that uniquely identifies a device.",
  "CCI-000788": "The organization manages information system identifiers for users and devices by assigning the user identifier to the intended party.",
  "CCI-000789": "The organization manages information system identifiers for users and devices by assigning the device identifier to the intended device.",
  "CCI-000790": "The organization defines a time period for which the reuse of user identifiers is prohibited.",
  "CCI-000791": "The organization defines a time period for which the reuse of device identifiers is prohibited.",
  "CCI-000792": "The organization manages information system identifiers for users and devices by preventing reuse of user identifiers for an organization-defined time period.",
  "CCI-000793": "The organization manages information system identifiers for users and devices by preventing reuse of device identifiers for an organization-defined time period.",
  "CCI-000794": "The organization defines a time period of inactivity after which the identifier is disabled.",
  "CCI-000795": "The organization manages information system identifiers by disabling the identifier after an organization-defined time period of inactivity.",
  "CCI-000796": "Prohibit the use of system account identifiers that are the same as public identifiers for individual accounts.",
  "CCI-000797": "The organization requires that registration to receive a user ID and password include authorization by a supervisor.",
  "CCI-000798": "The organization requires that registration to receive a user ID and password be done in person before a designated registration authority.",
  "CCI-000799": "The organization requires multiple forms of certification of individual identification, such as documentary evidence or a combination of documents and biometrics, be presented to the registration authority.",
  "CCI-000800": "Defines characteristics for identifying individual status.",
  "CCI-000801": "Manage individual identifiers by uniquely identifying each individual as organization-defined characteristics identifying individual status.",
  "CCI-000802": "The information system dynamically manages identifiers, attributes, and associated access authorizations.",
  "CCI-000803": "Implement mechanisms for authentication to a cryptographic module that meet the requirements of applicable laws, Executive Orders, directives, policies, regulations, standards, and guidance for such authentication.",
  "CCI-000804": "Uniquely identify and authenticate non-organizational users or processes acting on behalf of non-organizational users.",
  "CCI-001544": "Manage system authenticators by ensuring that authenticators have sufficient strength of mechanism for their intended use.",
  "CCI-001610": "Defines the time-period (by authenticator type) for changing/refreshing authenticators.",
  "CCI-001611": "The organization defines the minimum number of special characters for password complexity enforcement.",
  "CCI-001612": "The organization defines the minimum number of upper case characters for password complexity enforcement.",
  "CCI-001613": "The organization defines the minimum number of lower case characters for password complexity enforcement.",
  "CCI-001614": "The organization defines the minimum number of numeric characters for password complexity enforcement.",
  "CCI-001615": "The organization defines the minimum number of characters that are changed when new passwords are created.",
  "CCI-001616": "The organization defines minimum password lifetime restrictions.",
  "CCI-001617": "The organization defines maximum password lifetime restrictions.",
  "CCI-001618": "The organization defines the number of generations for which password reuse is prohibited.",
  "CCI-001619": "The information system enforces password complexity by the minimum number of special characters used.",
  "CCI-001620": "The organization defines the types of and/or specific authenticators for which the registration process must be carried out in person before a designated registration authority with authorization by a designated organizational official (e.g., a supervisor).",
  "CCI-001621": "Implement organization-defined security controls to manage the risk of compromise due to individuals having accounts on multiple systems.",
  "CCI-001932": "The organization documents an identification and authentication policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance.",
  "CCI-001933": "The organization defines the personnel or roles to be recipients of the identification and authentication policy and the procedures to facilitate the implementation of the identification and authentication policy and associated identification and authentication controls.",
  "CCI-001934": "The organization documents procedures to facilitate the implementation of the identification and authentication policy and associated identification and authentication controls.",
  "CCI-001935": "The organization defines the strength of mechanism requirements for the device that is separate from the system gaining access to privileged accounts.",
  "CCI-001936": "The information system implements multifactor authentication for network access to privileged accounts such that one of the factors is provided by a device separate from the system gaining access.",
  "CCI-001937": "The device used in the information system implementation of multifactor authentication for network access to privileged accounts meets organization-defined strength of mechanism requirements.",
  "CCI-001938": "The organization defines the strength of mechanism requirements for the device that is separate from the system gaining access to non-privileged accounts.",
  "CCI-001939": "The information system implements multifactor authentication for network access to non-privileged accounts such that one of the factors is provided by a device separate from the system gaining access.",
  "CCI-001940": "The device used in the information system implementation of multifactor authentication for network access to non-privileged accounts meets organization-defined strength of mechanism requirements.",
  "CCI-001941": "Implement replay-resistant authentication mechanisms for access to privileged accounts and/or non-privileged accounts.",
  "CCI-001942": "The information system implements replay-resistant authentication mechanisms for network access to non-privileged accounts.",
  "CCI-001943": "Defines the system accounts for which single sign-on capability will be provided.",
  "CCI-001944": "Defines the system services for which single sign-on capability will be provided.",
  "CCI-001945": "Provide a single sign-on capability for organization-defined system accounts.",
  "CCI-001946": "Provide a single sign-on capability for organization-defined system services.",
  "CCI-001947": "The organization defines the strength of mechanism requirements for the device that is separate from the system gaining access and is to provide one factor of a multifactor authentication for remote access to privileged accounts.",
  "CCI-001948": "The information system implements multifactor authentication for remote access to privileged accounts such that one of the factors is provided by a device separate from the system gaining access.",
  "CCI-001949": "The device used in the information system implementation of multifactor authentication for remote access to privileged accounts meets organization-defined strength of mechanism requirements.",
  "CCI-001950": "The organization defines the strength of mechanism requirements for the device that is separate from the system gaining access and is to provide one factor of a multifactor authentication for remote access to non-privileged accounts.",
  "CCI-001951": "The information system implements multifactor authentication for remote access to non-privileged accounts such that one of the factors is provided by a device separate from the system gaining access.",
  "CCI-001952": "The device used in the information system implementation of multifactor authentication for remote access to non-privileged accounts meets organization-defined strength of mechanism requirements.",
  "CCI-001953": "Accepts Personal Identity Verification-compliant credentials.",
  "CCI-001954": "Electronically verifies Personal Identity Verification-compliant credentials.",
  "CCI-001955": "Defines the out-of-band authentication to be implemented under organization-defined conditions.",
  "CCI-001956": "Defines the conditions for implementing organization-defined out-of-band authentication.",
  "CCI-001957": "Implement organization-defined out-of-band authentication mechanisms under organization-defined conditions.",
  "CCI-001958": "Authenticate organization-defined devices and/or types of devices before establishing a local, remote, and/or network connection.",
  "CCI-001959": "Defines the devices and/or types of devices the system is to authenticate before establishing a connection.",
  "CCI-001960": "Defines the lease information to be assigned to devices.",
  "CCI-001961": "Defines the lease duration to be assigned to devices.",
  "CCI-001962": "Where addresses are allocated dynamically, standardize dynamic address allocation lease information assigned to devices in accordance with organization-defined lease information.",
  "CCI-001963": "Where addresses are allocated dynamically, standardize dynamic address allocation lease duration assigned to devices in accordance with organization-defined lease duration.",
  "CCI-001964": "The organization defines the configuration management process that is to handle the device identification procedures.",
  "CCI-001965": "Defines the configuration management process that is to handle the device authentication procedures.",
  "CCI-001966": "Handle device identification based on attestation is handled by the organization-defined configuration management process.",
  "CCI-001967": "Authenticate organization-defined devices and/or types of devices before establishing a local, remote, and/or network connection using bidirectional authentication that is cryptographically based.",
  "CCI-001968": "Defines the configuration management process that is to handle the device identification procedures.",
  "CCI-001969": "Handle device authentication based on attestation is handled by the organization-defined configuration management process.",
  "CCI-001970": "Defines the personnel or roles that authorize the assignment of individual, group, role, and device identifiers.",
  "CCI-001971": "Manage system identifiers by receiving authorization from organization-defined personnel or roles to assign an individual, group, role, or device identifier.",
  "CCI-001972": "Manage system identifiers by selecting an identifier that identifies an individual, group, role, or device.",
  "CCI-001973": "Manage system identifiers by assigning the identifier to the intended individual, group, role, or device.",
  "CCI-001974": "Defines the time period for which the reuse of identifiers is prohibited.",
  "CCI-001975": "Manage system identifiers by preventing reuse of identifiers for an organization-defined time period.",
  "CCI-001976": "Manage individual identifiers dynamically in accordance with organization-defined identifier policy.",
  "CCI-001977": "Defines the external organizations with which it will coordinate for cross-management of identifiers.",
  "CCI-001978": "Coordinate with organization-defined external organizations for cross-organization management of identifiers.",
  "CCI-001979": "The organization requires the registration process to receive an individual identifier be conducted in person before a designated registration authority.",
  "CCI-001980": "Manage system authenticators by verifying, as part of the initial authenticator distribution, the identity of the individual, group, role, service, or device receiving the authenticator.",
  "CCI-001981": "Manage system authenticators by establishing administrative procedures for initial authenticator distribution.",
  "CCI-001982": "The organization manages information system authenticators by establishing administrative procedures for lost/compromised authenticators.",
  "CCI-001983": "The organization manages information system authenticators by establishing administrative procedures for damaged authenticators.",
  "CCI-001984": "Manage system authenticators by establishing administrative procedures for revoking authenticators.",
  "CCI-001985": "Manage system authenticators by implementing administrative procedures for initial authenticator distribution.",
  "CCI-001986": "The organization manages information system authenticators by implementing administrative procedures for lost/compromised authenticators.",
  "CCI-001987": "The organization manages information system authenticators by implementing administrative procedures for damaged authenticators.",
  "CCI-001988": "Manage system authenticators by implementing administrative procedures for revoking authenticators.",
  "CCI-001989": "The organization manages information system authenticators by changing default content of authenticators prior to information system installation.",
  "CCI-001990": "Manage system authenticators by changing authenticators for group or role accounts when membership to those accounts changes.",
  "CCI-001991": "The information system, for PKI-based authentication, implements a local cache of revocation data to support path discovery and validation in case of inability to access revocation information via the network.",
  "CCI-001992": "The organization defines the personnel or roles responsible for authorizing the organization's registration authority accountable for the authenticator registration process.",
  "CCI-001993": "The organization defines the registration authority accountable for the authenticator registration process.",
  "CCI-001994": "The organization defines the types of and/or specific authenticators that are subject to the authenticator registration process.",
  "CCI-001995": "The organization requires that the registration process, to receive organization-defined types of and/or specific authenticators, be conducted in person, or by a trusted third-party, before an organization-defined registration authority with authorization by organization-defined personnel or roles.",
  "CCI-001996": "The organization defines the requirements required by the automated tools to determine if password authenticators are sufficiently strong.",
  "CCI-001997": "The organization employs automated tools to determine if password authenticators are sufficiently strong to satisfy organization-defined requirements.",
  "CCI-001998": "Require developers and installers of system components to provide unique authenticators or change default authenticators prior to delivery and installation.",
  "CCI-001999": "The organization defines the external organizations to be coordinated with for cross-organization management of credentials.",
  "CCI-002000": "The organization coordinates with organization-defined external organizations for cross-organization management of credentials.",
  "CCI-002001": "Bind identities and authenticators dynamically using organization-defined binding rules.",
  "CCI-002002": "The organization defines the token quality requirements to be employed by the information system mechanisms for token-based authentication.",
  "CCI-002003": "The information system, for token-based authentication, employs mechanisms that satisfy organization-defined token quality requirements.",
  "CCI-002004": "Defines the biometric quality requirements to be employed by the mechanisms for biometric-based authentication.",
  "CCI-002005": "For biometric-based authentication, employ mechanisms that satisfy organization-defined biometric quality requirements.",
  "CCI-002006": "Defines the time period after which the use of cached authenticators is prohibited.",
  "CCI-002007": "Prohibit the use of cached authenticators after an organization-defined time period.",
  "CCI-002008": "For PKI-based authentication, employs an organization-wide methodology for managing the content of PKI trust stores installed across all platforms including networks, operating systems, browsers, and applications.",
  "CCI-002009": "Accept Personal Identity Verification-compliant credentials from other federal agencies.",
  "CCI-002010": "Electronically verify Personal Identity Verification-compliant credentials from other federal agencies.",
  "CCI-002011": "The information system accepts FICAM-approved third-party credentials.",
  "CCI-002012": "The organization defines the information systems which will employ only FICAM-approved information system components.",
  "CCI-002013": "The organization employs only FICAM-approved information system components in organization-defined information systems to accept third-party credentials.",
  "CCI-002014": "The information system conforms to FICAM-issued profiles.",
  "CCI-002015": "Accept federated or PKI credentials that meet organization-defined policy.",
  "CCI-002016": "Verify federated PKI credentials that meet organization-defined policy.",
  "CCI-002017": "The organization defines the information system services requiring identification.",
  "CCI-002018": "Defines the system services and applications requiring authentication.",
  "CCI-002019": "The organization defines the security safeguards to be used when identifying information system services.",
  "CCI-002020": "The organization defines the security safeguards to be used when authenticating information system services.",
  "CCI-002021": "Uniquely identify organization-defined system services and applications before establishing communications with devices, users, or other services or applications.",
  "CCI-002022": "Uniquely authenticate organization-defined system services and applications before establishing communications with devices, users, or other services or applications.",
  "CCI-002023": "The organization ensures that service providers receive identification information.",
  "CCI-002024": "The organization ensures that service providers validate identification information.",
  "CCI-002025": "The organization ensures that service providers transmit identification information.",
  "CCI-002026": "The organization ensures that service providers receive authentication information.",
  "CCI-002027": "The organization ensures that service providers validate authentication information.",
  "CCI-002028": "The organization ensures that service providers transmit authentication information.",
  "CCI-002029": "The organization defines the services between which identification decisions are to be transmitted.",
  "CCI-002030": "The organization defines the services between which authentication decisions are to be transmitted.",
  "CCI-002031": "The organization ensures that identification decisions are transmitted between organization-defined services consistent with organizational policies.",
  "CCI-002032": "The organization ensures that authentication decisions are transmitted between organization-defined services consistent with organizational policies.",
  "CCI-002033": "Defines the specific circumstances or situations when individuals accessing the system employ organization-defined supplemental authentication techniques or mechanisms.",
  "CCI-002034": "Defines the supplemental authentication techniques or mechanisms to be employed in specific organization-defined circumstances or situations by individuals accessing the system.",
  "CCI-002035": "Require individuals accessing the system employ organization-defined supplemental authentication techniques or mechanisms under specific organization-defined circumstances or situations.",
  "CCI-002036": "Defines the circumstances or situations under which users will be required to reauthenticate.",
  "CCI-002037": "The organization defines the circumstances or situations under which devices will be required to reauthenticate.",
  "CCI-002038": "The organization requires users to reauthenticate upon organization-defined circumstances or situations requiring reauthentication.",
  "CCI-002039": "The organization requires devices to reauthenticate upon organization-defined circumstances or situations requiring reauthentication.",
  "CCI-002040": "The organization requires that the registration process to receive an individual identifier includes supervisor authorization.",
  "CCI-002041": "The information system allows the use of a temporary password for system logons with an immediate change to a permanent password.",
  "CCI-002042": "Manage system authenticators by protecting authenticator content from unauthorized modification.",
  "CCI-002043": "The organization uses only FICAM-approved path discovery and validation products and services.",
  "CCI-002365": "The organization manages information system authenticators by requiring individuals to take specific security safeguards to protect authenticators.",
  "CCI-002366": "The organization manages information system authenticators by having devices implement specific security safeguards to protect authenticators.",
  "CCI-002367": "The organization ensures unencrypted static authenticators are not embedded in applications.",
  "CCI-004031": "Defines the personnel or roles the organization-level; mission/business process-level; and/or system-level identification and authorization policy is disseminated to.",
  "CCI-004032": "Develop and document an organization-level; mission/business process-level; and/or system-level identification and authorization policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination, among organizational entities, and compliance.",
  "CCI-004033": "Develop and document an organization-level; mission/business process-level; and/or system-level identification and authorization policy that is consistent with applicable laws, Executive Orders, directives, regulations, policies, standards, and guidelines.",
  "CCI-004034": "Develop and document the procedures to facilitate the implementation of the identification and authorization policy and the associated identification and authentication controls.",
  "CCI-004035": "Designate an organization-defined official to manage development and documentation of the identification and authentication policy.",
  "CCI-004036": "Designate an organization-defined official to manage dissemination of the identification and authentication policy.",
  "CCI-004037": "Designate an organization-defined official to manage development and documentation of the identification and authentication procedures.",
  "CCI-004038": "Designate an organization-defined official to manage dissemination of the identification and authentication procedures.",
  "CCI-004039": "Defines the official designated to managing the development, documentation, and dissemination of the identification and authentication policy.",
  "CCI-004040": "Defines the official designated to managing the development, documentation, and dissemination of the identification and authentication procedures.",
  "CCI-004041": "Review and update the current identification and authentication policy following organization-defined events.",
  "CCI-004042": "Defines the events following reviewing and updating the current identification and authentication policy.",
  "CCI-004043": "Review and update the current identification and authentication procedures following organization-defined events.",
  "CCI-004044": "Defines the events following reviewing and updating the current identification and authentication procedures.",
  "CCI-004045": "Require users to be individually authenticated before granting access to the shared accounts or resources.",
  "CCI-004046": "Implement multi-factor authentication for local; network; and/or remote access to privileged accounts; and/or non-privileged accounts such that one of the factors is provided by a device separate from the system gaining access.",
  "CCI-004047": "Implement multi-factor authentication for local; network; and/or remote access to privileged accounts; and/or non-privileged accounts such that the device meets organization-defined strength of mechanism requirements.",
  "CCI-004048": "Defines the strength of mechanism requirements for implementing multi-factor authentication.",
  "CCI-004049": "Defines the dynamic identifier policy for managing individual identifiers dynamically.",
  "CCI-004050": "Generate pairwise pseudonymous identifiers.",
  "CCI-004051": "Maintain the attributes for each uniquely identified individual, device, or service in organization-defined protected central storage.",
  "CCI-004052": "Defines the protected central storage for maintaining the attributes for each uniquely individual, device or service.",
  "CCI-004053": "Manage system authenticators by establishing administrative procedures for lost/compromised or damaged authenticators.",
  "CCI-004054": "Manage system authenticators by implementing administrative procedures for lost/compromised or damaged authenticators.",
  "CCI-004055": "Manage system authenticators by changing default authenticators prior to first use.",
  "CCI-004056": "Defines the events for when to change or refresh authenticators.",
  "CCI-004057": "Defines the frequency for updating commonly used, expected, or compromised passwords, when they are suspected of being compromised directly or indirectly.",
  "CCI-004058": "For password-based authentication, maintain a list of commonly used, expected, or compromised passwords on an organization-defined frequency.",
  "CCI-004059": "For password-based authentication, update the list of passwords on an organization-defined frequency.",
  "CCI-004060": "For password-based authentication, update the list of passwords when organizational passwords are suspected to have been compromised directly or indirectly.",
  "CCI-004061": "For password-based authentication, verify when users create or update passwords, that the passwords are not found on the list of commonly-used, expected, or compromised passwords in IA-5 (1) (a).",
  "CCI-004062": "For password-based authentication, store passwords using an approved salted key derivation function, preferably using a keyed hash.",
  "CCI-004063": "For password-based authentication, require immediate selection of a new password upon account recovery.",
  "CCI-004064": "For password-based authentication, allow user selection of long passwords and passphrases, including spaces and all printable characters.",
  "CCI-004065": "For password-based authentication, employ automated tools to assist the user in selecting strong password authenticators.",
  "CCI-004066": "For password-based authentication, enforce organization-defined composition and complexity rules.",
  "CCI-004067": "Defines the composition and complexity rules to be enforced.",
  "CCI-004068": "For public key-based authentication, implement a local cache of revocation data to support path discovery and validation.",
  "CCI-004069": "Ensure that the unencrypted static authenticators are not embedded in applications or other forms of static storage.",
  "CCI-004070": "Use organization-defined external organizations to federate credentials.",
  "CCI-004071": "Defines the external organizations used to federate credentials.",
  "CCI-004072": "Defines the binding rules for binding identities and authenticators.",
  "CCI-004073": "Use only General Services Administration-approved and validated products and services for identity, credential, and access management.",
  "CCI-004074": "Require that the issuance of organization-defined types of and/or specific authenticators be conducted in person or by a trusted external party before the organization-defined registration authority with authorization by organization-defined personnel or roles.",
  "CCI-004075": "Defines types of and/or specific authenticators to be conducted in person or by a trusted external party before the organization-defined registration authority.",
  "CCI-004076": "Defines the registration authority who conducts the issuance of organization-defined types of and/or specific authenticators.",
  "CCI-004077": "Defines the personnel or roles who authorize the issuance of organization-defined types of and/or specific authenticators.",
  "CCI-004078": "Employ presentation attack detection mechanisms for biometric-based authentication.",
  "CCI-004079": "Employ organization-defined password managers to generate and manage passwords.",
  "CCI-004080": "Defines the password managers employed to generate and manage passwords.",
  "CCI-004081": "Protect the passwords using organization-defined controls.",
  "CCI-004082": "Defines the controls for protecting the passwords.",
  "CCI-004083": "Accept only external credentials that are NIST compliant.",
  "CCI-004084": "Document and maintain a list of accepted external authenticators.",
  "CCI-004085": "Conform to organization-defined identity management profiles for identity management.",
  "CCI-004086": "Defines the identity management profiles for conforming to the profiles for identity management.",
  "CCI-004087": "Defines the policy for accepting and verifying federated or PKI credentials.",
  "CCI-004088": "Implement organization-defined measures to disassociate user attributes or identifier assertion relationships among individuals.",
  "CCI-004089": "Implement organization-defined measures to disassociate user attributes or identifier assertion relationships among credential service providers.",
  "CCI-004090": "Implement organization-defined measures to disassociate user attributes or identifier assertion relationships among relying parties.",
  "CCI-004091": "Defines the measures to be implemented to disassociate user attributes or identifier assertion relationships among individuals, credential service providers, and relying parties.",
  "CCI-004092": "Identity proof users that require accounts for logical access to systems based on appropriate identity assurance level requirements as specified in applicable standards.",
  "CCI-004093": "Identity proof users that require accounts for logical access to systems based on appropriate identity assurance level requirements as specified in applicable guidelines.",
  "CCI-004094": "Resolve user identities to a unique individual.",
  "CCI-004095": "Collect identity evidence.",
  "CCI-004096": "Validate identity evidence.",
  "CCI-004097": "Verify identity evidence.",
  "CCI-004098": "Require that the registration process to receive an account for logical access includes supervisor or sponsor authorization.",
  "CCI-004099": "Require evidence of individual identification be presented to the registration authority.",
  "CCI-004100": "Require that the presented identity evidence be validated through organizational defined methods of validation.",
  "CCI-004101": "Require that the presented identity evidence be verified through organizational defined methods of verification.",
  "CCI-004102": "Defines the methods of validation required for presenting identity evidence.",
  "CCI-004103": "Defines the methods of verification required for presenting identity evidence.",
  "CCI-004104": "Require that the validation of identity evidence be conducted in person before a designated registration authority.",
  "CCI-004105": "Require that the verification of identity evidence be conducted in person before a designated registration authority.",
  "CCI-004106": "Require that a registration code or notice of proofing be delivered through an out-of-band channel to verify the users address (physical or digital) of record.",
  "CCI-004107": "Accept externally-proofed identities at an organization-defined identity assurance level.",
  "CCI-004108": "Defines the identity assurance level by accepting externally-proofed identities.",
};
