/**
 * DISA CCI definitions — MA — Maintenance.
 *
 * Do not hand-edit — regenerate with: node scripts/gen-cci-catalog.mjs
 *
 * Loaded on demand by loadCciFamily("MA") in @/lib/cci-catalog. The index
 * there carries every other field; this chunk is only the definition prose.
 *
 * Source: U_CCI_List_2024.xml (DISA CCI list 2024-01-10), via a public mirror of the
 * DISA Cyber Exchange list. DISA CCI is a US Government work.
 */

export const cciDefinitions: Record<string, string> = {
  "CCI-000851": "Defines the frequency with which to review and update the current system maintenance policy.",
  "CCI-000852": "Develop and document an organization-level; mission/business process-level; and/or system-level maintenance policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance.",
  "CCI-000853": "Disseminate an organization-level; mission/business process-level; and/or system-level maintenance policy to organization-defined personnel or roles.",
  "CCI-000854": "Review and update the current maintenance policy in accordance with organization-defined frequency.",
  "CCI-000855": "Develop and document procedures to facilitate the implementation of the system maintenance policy and associated system maintenance controls.",
  "CCI-000856": "Disseminate procedures to facilitate the implementation of the system maintenance policy and associated system maintenance controls to organization-defined personnel or roles.",
  "CCI-000857": "Review and update the current maintenance procedures in accordance with organization-defined frequency.",
  "CCI-000858": "The organization schedules, performs, documents, and reviews records of maintenance and repairs on information system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-000859": "The organization approves and monitors all maintenance activities, whether performed on site or remotely and whether the equipment is serviced on site or removed to another location.",
  "CCI-000860": "Require that organization-defines personnel or roles explicitly approve the removal of the system or system components from organizational facilities for off-site maintenance, repair, or replacement.",
  "CCI-000861": "Sanitize equipment to remove organization-defined information from associated media prior to removal from organizational facilities for off-site maintenance, repairs or replacement.",
  "CCI-000862": "Check all potentially impacted controls to verify that the controls are still functioning properly following maintenance, repair or replacement actions.",
  "CCI-000863": "The organization maintains maintenance records for the information system that include the date and time of maintenance, the name of the individual performing the maintenance, the name of escort, if necessary, a description of the maintenance performed, and a list of equipment removed or replaced (including identification numbers, if applicable).",
  "CCI-000864": "The organization employs automated mechanisms to schedule, conduct, and document maintenance and repairs as required.",
  "CCI-000865": "Approve the use of system maintenance tools.",
  "CCI-000866": "Control the use of system maintenance tools.",
  "CCI-000867": "Monitor the use of system maintenance tools.",
  "CCI-000868": "The organization maintains, on an ongoing basis, information system maintenance tools.",
  "CCI-000869": "Inspect the maintenance tools used by maintenance personnel for improper or unauthorized modifications.",
  "CCI-000870": "Check media containing diagnostic and test programs for malicious code before the media are used in the system.",
  "CCI-000871": "Prevent the unauthorized removal of maintenance equipment containing organizational information by: (a) verifying that there is no organizational information contained on the equipment; (b) sanitizing or destroying the equipment; (c) retaining the equipment within the facility; or (d) obtaining an exemption from organization-defined personnel or roles explicitly authorizing removal of the equipment from the facility.",
  "CCI-000872": "The organization employs automated mechanisms to restrict the use of maintenance tools to authorized personnel only.",
  "CCI-000873": "Approve nonlocal maintenance and diagnostic activities.",
  "CCI-000874": "Monitor nonlocal maintenance and diagnostic activities.",
  "CCI-000875": "The organization controls non-local maintenance and diagnostic activities.",
  "CCI-000876": "Allow the use of nonlocal maintenance and diagnostic tools only as consistent with organizational policy and documented in the security plan for the information system.",
  "CCI-000877": "Employ strong authentication in the establishment of nonlocal maintenance and diagnostic sessions.",
  "CCI-000878": "Maintain records for nonlocal maintenance and diagnostic activities.",
  "CCI-000879": "The organization terminates sessions and network connections when nonlocal maintenance is completed.",
  "CCI-000880": "The organization audits non-local maintenance and diagnostic sessions.",
  "CCI-000881": "The organization documents, in the security plan for the information system, the policies and procedures for the establishment and use of nonlocal maintenance and diagnostic connections.",
  "CCI-000882": "Require that nonlocal maintenance and diagnostic services be performed from a system that implements a security capability comparable to the capability implemented on the system being serviced.",
  "CCI-000883": "Remove the component to be serviced from the system prior to nonlocal maintenance or diagnostic services; sanitize the component (for organizational information).",
  "CCI-000884": "Protect nonlocal maintenance sessions by employing organization-defined authenticators that are replay resistant.",
  "CCI-000885": "The organization requires that maintenance personnel notify organization-defined personnel when non-local maintenance is planned (i.e., date/time).",
  "CCI-000886": "Defines the personnel or roles to be notified of the date and time of planned nonlocal maintenance.",
  "CCI-000887": "Require the approval of each nonlocal maintenance session by organization-defined personnel or roles.",
  "CCI-000888": "The organization employs cryptographic mechanisms to protect the integrity and confidentiality of non-local maintenance and diagnostic communications.",
  "CCI-000889": "The organization employs remote disconnect verification at the termination of non-local maintenance and diagnostic sessions.",
  "CCI-000890": "Establish a process for maintenance personnel authorization.",
  "CCI-000891": "Maintain a list of authorized maintenance organizations or personnel.",
  "CCI-000892": "The organization ensures that personnel performing maintenance on the information system have required access authorizations or designates organizational personnel with required access authorizations and technical competence deemed necessary to supervise information system maintenance.",
  "CCI-000893": "Implement procedures for the use of maintenance personnel that lack appropriate security clearances or are not U.S. citizens.",
  "CCI-000894": "Requires maintenance personnel who do not have needed access authorizations, clearances, or formal access approvals to be escorted and supervised during the performance of maintenance and diagnostic activities on the system by approved organizational personnel who are fully cleared, have appropriate access authorizations, and are technically qualified.",
  "CCI-000895": "Require that, prior to initiating maintenance or diagnostic activities by personnel who do not have needed access authorizations, clearances or formal access approvals, all volatile information storage components within the system be sanitized and all nonvolatile storage media be removed or physically disconnected from the system and secured.",
  "CCI-000896": "The organization requires that in the event an information system component cannot be sanitized, the procedures contained in the security plan for the system be enforced.",
  "CCI-000897": "Verify that personnel performing maintenance and diagnostic activities on a system processing, storing, or transmitting classified information possess security clearances and formal access approvals for at least the highest classification level and for all compartments of information on the system.",
  "CCI-000898": "Verify that personnel performing maintenance and diagnostic activities on a system processing, storing, or transmitting classified information are U.S. citizens.",
  "CCI-000899": "Ensure that cleared foreign nationals with appropriate security clearances are used to conduct maintenance and diagnostic activities on classified systems only when the systems are jointly owned and operated by the United States and foreign allied governments, or owned and operated solely by foreign allied governments.",
  "CCI-000900": "Ensure that that approvals, consents, and detailed operational conditions regarding the use of foreign nationals to conduct maintenance and diagnostic activities on classified systems are fully documented within Memoranda of Agreements.",
  "CCI-000901": "The organization defines a list of security-critical information system components and/or key information technology components for which it will obtain maintenance support and/or spare parts.",
  "CCI-000902": "The organization defines a time period for obtaining maintenance support and/or spare parts for security-critical information system components and/or key information technology components.",
  "CCI-000903": "Obtain maintenance support and/or spare parts for organization-defined system components within an organization-defined time period of failure.",
  "CCI-001628": "Defines a frequency with which to review and update the current maintenance procedures.",
  "CCI-001629": "The organization employs automated mechanisms to produce up-to-date, accurate, complete, and available records of all maintenance and repair actions needed, in process, and complete.",
  "CCI-001630": "Designated organizational personnel review the maintenance records of the non-local maintenance and diagnostic sessions.",
  "CCI-001631": "After the service is performed, inspect and sanitize the component (for potentially malicious software) before reconnecting the component to the system.",
  "CCI-001632": "Protect nonlocal maintenance sessions by separating the maintenance session from other network sessions with the system by either physically separated communications paths or logically separated communications paths based upon encryption.",
  "CCI-002861": "Defines the personnel or roles to whom an organization-level; mission/business process-level; and/or system-level maintenance policy is disseminated.",
  "CCI-002862": "Defines the personnel or roles to whom system maintenance procedures are to be disseminated.",
  "CCI-002863": "The organization employs automated mechanisms to schedule, conduct, and document repairs.",
  "CCI-002864": "Produce up-to date, accurate, and complete records of all maintenance requested, scheduled, in process, and completed.",
  "CCI-002865": "Produce up-to date, accurate, and complete records of all repair actions requested, scheduled, in process, and completed.",
  "CCI-002866": "Schedule maintenance on system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-002867": "The organization performs maintenance on information system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-002868": "Document records of maintenance on system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-002869": "Review records of maintenance on system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-002870": "Schedule repair on system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-002871": "The organization performs repairs on information system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-002872": "Document repair on system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-002873": "Review records of repairs on system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-002874": "Defines the personnel or roles who can explicitly approve the removal of the system or system components from organizational facilities for off-site maintenance, repairs or replacement.",
  "CCI-002875": "Include organization-defined information in organizational maintenance records.",
  "CCI-002876": "Defines the information to include in organizational maintenance records.",
  "CCI-002877": "The organization prevents the unauthorized removal of maintenance equipment containing organizational information by verifying that there is no organizational information contained on the equipment.",
  "CCI-002878": "The organization prevents the unauthorized removal of maintenance equipment containing organizational information by sanitizing or destroying the equipment.",
  "CCI-002879": "The organization prevents the unauthorized removal of maintenance equipment containing organizational information by retaining the equipment within the facility.",
  "CCI-002880": "The organization prevents the unauthorized removal of maintenance equipment containing organizational information by retaining the equipment within the facility.",
  "CCI-002881": "The organization prevents the unauthorized removal of maintenance equipment containing organizational information by obtaining an exemption from organization-defined personnel or roles explicitly authorizing removal of the equipment from the facility.",
  "CCI-002882": "Defines the personnel or roles who can provide an exemption that explicitly authorizes removal of equipment from the facility.",
  "CCI-002883": "Restrict the use of maintenance tools to authorized personnel only.",
  "CCI-002884": "Log organization-defined audit events for nonlocal maintenance and diagnostic sessions.",
  "CCI-002885": "Defines the audit events for logged for nonlocal maintenance and diagnostic sessions.",
  "CCI-002886": "Review the audit records of the maintenance and diagnostic sessions to detect anomalous behavior.",
  "CCI-002887": "Defines the authenticators that are replay resistant which will be employed to protect nonlocal maintenance sessions.",
  "CCI-002888": "Defines the personnel or roles authorized to approve each nonlocal maintenance session.",
  "CCI-002889": "Notify organization-defined personnel or roles of the date and time of planned nonlocal maintenance.",
  "CCI-002890": "Implement organization-defined cryptographic mechanisms to protect the integrity of nonlocal maintenance and diagnostic communications.",
  "CCI-002891": "Verify session and network connection termination after the completion of nonlocal maintenance and diagnostic sessions.",
  "CCI-002892": "The organization develops and implements alternate security safeguards in the event an information system component cannot be sanitized, removed, or disconnected from the system.",
  "CCI-002893": "Ensure that non-escorted personnel performing maintenance activities not directly associated with the system but in the physical proximity of the system, have required access authorization.",
  "CCI-002894": "Verify that non-escorted personnel performing maintenance on the system possess the required access authorizations.",
  "CCI-002895": "Designate organizational personnel with required access authorizations and technical competence to supervise the maintenance activities of personnel who do not possess the required access authorizations.",
  "CCI-002896": "Defines the system components for which it obtains maintenance support and/or spare parts.",
  "CCI-002897": "Defines a time period for obtaining maintenance support and/or spare parts for organization-defined system components after a failure.",
  "CCI-002898": "Perform preventive maintenance on organization-defined information system components at organization-defined time intervals.",
  "CCI-002899": "Defines system components on which to perform preventive maintenance.",
  "CCI-002900": "Defines time intervals at which to perform preventive maintenance on organization-defined system components.",
  "CCI-002901": "Perform predictive maintenance on organization-defined system components at organization-defined intervals.",
  "CCI-002902": "Defines system components on which to perform predictive maintenance.",
  "CCI-002903": "Defines time intervals at which to perform predictive maintenance on organization-defined system components.",
  "CCI-002904": "Transfer predictive maintenance data to a maintenance management system using organization-defined automated mechanisms.",
  "CCI-002905": "The organization employs automated mechanisms to schedule, conduct, and document maintenance.",
  "CCI-003123": "Implement organization-defined cryptographic mechanisms to protect the confidentiality of nonlocal maintenance and diagnostic communications.",
  "CCI-004165": "Develop and document an organization-level; mission/business process-level; and/or system-level maintenance policy that is consistent with applicable laws, Executive Orders, directives, regulations, policies, standards, and guidelines.",
  "CCI-004166": "Designate an organization-defined official to manage the development, documentation, and dissemination of the maintenance policy.",
  "CCI-004167": "Designate an organization-defined official to manage the development, documentation, and dissemination of the maintenance procedures.",
  "CCI-004168": "Defines the official who will manage the development, documentation, and dissemination of the maintenance policy.",
  "CCI-004169": "Defines the official who will manage the development, documentation, and dissemination of the maintenance procedures.",
  "CCI-004170": "Review and update the current maintenance policy following organization-defined events.",
  "CCI-004171": "Defines the events following reviewing and updating the current maintenance policy.",
  "CCI-004172": "Review and update the current maintenance procedures following organization-defined events.",
  "CCI-004173": "Defines the events following reviewing and updating the current maintenance procedures.",
  "CCI-004174": "Schedule replacement on system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-004175": "Document replacement on system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-004176": "Review records of replacement on system components in accordance with manufacturer or vendor specifications and/or organizational requirements.",
  "CCI-004177": "Approve all maintenance activities, whether performed on site or remotely.",
  "CCI-004178": "Monitor all maintenance activities, whether performed on site or remotely.",
  "CCI-004179": "Approve all maintenance activities, whether the system or system components are serviced on site or removed to another location.",
  "CCI-004180": "Monitor all maintenance activities, whether the system or system components are serviced on site or removed to another location.",
  "CCI-004181": "Defines the information to be removed from associated media.",
  "CCI-004182": "Schedule maintenance, repair, and replacement actions for the system using organization-defined automated mechanisms.",
  "CCI-004183": "Conduct maintenance, repair, and replacement actions for the system using organization-defined automated mechanisms.",
  "CCI-004184": "Document maintenance, repair, and replacement actions for the system using organization-defined automated mechanisms.",
  "CCI-004185": "Produce up-to date, accurate, and complete records of all replacement actions requested, scheduled, in process, and completed.",
  "CCI-004186": "Review previously approved system maintenance tools on an organization-defined frequency.",
  "CCI-004187": "Defines the frequency for reviewing previously approved system maintenance tools.",
  "CCI-004188": "Monitor the use of maintenance tools that execute with increased privilege.",
  "CCI-004189": "Inspect the maintenance tools to ensure the latest software updates and patches are installed.",
  "CCI-004190": "Terminate session when nonlocal maintenance is completed.",
  "CCI-004191": "Terminate network connection when nonlocal maintenance is completed.",
  "CCI-004192": "Protect nonlocal maintenance sessions by separating the maintenance session from other network sessions with the system by logically separated communications paths.",
  "CCI-004193": "Defines the cryptographic mechanisms for protecting the integrity and confidentiality of nonlocal maintenance and diagnostic communications.",
  "CCI-004194": "Develop organization-defined alternate controls in the event a system component cannot be sanitized, removed, or disconnected from the system.",
  "CCI-004195": "Implement organization-defined alternate controls in the event a system component cannot be sanitized, removed, or disconnected from the system.",
  "CCI-004196": "Defines alternate controls in the event a system component cannot be sanitized, removed, or disconnected from the system.",
  "CCI-004197": "Defines the automated mechanisms for transferring predictive maintenance data to a maintenance system.",
  "CCI-004198": "Restrict or prohibit field maintenance on organization-defined systems or system components to organization-defined trusted maintenance facilities.",
  "CCI-004199": "Defines the systems or system components which restrict or prohibit field maintenance.",
  "CCI-004200": "Defines the trusted maintenance facilities which the systems or system components restrict or prohibit field maintenance.",
};
