/**
 * DISA CCI definitions — PS — Personnel Security.
 *
 * Do not hand-edit — regenerate with: node scripts/gen-cci-catalog.mjs
 *
 * Loaded on demand by loadCciFamily("PS") in @/lib/cci-catalog. The index
 * there carries every other field; this chunk is only the definition prose.
 *
 * Source: U_CCI_List_2024.xml (DISA CCI list 2024-01-10), via a public mirror of the
 * DISA Cyber Exchange list. DISA CCI is a US Government work.
 */

export const cciDefinitions: Record<string, string> = {
  "CCI-001504": "Develop and document an organization-level; mission/business process-level; and/or system-level personnel security policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance.",
  "CCI-001505": "Disseminate an organization-level; mission/business process-level; and/or system-level personnel security policy to organization-defined personnel or roles.",
  "CCI-001506": "Review and update the current personnel security policy in accordance with organization-defined frequency.",
  "CCI-001507": "Defines the frequency with which to review and update the current personnel security policy.",
  "CCI-001508": "Defines the frequency with which to review and update the current personnel security procedures.",
  "CCI-001509": "Develop and document procedures to facilitate the implementation of the personnel security policy and associated personnel security controls.",
  "CCI-001510": "Disseminate personnel security procedures to organization-defined personnel or roles.",
  "CCI-001511": "Review and update the current personnel security procedures in accordance with organization-defined frequency.",
  "CCI-001512": "Assign a risk designation to all organizational positions.",
  "CCI-001513": "Establish screening criteria for individuals filling organizational positions.",
  "CCI-001514": "Review and update position risk designations in accordance with organization-defined frequency.",
  "CCI-001515": "Defines the frequency with which to review and update position risk designations.",
  "CCI-001516": "Screen individuals prior to authorizing access to the system.",
  "CCI-001517": "Rescreen individuals with authorized access to the system in accordance with organization-defined conditions requiring rescreening, and where rescreening is so indicated, on the organization-defined frequency of rescreening.",
  "CCI-001518": "Defines the conditions requiring rescreening of individuals with authorized access to the system.",
  "CCI-001519": "Defines the frequency for rescreening individuals with authorized access to the information system when organization-defined conditions requiring rescreening are met.",
  "CCI-001520": "Verify that individuals accessing a system processing, storing, or transmitting classified information are cleared and indoctrinated to the highest classification level of the information to which they have access on the system.",
  "CCI-001521": "Verify that individuals accessing a system processing, storing, or transmitting types of classified information which require formal indoctrination, are formally indoctrinated for all of the relevant types of information to which they have access on the system.",
  "CCI-001522": "Upon termination of individual employment, disable system access within an organization-defined time period.",
  "CCI-001523": "Upon termination of individual employment, conduct exit interviews that include a discussion of organization-defined information security topics.",
  "CCI-001524": "Upon termination of individual employment, retrieve all security-related organizational system-related property.",
  "CCI-001525": "Upon termination of individual employment, retain access to organizational information formerly controlled by the terminated individual.",
  "CCI-001526": "Upon termination of individual employment, retain access to organizational systems formerly controlled by the terminated individual.",
  "CCI-001527": "Review and confirm the ongoing operational need for current logical and physical access authorizations to systems and facilities when individuals are reassigned or transferred to other positions within the organization.",
  "CCI-001528": "Initiate organization-defined transfer or reassignment actions within an organization-defined time period following the formal personnel transfer action.",
  "CCI-001529": "Defines transfer or reassignment actions to initiate within an organization-defined time period following the formal personnel transfer action.",
  "CCI-001530": "Defines the time period within which the organization initiates organization-defined transfer or reassignment actions following the formal personnel transfer action.",
  "CCI-001531": "The organization ensures that individuals requiring access to organizational information and information systems sign appropriate access agreements prior to being granted access.",
  "CCI-001532": "Review and update the access agreements for organizational systems in accordance with organization-defined frequency.",
  "CCI-001533": "Defines the frequency with which to review and update access agreements for organizational systems.",
  "CCI-001534": "The organization ensures that access to information with special protection measures is granted only to individuals who have a valid access authorization that is demonstrated by assigned official government duties.",
  "CCI-001535": "The organization ensures that access to information with special protection measures is granted only to individuals who satisfy associated personnel security criteria.",
  "CCI-001536": "Verify that access to classified information requiring special protection is granted only to individuals who have a valid access authorization that is demonstrated by assigned official government duties.",
  "CCI-001537": "Verify that access to classified information requiring special protection is granted only to individuals who satisfy associated personnel security criteria.",
  "CCI-001538": "Verify that access to classified information requiring special protection is granted only to individuals who have read, understood, and signed a nondisclosure agreement.",
  "CCI-001539": "Establish personnel security requirements including security roles and responsibilities for external providers.",
  "CCI-001540": "Document personnel security requirements.",
  "CCI-001541": "Monitor provider compliance with personnel security requirements.",
  "CCI-001542": "The organization employs a formal sanctions process for individuals failing to comply with established information security policies and procedures.",
  "CCI-003016": "The organization, upon termination of individual employment, notifies organization-defined personnel or roles within an organization-defined time period.",
  "CCI-003017": "Defines the personnel or roles to whom an organization-level; mission/business process-level; and/or system-level personnel security policy is disseminated.",
  "CCI-003018": "Defines the personnel or roles to whom the personnel security procedures are disseminated.",
  "CCI-003019": "Verify that individuals accessing a system processing, storing, or transmitting information requiring special protection have valid access authorizations that are demonstrated by assigned official government duties.",
  "CCI-003020": "Verify that individuals accessing a system processing, storing, or transmitting information requiring special protection satisfy organization-defined additional personnel screening criteria.",
  "CCI-003021": "Defines additional personnel screening criteria that individuals accessing a system processing, storing, or transmitting information requiring protection must satisfy.",
  "CCI-003022": "Defines the time period within which to disable system access upon termination of individual employment.",
  "CCI-003023": "Upon termination of individual employment, terminate or revoke any authenticators and credentials associated with the individual.",
  "CCI-003024": "Defines information security topics to be discussed while conducting exit interviews.",
  "CCI-003025": "The organization defines personnel or roles to notify upon termination of individual employment.",
  "CCI-003026": "The organization defines the time period within which to notify organization-defined personnel or roles upon termination of individual employment.",
  "CCI-003027": "Notify terminated individuals of applicable, legally binding post-employment requirements for the protection of organizational information.",
  "CCI-003028": "Require terminated individuals to sign an acknowledgment of post-employment requirements as part of the organizational termination process.",
  "CCI-003029": "Use organization-defined automated mechanisms to notify organization-defined personnel or roles of individual termination actions; and/or disable access to system resources.",
  "CCI-003030": "Defines the personnel or roles to be notified by automated mechanism of individual termination actions, and/or disable access to system resources.",
  "CCI-003031": "Modify access authorization as needed to correspond with any changes in operational need due to reassignment or transfer.",
  "CCI-003032": "Notify organization-defined personnel or roles within an organization-defined time period when individuals are transferred or reassigned to other positions within the organization.",
  "CCI-003033": "Defines personnel or roles to be notified when individuals are transferred or reassigned to other positions within the organization.",
  "CCI-003034": "Defines the time period within which organization-defined personnel or roles are to be notified when individuals are transferred or reassigned to other positions within the organization.",
  "CCI-003035": "Develop and document access agreements for organizational systems.",
  "CCI-003036": "The organization ensures that individuals requiring access to organizational information and information systems re-sign access agreements to maintain access to organizational information systems when access agreements have been updated or in accordance with organization-defined frequency.",
  "CCI-003037": "The organization defines the frequency for individuals requiring access to organization information and information systems to re-sign access agreements.",
  "CCI-003038": "Notify individuals of applicable, legally binding post-employment requirements for protection of organizational information.",
  "CCI-003039": "Require individuals to sign an acknowledgement of legally binding post-employment requirements for protection of organizational information, if applicable, as part of granting initial access to covered information.",
  "CCI-003040": "The organization requires third-party providers to comply with personnel security policies and procedures established by the organization.",
  "CCI-003041": "Require external providers to notify organization-defined personnel or roles of any personnel transfers or terminations of external personnel who possess organizational credentials and/or badges, or who have system privileges within an organization-defined time period.",
  "CCI-003042": "Defines personnel or roles whom external providers are to notify when external personnel who possess organizational credentials and /or badges or who have system privileges are transferred or terminated.",
  "CCI-003043": "Defines the time period for external providers to notify organization-defined personnel or roles when external personnel who possess organizational credentials and/or badges, or who have system privileges are transferred or terminated.",
  "CCI-003044": "Notify organization-defined personnel or roles within an organization-defined time period when a formal employee sanctions process is initiated, identifying the individual sanctioned and the reason for the sanction.",
  "CCI-003045": "Defines personnel or roles who are to be notified when a formal employee sanctions process is initiated.",
  "CCI-003046": "Defines the time period within which to notify organization-defined personnel or roles when a formal employee sanctions process is initiated.",
  "CCI-004498": "Develop and document an organization-level; mission/business process-level; and/or system-level personnel security policy that is consistent with applicable laws, Executive Orders, directives, regulations, policies, standards, and guidelines.",
  "CCI-004499": "Designate an organization-defined official to manage the development and documentation of the personnel security policy.",
  "CCI-004500": "Designate an organization-defined official to manage the dissemination of the personnel security policy.",
  "CCI-004501": "Defines the official who will manage the personnel security policy.",
  "CCI-004502": "Designate an organization-defined official to manage development and documentation of the personnel security procedures.",
  "CCI-004503": "Designate an organization-defined official to manage the dissemination of the personnel security procedures.",
  "CCI-004504": "Defines the official who will manage the personnel security procedures.",
  "CCI-004505": "Review and update the current personnel security policy following organization-defined events.",
  "CCI-004506": "Defines the events following reviewing and updating the current personnel security policy.",
  "CCI-004507": "Review and update the current personnel security procedures following organization-defined events.",
  "CCI-004508": "Defines the events following reviewing and updating the current personnel security procedures.",
  "CCI-004509": "Verify that individuals accessing a system processing, storing, or transmitting organization-defined information types meet organization-defined citizenship requirements.",
  "CCI-004510": "Defines the information types that meet the organization-defined citizenship requirement.",
  "CCI-004511": "Defines the citizenship requirements for individuals accessing a system, storing, or transmitting organization-defined information types.",
  "CCI-004512": "Defines the automated mechanisms for notifying organization-defined personnel or roles of individual termination actions; and/or disable access to system resources.",
  "CCI-004513": "Verify that individuals requiring access to organizational information sign appropriate access agreements prior to being granted access.",
  "CCI-004514": "Verify that individuals requiring access to organizational systems sign appropriate access agreements prior to being granted access.",
  "CCI-004515": "Verify that individuals requiring access to organizational information re-sign access agreements to maintain access to organizational information systems when access agreements have been updated or in accordance with organization-defined frequency.",
  "CCI-004516": "Verify that individuals requiring access to organizational systems re-sign access agreements to maintain access to organizational information systems when access agreements have been updated or in accordance with organization-defined frequency.",
  "CCI-004517": "Defines the frequency for individuals requiring access to organizational information to re-sign access agreements.",
  "CCI-004518": "Defines the frequency for individuals requiring access to organizational systems to re-sign access agreements.",
  "CCI-004519": "Require external providers to comply with personnel security policies established by the organization.",
  "CCI-004520": "Require external providers to comply with personnel security procedures established by the organization.",
  "CCI-004521": "Employ a formal sanctions process for individuals failing to comply with established information security policies.",
  "CCI-004522": "Employ a formal sanctions process for individuals failing to comply with established information security procedures.",
  "CCI-004523": "Incorporate security roles and responsibilities into organizational position descriptions.",
  "CCI-004524": "Incorporate privacy roles and responsibilities into organizational position descriptions.",
};
